const GAME_DATA = {

  // ── Never Have I Ever ──────────────────────────────────────────────────────
  never: [
    "eaten an entire pizza by myself",
    "stayed up for more than 24 hours straight",
    "traveled to a country where I didn't speak the language",
    "cried at a movie in public",
    "gone skinny dipping",
    "pretended to be sick to skip school or work",
    "sent a text to the wrong person",
    "fallen asleep during a meeting or class",
    "eaten food that fell on the floor",
    "lied about my age",
    "sung karaoke in front of strangers",
    "been on a blind date",
    "talked to myself in public",
    "forgotten someone's name right after being introduced",
    "gotten lost in a city I thought I knew",
    "eaten sushi for breakfast",
    "binge-watched an entire TV series in one day",
    "pulled an all-nighter to finish a project",
    "laughed so hard I cried",
    "pretended to enjoy a gift I hated",
    "learned a dance move from a social media trend",
    "taken a selfie with a stranger",
    "accidentally walked into the wrong bathroom",
    "overslept and missed something important",
    "cooked a meal that was completely inedible",
    "gotten a parking ticket",
    "run for a bus and just missed it",
    "spoken to a celebrity",
    "tried a sport and immediately regretted it",
    "gone on a spontaneous road trip",
    "eaten something spicy that made me sweat",
    "re-gifted a present",
    "laughed at my own joke before finishing it",
    "called a teacher 'Mom' or 'Dad' by accident",
    "used Google Translate to talk to someone",
    "bought something expensive on impulse and regretted it",
    "broken a phone screen",
    "slept in a tent outdoors",
    "eaten a food from a different country and loved it",
    "worn mismatched socks on purpose",
    "tried to cook a recipe and completely changed it halfway through",
    "ridden a motorbike or scooter",
    "gone a whole day without my phone",
    "waved back at someone who was waving at the person behind me",
    "had a dream so vivid I thought it was real",
    "made up an excuse to leave a party early",
    "googled the answer during a quiz or exam",
    "eaten cereal without milk because there was none left",
    "memorized a song in a language I don't speak",
    "worn the same clothes two days in a row",
    "snorted while laughing",
    "introduced myself with the wrong name by accident",
    "walked into a glass door",
    "tried to open a door by pushing when it said pull",
    "said 'you too' when a waiter said 'enjoy your meal'",
    "waved at someone's phone thinking they were waving at me",
    "called tech support and felt totally lost",
    "ordered something in a restaurant and immediately regretted it",
    "finished a book in one sitting",
    "taken a long shower just to think",
    "made a fake laugh convincingly",
    "bought something just because it was on sale",
    "had a song stuck in my head for more than a week",
    "tried to fix something and made it worse",
    "done a midnight grocery run",
    "eaten dinner for breakfast",
    "started a workout program and quit within a week",
    "texted someone instead of calling because I was nervous",
    "scrolled my phone for so long I forgot what I was looking for",
    "ordered food delivery when the restaurant was walking distance away",
    "stayed in my pajamas for an entire weekend",
    "thought a movie was great, then re-watched it and changed my mind",
    "tried to speak a language I barely know to impress someone",
    "attempted to parallel park and given up",
    "worn an outfit and immediately wished I'd chosen something else",
    "forgotten a word in my own language mid-sentence",
    "gone to the movies alone",
    "rearranged furniture at midnight",
    "mixed up twins after being told how to tell them apart",
    "gotten so into a book I missed a stop on public transport",
    "left a voicemail and immediately cringed",
    "taken a photo of my food before eating it",
    "created a playlist for a very specific mood",
    "looked something up online, got distracted, and forgot what I was searching for",
    "pretended not to see someone I know to avoid small talk",
    "tried a food I swore I'd hate and ended up loving it",
    "named an inanimate object I own",
    "bought a book fully intending to read it but never did",
    "gone to bed with wet hair",
    "attempted a DIY project that totally failed",
    "held a door open for someone who was too far away",
    "apologized to a piece of furniture I bumped into",
    "laughed at something no one else found funny",
    "said 'I'm almost ready' when I hadn't started getting ready",
    "confused 'your' and 'you're' in a formal message",
    "zoned out completely during a conversation and nodded anyway",
    "set multiple alarms and slept through all of them",
    "said goodbye, then walked in the same direction as the other person",
  ],

  // ── Hot Take Roulette ──────────────────────────────────────────────────────
  hottake: [
    "Pineapple on pizza is not the real problem — the real problem is people who hate it.",
    "Breakfast food tastes better at dinner than at actual breakfast.",
    "Adding cheese to almost anything makes it better.",
    "Spicy food is not really about taste — it is about proving something.",
    "Ordering the same thing every time at a restaurant is a sign of self-awareness, not boring taste.",
    "Sharing food off someone else's plate without asking is completely unacceptable.",
    "Instant noodles deserve way more respect than they get.",
    "If the food is good enough, the atmosphere of a restaurant does not matter at all.",
    "The person who finishes their meal first should have to sit in silence while others catch up.",
    "Drinks are always better with ice, even in winter.",
    "Dessert should come before the main course — life is short.",
    "People who say they 'don't have a favourite food' are lying.",
    "Ghosting someone you barely know is perfectly acceptable.",
    "Long-distance relationships almost never truly work out.",
    "You can fall genuinely in love with someone you have never met in person.",
    "People who arrive exactly on time are more annoying than people who are five minutes late.",
    "Crying in front of others is a sign of strength, not weakness.",
    "Complimenting a stranger is almost always welcome, not awkward.",
    "The best friendships need no explanation after a long silence.",
    "Being liked by everyone is a red flag.",
    "You cannot truly know someone until you have travelled with them.",
    "Most people are far lonelier than they are willing to admit.",
    "A person's true character is revealed by how they treat waiters and cashiers.",
    "The phrase 'We should catch up sometime' almost never actually means it.",
    "Being early to everything is a form of social anxiety, not politeness.",
    "A person who has never been heartbroken has never truly been in love.",
    "TikTok has done more damage to attention spans than any drug ever did.",
    "Replying with just 'K' to a message is passive-aggressive, no matter the context.",
    "Reacting to someone's message with 👍 is the digital equivalent of a dismissive nod.",
    "Voice notes should require the other person's permission before you send one.",
    "Checking your phone first thing every morning is one of the worst habits a person can have.",
    "Social media makes people more lonely, not less.",
    "Everyone performs a different version of themselves online — and that is perfectly fine.",
    "Deleting all social media for a month would make most people genuinely happier.",
    "Online arguments almost never actually change anyone's mind.",
    "A person's texting style tells you more about them than their CV.",
    "The most productive people are rarely the busiest ones.",
    "Homework should be banned for everyone under 14.",
    "A university degree is no longer worth the time or money for most careers.",
    "Most job interviews tell you almost nothing useful about how someone will actually perform.",
    "You should always try to negotiate your salary — no exceptions.",
    "Passion for your work is overrated. Decent pay and good hours matter far more.",
    "Open-plan offices are one of the worst ideas in modern workplace history.",
    "Arriving 10 minutes early to a meeting you did not call is just unpaid work.",
    "The best meetings are the ones that could have been a short email.",
    "Four-day work weeks would make most people more productive, not less.",
    "People who say 'I don't care what others think' usually care the most.",
    "Being bored is actually essential for creativity.",
    "Success in life is mostly about luck, not skill or hard work.",
    "Most adults are not nearly as grown-up as they pretend to be.",
    "Having two or three real friends is far better than having twenty casual ones.",
    "It is more important to be interesting than to be nice.",
    "People change over time, but not nearly as much as they like to claim.",
    "Regret teaches you more than success ever does.",
    "Everyone secretly has at least one truly terrible opinion they will never admit to.",
    "Saying sorry too often actually makes people trust you less, not more.",
    "Small talk is not a waste of time — it is how trust gets built.",
    "The funniest people in the room are almost always hiding something painful.",
    "People who walk slowly in the middle of a crowded pavement are the real villains of society.",
    "Movie sequels are almost always worse than the original — no exceptions.",
    "Spoilers actually make a story more enjoyable to experience, not less.",
    "The best music was almost certainly made before you were born.",
    "Horror films are far more effective watched alone than with a group of friends.",
    "Celebrities do not owe their fans any explanation about their private lives.",
    "Reboots and remakes are completely lazy — and yet we watch every single one.",
    "Silence in a good conversation is not awkward — it means both people are comfortable.",
    "Cats are smarter than dogs. Dogs are just more emotionally needy.",
    "Bad weather makes people more creative and productive, not less.",
    "The last piece of shared food should always go to whoever ate the least.",
  ],

  // ── Story Teller ───────────────────────────────────────────────────────────
  storyteller: {
    characters: [
      "a lost tourist",
      "a nervous student",
      "a tired teacher",
      "a friendly taxi driver",
      "a noisy neighbour",
      "a confused chef",
      "a shy singer",
      "a clumsy waiter",
      "a bossy coach",
      "a forgetful doctor",
      "a brave firefighter",
      "a lazy security guard",
      "a curious little kid",
      "a grumpy old man",
      "a cheerful delivery driver",
      "a helpful stranger",
      "a street musician",
      "a very tall basketball player",
      "a sleepy librarian",
      "an overexcited tour guide",
      "a grandma who loves video games",
      "a proud dad taking too many photos",
      "a nervous bride on her wedding day",
      "a first-day employee at a new job",
      "a very loud sports fan",
      "a bored office worker",
      "a kind old lady with too many bags",
      "a teenage boy trying to look cool",
      "an excited kid on a school trip",
      "a man who has not slept in two days",
      "a very competitive runner",
      "a stressed mother with three young kids",
      "a teenager who just failed their driving test",
      "a retired teacher on holiday",
      "a very shy person on a first date",
    ],
    actions: [
      "finds a bag full of cash on the floor",
      "gets completely lost and asks five different people for help",
      "accidentally breaks something very expensive",
      "misses the last bus home",
      "finds a lost dog on the street",
      "bumps into an old friend they haven't seen in years",
      "wins a surprise prize they never signed up for",
      "forgets someone's name at the worst possible moment",
      "drops their phone into water",
      "gets on the wrong train and ends up in the wrong place",
      "gets soaked in a sudden heavy rainstorm",
      "is mistaken for a famous person",
      "accidentally orders the wrong food in the wrong language",
      "gets stuck in an elevator with a complete stranger",
      "loses their wallet and has no money at all",
      "sends a private message to completely the wrong person",
      "shows up at a party at the totally wrong address",
      "gets locked out of their house at midnight",
      "burns dinner right before the guests arrive",
      "calls someone by the wrong name all day long",
      "picks up someone else's shopping bag by mistake",
      "falls asleep somewhere very embarrassing in public",
      "drops their ice cream on a stranger's shoes",
      "trips and falls in front of a large crowd",
      "walks into the wrong room during a very important meeting",
      "gets hiccups right before giving a big speech",
      "arrives very late and tries to pretend they were there the whole time",
      "signs up for the completely wrong class by mistake",
      "wins an argument but immediately feels terrible about it",
      "runs into their ex at the most awkward possible moment",
      "tries to pay for something and their card is rejected",
      "spills a full drink on a stranger",
      "sends a voice message instead of a regular text by mistake",
      "gives totally wrong directions to someone who needed help",
      "sits down at the wrong table and eats someone else's food",
    ],
    locations: [
      "at a busy supermarket",
      "in a coffee shop",
      "on a crowded bus",
      "at a birthday party",
      "in a school classroom",
      "at a shopping mall",
      "at a train station",
      "in an elevator",
      "at a hospital waiting room",
      "on a beach",
      "in a park",
      "at an airport",
      "in a library",
      "at a wedding",
      "in a gym",
      "on an airplane",
      "at a cinema",
      "in a hotel lobby",
      "at a job interview",
      "at a street market",
      "at a sports stadium",
      "at a music concert",
      "in a taxi",
      "in a dentist's waiting room",
      "at a karaoke bar",
      "at a fancy restaurant",
      "inside a bakery",
      "at a theme park",
      "on a first date",
      "at a convenience store late at night",
      "at a bus stop in the rain",
      "in a pharmacy",
      "at a food court",
      "at a car wash",
      "in a crowded car park",
    ],
  },

  // ── Sophie's Choice ────────────────────────────────────────────────────────
  sophies: [
    {
      situation: 'Your best friend has been cheating on their partner for six months. Their partner — who is also your friend — just told you they are planning to propose next week.',
      a: 'Stay silent. Your loyalty belongs to your best friend, and it is not your relationship.',
      b: 'Tell the partner the truth before the proposal happens. They deserve to know.',
    },
    {
      situation: 'Your father has just been diagnosed with a serious illness and needs daily care. The promotion you have worked eight years for was just announced — and it requires you to move abroad immediately.',
      a: 'Accept the promotion. Your father has other family who can help.',
      b: 'Turn it down and go home to care for your father. The career can wait.',
    },
    {
      situation: 'You discover your company has been knowingly selling a product that is dangerous to children. Your boss tells you that if you speak to anyone about it, you will be fired and blacklisted from the industry.',
      a: 'Stay quiet. You have a family to support and no other job lined up.',
      b: 'Report it to the authorities, even if it means losing everything you have built.',
    },
    {
      situation: 'You have been with your partner for five years and love them deeply. You just found a message on their phone showing they kissed someone else at a work event last month. They have been acting completely normal ever since.',
      a: 'Confront them directly. You need the truth, even if it destroys the relationship.',
      b: 'Say nothing. One mistake should not erase five years of love.',
    },
    {
      situation: 'Your younger sibling confesses that they caused a hit-and-run accident years ago that seriously injured someone. The victim spent a year in hospital and still walks with a limp. Your sibling has completely changed their life since then.',
      a: 'Encourage them to go to the police and confess. The victim deserves justice.',
      b: 'Keep their secret. What good does it do now to destroy your sibling\'s life?',
    },
    {
      situation: 'Your closest friend has been in a relationship that has slowly become controlling and isolating. They refuse to see it as a problem. Their partner has never been violent — yet — but you are genuinely afraid of what may come.',
      a: 'Contact their family and explain your fears, even if it costs you the friendship.',
      b: 'Respect their wishes and stay available without pushing. It is their life.',
    },
    {
      situation: 'You are the best man at a wedding. The night before the ceremony, the groom privately tells you he is not sure he still loves the bride — but everything is paid for, and both families have flown in from across the world.',
      a: 'Tell him to call it off. A marriage built on doubt will only cause more pain.',
      b: 'Tell him cold feet are normal and push him to go through with it.',
    },
    {
      situation: 'Your elderly parent has just been diagnosed with terminal cancer and has about six months to live. They have no idea and are happily making plans for the future. The doctor asks you to decide whether they should be told.',
      a: 'Tell them the truth. They deserve to know and to say their goodbyes properly.',
      b: 'Let them stay happy and unaware for whatever time they have left.',
    },
    {
      situation: 'Your closest colleague confides that they have been secretly using drugs and it is affecting their work. They operate heavy machinery. Last week there was a near-accident that nobody else noticed. They beg you not to tell anyone.',
      a: 'Keep their secret and try to support them privately. Reporting will destroy their life.',
      b: 'Report it to management. Everyone\'s safety matters more than one person\'s secret.',
    },
    {
      situation: 'Your partner of three years says they will end the relationship if you take a once-in-a-lifetime opportunity — a year abroad that you have been dreaming about since childhood.',
      a: 'Give up the trip. This relationship is more important than any dream.',
      b: 'Go anyway. If the relationship cannot survive one year apart, it was never strong enough.',
    },
    {
      situation: 'You are on a jury. The evidence clearly proves the defendant is guilty. But you learn they committed the crime to feed their starving children after every other option had failed. A guilty verdict means a long prison sentence.',
      a: 'Vote guilty. The law must be applied equally to everyone, no matter the circumstances.',
      b: 'Vote not guilty. No law should imprison a parent for feeding their children.',
    },
    {
      situation: 'A colleague you barely know has been falsely accused of something serious at work. You know the truth — but speaking up means admitting you were somewhere you were not supposed to be that day.',
      a: 'Come forward with the truth, even if it exposes where you really were.',
      b: 'Stay silent. You do not know this person well enough to risk your own reputation.',
    },
    {
      situation: 'You find your teenager\'s private diary left open on the table. You have been deeply worried about them for weeks — they have been withdrawn, sad, and distant.',
      a: 'Read it. You are their parent and their safety is more important than their privacy.',
      b: 'Put it back unopened. Trust is the foundation of your relationship with your child.',
    },
    {
      situation: 'Your best friend has spent three years writing a novel and asks for your honest opinion before sending it to publishers. In your view, the book is genuinely terrible and will certainly be rejected everywhere. They are clearly very proud of it.',
      a: 'Tell them the full truth now. Rejection letters from strangers will be far more painful.',
      b: 'Tell them it is wonderful and encourage them to try. Dreams are worth protecting.',
    },
    {
      situation: 'You are walking alone late at night and see a man aggressively threatening a woman on an empty street. You have no phone signal and no weapon.',
      a: 'Step in immediately. You cannot walk past and do nothing.',
      b: 'Keep moving as fast as you can to find help. Getting yourself hurt helps nobody.',
    },
    {
      situation: 'Your parent asks directly whether you like their new partner. You believe the new partner is manipulative and possibly dangerous. Your parent seems genuinely happy for the first time in years.',
      a: 'Tell them the full truth, even if it creates distance between you.',
      b: 'Say you are happy for them. You might be wrong, and they deserve to feel joy.',
    },
    {
      situation: 'You discover on the morning of your wedding that your future spouse once committed a serious crime for which they were never caught. They were very young. They deeply regret it. The victim is someone you know.',
      a: 'Go ahead with the wedding. People can change, and you love who they are today.',
      b: 'Call it off. You cannot build a marriage on a secret of this size.',
    },
    {
      situation: 'Your brother calls from abroad in tears. He has done something illegal — nothing violent, but serious — and asks you to lie to the police if they contact you. He says the truth will send him to prison.',
      a: 'Lie for him. He is your brother and you will not be the one who sends him to prison.',
      b: 'Tell the truth. You will not commit a crime for anyone, even family.',
    },
    {
      situation: 'Your friend has been trying to have a baby through IVF for three years, with no success. They are about to spend their entire life savings on one final attempt. You genuinely believe it will not work.',
      a: 'Tell them exactly what you think, even if it destroys their last hope.',
      b: 'Say nothing. This is their decision and their hope to hold onto.',
    },
    {
      situation: 'Your ageing parent has started showing signs of memory loss and got lost on a familiar road last week. They become furious whenever driving is mentioned. Nothing has been officially diagnosed and their licence is still valid.',
      a: 'Report your concerns to their doctor and ask that the licence be reviewed.',
      b: 'Say nothing. Taking away their independence will break them. They deserve dignity.',
    },
    {
      situation: 'You are a journalist and have just found proof of a story that will make your career — but publishing it will destroy the reputation of an innocent person who happens to be connected to the real story.',
      a: 'Publish it. The public has a right to know and this is your job.',
      b: 'Bury the story. Some careers are not worth what they cost other people.',
    },
    {
      situation: 'You and your partner have been trying to have a child for years. You discover that the reason you cannot conceive is your partner\'s health. They do not know yet. Telling them will change everything.',
      a: 'Tell them immediately. They have an absolute right to know the truth about their own body.',
      b: 'Keep the information to yourself for now. You need time to figure out how to handle it.',
    },
    {
      situation: 'The mentor who gave you your first job — and changed your life — asks you to be a reference for a senior role. You have heard from a reliable source that they behaved very badly toward a former colleague. You were not there and cannot be certain.',
      a: 'Refuse to be a reference and explain your reason honestly.',
      b: 'Give the glowing reference. You owe this person everything, and you are not certain of the story.',
    },
    {
      situation: 'Your closest friend is going for the same promotion as you. You discover by accident that they lied on their application in a way that will almost certainly get them the position over you. Only you know.',
      a: 'Report the lie to HR. The position should go to whoever truly deserves it.',
      b: 'Stay silent. You will not betray a close friendship for your own career gain.',
    },
    {
      situation: 'You are in a job interview your family desperately needs you to get. The interviewer makes a discriminatory comment about a group you belong to — but cannot tell by looking at you. Speaking up will almost certainly end the interview.',
      a: 'Speak up immediately. You will not sit through discrimination for any salary.',
      b: 'Stay silent, get the job, and fight bigger battles from a position of strength.',
    },
    {
      situation: 'Your teenage child comes home shaken and admits they watched a classmate get seriously bullied and did nothing. The victim was badly hurt. The school is now investigating and asking all students what they saw.',
      a: 'Tell your child to go to the school and tell the full truth immediately.',
      b: 'Tell your child to say nothing. Protecting your own child comes before everything else.',
    },
    {
      situation: 'You are deeply in debt and about to lose your home. A stranger drops a bag and disappears into a crowd. Inside you find $20,000 in cash — clearly not legally obtained — with no way to identify the owner.',
      a: 'Keep it. You need it more than whoever lost it, and they were clearly no saint.',
      b: 'Hand it in to the police. Money like this never comes without consequences.',
    },
    {
      situation: 'You have lived in your adopted country for twenty years and built your entire life here. You discover that due to an old paperwork error, your citizenship is technically not valid. Nobody is looking for you.',
      a: 'Come forward immediately and try to correct it legally, whatever the cost.',
      b: 'Stay silent. You have earned your place here and nobody is coming for you.',
    },
    {
      situation: 'Your best friend is about to make a business investment that you are almost certain will fail and leave them bankrupt. They have not asked for your opinion and seem completely committed to the plan.',
      a: 'Tell them exactly what you think, even if they resent you for it.',
      b: 'Say nothing. They are an adult and it is not your place to interfere.',
    },
    {
      situation: 'You find proof that a very close family member has been lying to the entire family for years about something significant — money, identity, or the past. Revealing it will shatter everything. Staying silent means living with the lie.',
      a: 'Bring it into the open. The family deserves to know the truth, however painful.',
      b: 'Keep it to yourself. Some truths do more damage than the lies they replace.',
    },
    {
      situation: 'Your sibling has been in a serious accident and is brain-dead. The doctors say there is no chance of recovery. They could save five other lives if you agree to organ donation. Your parents are unreachable abroad and the doctors need an answer within the hour.',
      a: 'Give consent for the donation. Five lives matter more than keeping your sibling on a machine.',
      b: 'Wait for your parents, however long it takes. This decision is not yours alone to make.',
    },
    {
      situation: 'You work for a pharmaceutical company and discover that data in a major drug trial has been secretly altered to hide serious side effects. The drug is about to be approved and millions of people will use it. Speaking out will likely end your career and expose you to legal action.',
      a: 'Go public with the evidence. Millions of patients matter more than your career.',
      b: 'Resign quietly and say nothing. You cannot fight this system alone and you will lose.',
    },
    {
      situation: 'Your partner has been in a coma for nine months with no brain activity. The doctors say recovery is impossible. They are kept alive by machines. Your partner left no living will. Their parents want to keep the machines on indefinitely. You must make a final decision.',
      a: 'Make the decision to switch off the machines and let them go in peace.',
      b: 'Respect the parents\' wishes. You will not be the one who ends their child\'s life.',
    },
    {
      situation: 'You are on an overloaded lifeboat after a disaster. There is room for exactly one more person. In the water you can see two people — a young mother holding a baby, and your own elderly parent. The boat cannot hold both.',
      a: 'Pull in the young mother and her baby. There is no other choice you can live with.',
      b: 'Pull in your parent. You cannot abandon the person who raised you.',
    },
    {
      situation: 'Your best friend confides that they have been having thoughts of harming themselves. They are not in immediate danger but the situation is serious. They beg you not to tell anyone — and say that if you break their trust they will never speak to you again.',
      a: 'Break their trust and contact their family or a professional immediately. Their life matters more.',
      b: 'Respect their wishes, stay as close as possible, and support them yourself.',
    },
    {
      situation: 'You discover that the factory your entire town depends on for employment is secretly dumping toxic waste into the local river. Children downstream are getting sick. Reporting it will almost certainly shut the factory down and end the livelihoods of nearly everyone you know.',
      a: 'Report it to the authorities. The health of children comes before anyone\'s job.',
      b: 'Go to the factory owner privately first and demand they stop before you take any further action.',
    },
    {
      situation: 'Your parent has just died and you discover they secretly had a second family in another city for over twenty years. The other family does not know your parent has passed away. Their children are your half-siblings. They have a right to grieve — but the truth will shatter everything.',
      a: 'Contact the other family. They deserve to know the truth and to say goodbye.',
      b: 'Let them live without ever knowing. What they do not know cannot hurt them now.',
    },
    {
      situation: 'You are reviewing applications for a life-changing scholarship. The top application is clearly the best — but several paragraphs are copied from an obscure old source that the rest of the committee would never find. The second-place applicant is also talented and genuinely deserving.',
      a: 'Disqualify the top application. Plagiarism is plagiarism, regardless of the circumstances.',
      b: 'Award it anyway. The copied lines were minor and the application is still far and away the best.',
    },
    {
      situation: 'You find out you carry a genetic condition that your future children have a 50% chance of inheriting. It is serious but manageable. Your partner desperately wants children and has never asked about your family medical history. You have not told them.',
      a: 'Tell them immediately, even if it changes your entire future together.',
      b: 'Say nothing for now. Many people live full lives with this condition and it is your private health information.',
    },
    {
      situation: 'Your teenage child has been accepted into a prestigious sports academy that could lead to a professional career. But the training means leaving school, losing normal friendships, and enormous pressure from age 14. Your child is certain they want to go. You are not.',
      a: 'Support their dream fully. It is their life and you will back them completely.',
      b: 'Make them wait until 18 to choose. They are too young to give up a normal childhood.',
    },
    {
      situation: 'During a private conversation, your phone accidentally recorded your manager making comments that prove years of discrimination against a colleague who is about to be unfairly dismissed. You had no right to record the conversation. Using the recording could save your colleague\'s career.',
      a: 'Share the recording with HR. How you obtained it does not change what it proves.',
      b: 'Delete it. You had no right to that recording and using it will only turn everything against you.',
    },
    {
      situation: 'A stranger sits next to you on a long flight and, believing they will never see you again, confesses to something terrible they did years ago — something that caused great harm to a person you happen to know personally. The stranger does not know this connection.',
      a: 'Tell them exactly who you are and what their actions did to someone you love.',
      b: 'Say nothing. They will carry the weight of their own conscience without your help.',
    },
    {
      situation: 'Your child has been accepted into their dream university on a financial-need scholarship. You have just received an inheritance that technically disqualifies them — but nobody asked and you did not volunteer the information. The scholarship covers everything.',
      a: 'Contact the university and declare the inheritance. Your child must earn their place honestly.',
      b: 'Say nothing. The scholarship system is deeply imperfect and your child genuinely deserves this.',
    },
    {
      situation: 'A close friend who is a teacher has been having an inappropriate relationship with a 17-year-old student. The student appears willing. Your friend is about to get married and their partner is pregnant. You are the only one who knows.',
      a: 'Report it to the school and authorities without delay.',
      b: 'Confront your friend directly and give them the chance to end it before you act.',
    },
    {
      situation: 'You discover your 16-year-old child has been secretly sending money every month to a person they met online — someone you have never heard of, in another country. Your child refuses to discuss it and says you would not understand.',
      a: 'Cut off their access to money and report it to the police as a potential scam or worse.',
      b: 'Give them the chance to explain first. Cutting them off without listening will destroy their trust in you.',
    },
    {
      situation: 'You are a doctor in a crisis with one treatment left and two patients who critically need it tonight. One is a 78-year-old grandmother surrounded by family. The other is a 10-year-old child. Both will die without treatment. The decision falls entirely to you.',
      a: 'Give the treatment to the child. They have their whole life ahead of them.',
      b: 'Give it to the grandmother. She arrived first and every human life deserves equal value.',
    },
    {
      situation: 'You are on a hiking trip and your friend twists their ankle badly in a remote area. It will be dark in two hours. You can carry them slowly toward the road, or leave them sheltered and run for help alone — but the weather is changing fast and you are not sure which choice is safer.',
      a: 'Leave them in a safe spot and run for help. You can move faster alone and get back sooner.',
      b: 'Stay together no matter what. You will not leave your friend alone in the dark.',
    },
    {
      situation: 'Your friend has spent years convinced that their ex ended the relationship unfairly and treated them badly. You know the real story — your friend was controlling and unkind in ways they have never acknowledged. They are now in a new relationship and the same patterns are emerging.',
      a: 'Tell them the truth about why their last relationship really ended, even if it destroys your friendship.',
      b: 'Say nothing. People have to discover their own patterns in their own time.',
    },
    {
      situation: 'You discover that your own parent — who you have always deeply respected — reported a neighbour to the authorities decades ago for political reasons, knowing the accusation was false. The neighbour lost everything. That neighbour\'s family still lives nearby.',
      a: 'Confront your parent and push them to make some form of amends, however late.',
      b: 'Let it stay in the past. Your parent is old. Nothing you do now will undo what happened.',
    },
    {
      situation: 'You find out your closest friend has been secretly in contact with your ex-partner — the one who hurt you deeply — for over a year. They say they were trying to protect you by keeping it quiet. You are not sure whether to believe them.',
      a: 'End the friendship. The secret alone is a betrayal, regardless of the reason.',
      b: 'Hear them out fully before deciding anything. People keep secrets for complicated reasons.',
    },
  ],

  // ── Persuade Together ──────────────────────────────────────────────────────
  persuade: [
    { cat:'🏫 School', judge:'Teacher', emoji:'🧑‍🏫',
      team:'Students who want more time for the exam',
      situation:'Your whole class thinks the exam is too soon. Convince the teacher to move it to next week.' },
    { cat:'🏫 School', judge:'Principal', emoji:'🏫',
      team:'Student council who wants to change the uniform rule',
      situation:'The whole student council thinks the school uniform is old and boring. Convince the principal to let students wear casual clothes every Friday.' },
    { cat:'🏫 School', judge:'Teacher', emoji:'🧑‍🏫',
      team:'Students who think the homework is not fair',
      situation:'Your whole class thinks this week\'s homework is too long and not fair. Convince the teacher to cancel it completely.' },
    { cat:'🏫 School', judge:'Professor', emoji:'👨‍🏫',
      team:'Students who all missed the deadline',
      situation:'Many students missed the project deadline because the instructions were not clear. Convince the professor to give everyone one more week.' },
    { cat:'🏫 School', judge:'Teacher', emoji:'🧑‍🏫',
      team:'Students who want to do something creative',
      situation:'The whole class wants to replace the final exam with a fun group project or show. Convince the teacher it is a great way to learn.' },
    { cat:'🏫 School', judge:'Principal', emoji:'🏫',
      team:'Students who want a game room at school',
      situation:'A group of students wants to turn an empty room into a place to play games and relax. Convince the principal it will help students do better in class.' },
    { cat:'🏫 School', judge:'Teacher', emoji:'🌳',
      team:'Students who want class outside today',
      situation:'It is a beautiful sunny day and everyone wants to have class outside in the garden. Convince the teacher to leave the classroom just this one time.' },
    { cat:'🏫 School', judge:'Cafeteria Manager', emoji:'🥗',
      team:'Students who want better school food',
      situation:'The whole student group thinks the school food is boring and not healthy. Convince the cafeteria manager to change the menu and make it better.' },
    { cat:'🏫 School', judge:'Principal', emoji:'⏰',
      team:'Students who want a longer lunch break',
      situation:'Everyone feels the lunch break is too short. Convince the principal to make it 30 minutes longer every day.' },
    { cat:'🏫 School', judge:'Principal', emoji:'🚌',
      team:'Students who want a school trip',
      situation:'The whole class wants to go on a school trip instead of normal classes for a week. Convince the principal it is a great way to learn outside the classroom.' },
    { cat:'💼 Workplace', judge:'Manager', emoji:'💼',
      team:'Employees who want to work from home',
      situation:'Your whole team wants to work from home every Friday. Convince the manager that the work will still get done and everyone will be happier.' },
    { cat:'💼 Workplace', judge:'CEO', emoji:'🏢',
      team:'Team members who want more money for projects',
      situation:'Your team does not have enough money to do their work well. Convince the CEO to give the team twice as much money for the next three months.' },
    { cat:'💼 Workplace', judge:'HR Manager', emoji:'📋',
      team:'Employees who want free lunch and a rest room',
      situation:'The whole team wants free lunch every Friday and a quiet room to rest during the day. Convince the HR manager it will make the team work much better.' },
    { cat:'💼 Workplace', judge:'Boss', emoji:'👔',
      team:'Employees who hate the early morning meeting',
      situation:'Nobody likes the 8am Monday meeting. Convince the boss to move it to Wednesday at 11am instead.' },
    { cat:'💼 Workplace', judge:'Boss', emoji:'🐾',
      team:'Employees who want a "bring your pet" day',
      situation:'The whole team wants to bring their pets to the office once a month. Convince the boss it will make everyone less stressed and more friendly with each other.' },
    { cat:'💼 Workplace', judge:'CEO', emoji:'📅',
      team:'Employees who want a 4-day work week',
      situation:'Everyone in the company wants to work only 4 days a week but get the same pay. Convince the CEO the company will do better and people will work harder.' },
    { cat:'💼 Workplace', judge:'HR Manager', emoji:'🧘',
      team:'Employees who want extra rest days',
      situation:'Your team wants the company to give everyone two extra paid "rest days" per year. Convince the HR manager it is good for everyone.' },
    { cat:'💼 Workplace', judge:'CEO', emoji:'🎮',
      team:'Employees who want a fun room in the office',
      situation:'A group of workers wants to build a game room and a relaxing area in the office. Convince the CEO it will help the team think more clearly and work better.' },
    { cat:'💼 Workplace', judge:'HR Manager', emoji:'👨‍👩‍👦',
      team:'Employees who want family visit days',
      situation:'The team wants to invite their families to the office on the last Friday of every month. Convince the HR manager it will make workers feel happier and more connected.' },
    { cat:'💼 Workplace', judge:'Manager', emoji:'👕',
      team:'Employees who want a casual dress code',
      situation:'Everyone is tired of wearing formal clothes to the office every day. Convince the manager to change the dress code to casual clothes from Monday to Friday.' },
    { cat:'🏘️ Community', judge:'Mayor', emoji:'🌱',
      team:'Residents who want a community garden',
      situation:'Your group wants to turn the empty land on Main Street into a garden and playground for everyone. Convince the mayor to say yes and help pay for it.' },
    { cat:'🏘️ Community', judge:'Landlord', emoji:'🏠',
      team:'Tenants who want better living conditions',
      situation:'All the people in the building want the landlord to fix the broken lift, add free WiFi, and allow pets. Convince the landlord to agree to all three.' },
    { cat:'🏘️ Community', judge:'School Principal', emoji:'📵',
      team:'Parents who want a no-phone rule at school',
      situation:'A group of parents wants the school to not allow phones during school hours. Convince the principal to start this rule next month.' },
    { cat:'🏘️ Community', judge:'City Council', emoji:'🛹',
      team:'Young people who want a skate park',
      situation:'A group of young people wants the city to build a free skate park and sports area. Convince the city council it will keep young people active and happy.' },
    { cat:'🏘️ Community', judge:'Library Director', emoji:'📚',
      team:'Residents who want longer library hours',
      situation:'People in the area want the library to stay open until midnight. Convince the director this will help students and people who like to read at night.' },
    { cat:'🏘️ Community', judge:'Mayor', emoji:'🚲',
      team:'Residents who want car-free Sundays',
      situation:'Your group wants to close the main street to cars every Sunday so people can walk and ride bikes freely. Convince the mayor to try this idea.' },
    { cat:'🏘️ Community', judge:'City Council', emoji:'🎉',
      team:'Residents who want a street party',
      situation:'Your group wants to hold a big free street party with food, music, and fun activities. Convince the city council to say yes and give a small amount of money.' },
    { cat:'🏘️ Community', judge:'City Planner', emoji:'🌳',
      team:'Residents who want a park instead of a car park',
      situation:'The city wants to build a big car park in your area. Convince the city planner to turn that space into a nice green park with trees and seats instead.' },
    { cat:'👨‍👩‍👦 Family', judge:'Mom & Dad', emoji:'🎢',
      team:'All the kids who want to go to a theme park',
      situation:'All the children want to go to a theme park for the family holiday instead of visiting family. Convince your parents it will be much more fun and a memory they will never forget.' },
    { cat:'👨‍👩‍👦 Family', judge:'Grandma', emoji:'👵',
      team:'Grandchildren who want grandma to get a smartphone',
      situation:'The whole family wants grandma to get a smartphone so everyone can video call her. Convince her it is easy to use and will help keep the family close.' },
    { cat:'👨‍👩‍👦 Family', judge:'Mom & Dad', emoji:'🎮',
      team:'Siblings who want a new games console',
      situation:'All the brothers and sisters want a new games console. Convince your parents it helps with teamwork and everyone will set a time limit.' },
    { cat:'👨‍👩‍👦 Family', judge:'Dad', emoji:'🐶',
      team:'Kids who really want a family dog',
      situation:'All the children want a dog. Convince dad that everyone will help look after it and the whole family will be happier.' },
    { cat:'👨‍👩‍👦 Family', judge:'Mom & Dad', emoji:'🎆',
      team:'Kids who want to stay up for New Year\'s Eve',
      situation:'All the children want to stay up past midnight for New Year\'s Eve. Convince the parents this only happens once a year and everyone will be fine the next day.' },
    { cat:'👨‍👩‍👦 Family', judge:'Mom & Dad', emoji:'🚗',
      team:'Kids who want a surprise road trip',
      situation:'The children want to skip school on Friday for a 3-day road trip with the family. Convince your parents it will be the best family memory ever.' },
    { cat:'👨‍👩‍👦 Family', judge:'Grandparents', emoji:'🏕️',
      team:'Family members who want to go camping',
      situation:'Everyone wants to go camping in the forest instead of the usual big formal dinner at a restaurant. Convince the grandparents that camping will be much more fun.' },
    { cat:'👨‍👩‍👦 Family', judge:'Mom & Dad', emoji:'📺',
      team:'Kids who want a bigger TV',
      situation:'Everyone at home wants to change the old small TV for a big new smart TV. Convince your parents it is a good thing to buy for the whole family.' },
    { cat:'👨‍👩‍👦 Family', judge:'Mom & Dad', emoji:'📱',
      team:'Siblings who all want their own phone',
      situation:'All the brothers and sisters feel they are the only kids without a phone. Convince your parents that phones are useful, safe, and easy to manage with some rules.' },
    { cat:'👨‍👩‍👦 Family', judge:'Mom & Dad', emoji:'🎨',
      team:'Kids who want to redecorate their rooms',
      situation:'All the children want to give their rooms a new look with different colours and new things on the walls. Convince your parents to let everyone give their room a fresh new style.' },
    { cat:'🧑‍🤝‍🧑 Friends', judge:'One friend who doesn\'t want to go', emoji:'🤷',
      team:'Friends who need everyone on the trip',
      situation:'The whole group has planned a trip but one person keeps saying no. Convince them to come — you really need everyone there to make it the best trip ever.' },
    { cat:'🧑‍🤝‍🧑 Friends', judge:'The friend who planned everything', emoji:'🗓️',
      team:'Group members who want to go to the beach instead',
      situation:'The group first planned to go to the mountains, but now almost everyone wants to go to the beach. Convince the person who planned it to change the place.' },
    { cat:'🧑‍🤝‍🧑 Friends', judge:'One friend who wants to go home early', emoji:'🌙',
      team:'Friends who want to stay at the party',
      situation:'It is only 9pm and one friend already wants everyone to go home. Convince them to stay at least two more hours — the fun is just starting.' },
    { cat:'🧑‍🤝‍🧑 Friends', judge:'The one friend who always says no to karaoke', emoji:'🎤',
      team:'Friends who love karaoke',
      situation:'Everyone wants to go to karaoke but one person says no every single time. Convince them that this time will be different — and they will really enjoy it.' },
    { cat:'🧑‍🤝‍🧑 Friends', judge:'The laziest friend in the group', emoji:'💪',
      team:'Friends who want to do a fitness challenge',
      situation:'The whole group wants to do a 30-day fitness challenge together. Convince the laziest friend that it will be fun and not as hard as they think.' },
    { cat:'🧑‍🤝‍🧑 Friends', judge:'The friend who is not sure about the food', emoji:'🍽️',
      team:'The group who wants to try a very different restaurant',
      situation:'Your group wants to eat at a restaurant that serves very unusual food. Convince the most careful eater in the group to give it a try — they might love it.' },
    { cat:'🧑‍🤝‍🧑 Friends', judge:'The friend who organised the house party', emoji:'🏕️',
      team:'Friends who want to go camping instead',
      situation:'Your friend worked hard to plan a house party, but now everyone wants to go camping instead. Convince the organiser to change the plan.' },
    { cat:'🧑‍🤝‍🧑 Friends', judge:'The shyest person in the group', emoji:'🎸',
      team:'Friends who want to start a band',
      situation:'The group wants to start a band and play at the school show. Convince the shyest person to be the lead singer — the band really needs their voice.' },
    { cat:'🧑‍🤝‍🧑 Friends', judge:'The friend who thinks it\'s too much work', emoji:'🎂',
      team:'Friends who want to plan a surprise party',
      situation:'The group wants to plan a big surprise party for a close friend. Convince the one who thinks it is too much work that it will be easy, fun, and totally worth it.' },
    { cat:'🧑‍🤝‍🧑 Friends', judge:'The friend who never wants to go out', emoji:'🌞',
      team:'Friends who want a picnic in the park',
      situation:'The group wants to go to the park for a picnic on a sunny day, but one friend always wants to stay home. Convince them that fresh air and good food with friends is the best plan.' },
    { cat:'🧑‍🤝‍🧑 Friends', judge:'The most resistant friend', emoji:'🎨',
      team:'Friends who want to try a new hobby',
      situation:'The whole group wants to try pottery or painting together. Convince the most resistant friend that it will be a fun and relaxing way to spend time together.' },
    { cat:'🧑‍🤝‍🧑 Friends', judge:'The friend who hates running', emoji:'🏃',
      team:'Friends who want to do a charity run',
      situation:'The whole group wants to sign up for a charity run together. Convince the friend who hates running that it is for a good cause — and they do not need to run fast.' },
    { cat:'🏆 Sports', judge:'Coach', emoji:'🏆',
      team:'Players who want fewer training days',
      situation:'The whole team thinks training six days a week is too much and people are getting hurt. Convince the coach to cut it down to four days and keep the team strong.' },
    { cat:'🏆 Sports', judge:'Referee', emoji:'🟨',
      team:'Players who think the call was wrong',
      situation:'Your team thinks the referee made a bad call that could cost you the game. Convince the referee to change the decision before the final whistle.' },
    { cat:'🏆 Sports', judge:'Coach & Sponsor', emoji:'👕',
      team:'Players who want to design their own team shirt',
      situation:'The whole team is tired of the boring old team shirt. Convince the coach and the sponsor to let the players make their own new design for next season.' },
    { cat:'✈️ Travel', judge:'Restaurant Manager', emoji:'🍽️',
      team:'A group who had a very bad dinner experience',
      situation:'Your whole group got cold food, waited over an hour, and had rude service. Convince the restaurant manager to give everyone a full refund.' },
    { cat:'✈️ Travel', judge:'Hotel Manager', emoji:'🏨',
      team:'Guests who had problems at check-in',
      situation:'Your group booked three rooms but they were not ready when you arrived — two hours late with no sorry. Convince the hotel manager to give everyone a better room for free.' },
    { cat:'✈️ Travel', judge:'Airline Staff', emoji:'✈️',
      team:'Passengers who missed their next flight',
      situation:'Your whole group missed a flight because the airline\'s first flight was late. Convince the airline staff to put everyone on a new flight for free and give a food voucher.' },
    { cat:'✈️ Travel', judge:'Museum Staff', emoji:'🏛️',
      team:'A group who wants to see a special show',
      situation:'The special show at the museum is fully booked for two months. Convince the museum staff to let your group in for a private visit after the museum closes.' },
    { cat:'✈️ Travel', judge:'Event Manager', emoji:'🎪',
      team:'A group of fans outside a sold-out event',
      situation:'The event is sold out and your group is standing outside. Convince the event manager that letting your group in will only make the atmosphere even better.' },
    { cat:'✈️ Travel', judge:'Theme Park Manager', emoji:'🎢',
      team:'A large group who wants a discount',
      situation:'Your whole group wants to visit the theme park but the tickets are very expensive. Convince the manager to give the whole group a big discount for coming together.' },
    { cat:'✈️ Travel', judge:'Hotel Manager', emoji:'🏊',
      team:'Guests who want the pool to stay open late',
      situation:'Your group wants to swim in the hotel pool at night, but it closes at 8pm. Convince the hotel manager to keep the pool open until 11pm just for your group tonight.' },
    { cat:'✈️ Travel', judge:'Tour Guide', emoji:'🗺️',
      team:'Tourists who want one more stop on the tour',
      situation:'Your group loves the tour but wants to add one more interesting place before it ends. Convince the tour guide to take you there — even if it is a little extra time.' },
    { cat:'😄 Fun & Silly', judge:'Mom & Dad', emoji:'🎮',
      team:'Kids who want to skip school for a gaming day',
      situation:'Everyone wants to skip school on Friday to stay home and play video games all day together. Convince your parents that one day off will not hurt and it will be an amazing memory.' },
    { cat:'😄 Fun & Silly', judge:'Teacher', emoji:'💨',
      team:'Students with a very creative excuse',
      situation:'Nobody in the class did their homework. Convince the teacher that a strong wind came through the window and blew everyone\'s homework away before they could hand it in.' },
    { cat:'😄 Fun & Silly', judge:'Boss', emoji:'😴',
      team:'Employees who want to wear pyjamas on Fridays',
      situation:'The whole team wants to wear their pyjamas to the office every Friday. Convince the boss that everyone will be more relaxed and do better work in comfortable clothes.' },
    { cat:'😄 Fun & Silly', judge:'Grandparents', emoji:'🌶️',
      team:'Grandchildren who want a spicy food challenge',
      situation:'The whole family wants to do a very spicy food challenge together at dinner. Convince the grandparents to join in — it will be the funniest family moment ever.' },
    { cat:'😄 Fun & Silly', judge:'Principal', emoji:'🐾',
      team:'Students who want a "bring your pet" day',
      situation:'The whole school wants one special day where students can bring their pets to school. Convince the principal it will make everyone very happy and be a day no one forgets.' },
    { cat:'😄 Fun & Silly', judge:'Librarian', emoji:'🍪',
      team:'Students who want a snack break in the library',
      situation:'Everyone studying in the library is hungry and tired. Convince the librarian to allow a short snack break in the middle of study time — just 10 quiet minutes.' },
    { cat:'😄 Fun & Silly', judge:'Mom & Dad', emoji:'🌙',
      team:'Kids who want an all-night movie night',
      situation:'Everyone wants to stay up all night watching films together. Convince your parents to join in and make it a big, fun family night that nobody will ever forget.' },
    { cat:'😄 Fun & Silly', judge:'Coach', emoji:'💦',
      team:'Players who want a water fight instead of training',
      situation:'It is very hot and nobody wants to do normal training today. Convince the coach to let the whole team have a water fight instead — it is still a team activity!' },
    { cat:'😄 Fun & Silly', judge:'Neighbour', emoji:'🍖',
      team:'A group who wants to use the neighbour\'s garden',
      situation:'Your group wants to have a big BBQ party but needs more space. Convince your neighbour to let everyone use their garden for the afternoon.' },
    { cat:'😄 Fun & Silly', judge:'Restaurant Owner', emoji:'🎵',
      team:'A group with no money but lots of talent',
      situation:'Your group has eaten a great meal but has no money to pay. Convince the restaurant owner to let everyone pay with a song and a short dance instead of money.' },
    { cat:'😄 Fun & Silly', judge:'Teacher', emoji:'🛏️',
      team:'Students who want a pillow fight as a class activity',
      situation:'The class wants to have a big pillow fight as a "team activity". Convince the teacher this is a real way to build friendship and have a lot of fun together.' },
    { cat:'😄 Fun & Silly', judge:'Mom & Dad', emoji:'🍰',
      team:'Kids who want a snacks-only dinner',
      situation:'Nobody wants real food tonight. Convince your parents to let everyone eat only snacks and sweet things for dinner — just this one time as a special treat.' },
    { cat:'😄 Fun & Silly', judge:'Boss', emoji:'🎲',
      team:'Employees who want an afternoon off to play games',
      situation:'It has been a very hard week and the whole team is tired. Convince the boss to cancel all work for one afternoon so everyone can relax and play board games together.' },
    { cat:'😄 Fun & Silly', judge:'Principal', emoji:'🏫',
      team:'Students who want to teach the classes for one day',
      situation:'The whole class wants to be the teachers for one day and teach their own lessons. Convince the principal this is a fun and creative way to learn.' },
    { cat:'😄 Fun & Silly', judge:'Hotel Manager', emoji:'🏰',
      team:'Guests who want to build a fort in the lobby',
      situation:'Your group wants to use the hotel sofas and blankets to build a giant fort in the lobby for the evening. Convince the hotel manager it will be harmless and very fun for everyone.' },
    { cat:'😄 Fun & Silly', judge:'Park Manager', emoji:'🫧',
      team:'A group who wants a bubble contest in the park',
      situation:'Your group wants to have a big bubble-blowing contest in the park. Convince the manager to let you use a small area — and maybe even join in.' },
    { cat:'😄 Fun & Silly', judge:'Mom & Dad', emoji:'🐐',
      team:'Kids who want a pet goat',
      situation:'Everyone in the family wants to get a pet goat for the garden. Convince your parents that a goat is a great pet, easy to look after, and will make the garden much more fun.' },
    { cat:'😄 Fun & Silly', judge:'Teacher', emoji:'🏊',
      team:'Students who want class in the swimming pool',
      situation:'The whole class wants to move today\'s lesson to the school swimming pool. Convince the teacher it is still a proper class — just with more water.' },
    { cat:'😄 Fun & Silly', judge:'Mom & Dad', emoji:'🤡',
      team:'Kids who want a matching funny costume day',
      situation:'All the children want the whole family to put on matching funny costumes and spend the whole day out in town. Convince your parents it will be the most fun family day ever.' },
    { cat:'😄 Fun & Silly', judge:'Café Owner', emoji:'🎶',
      team:'A group who wants to stay after closing time',
      situation:'Your group is having such a great time at the café but it is closing time. Convince the owner to let everyone stay for a short singing competition before leaving.' },
    { cat:'😄 Fun & Silly', judge:'Teacher', emoji:'💃',
      team:'Students who want a dance break in class',
      situation:'The whole class is tired and wants to stop the lesson for a 5-minute group dance. Convince the teacher it will help everyone focus much better afterwards.' },
    { cat:'😄 Fun & Silly', judge:'Mom & Dad', emoji:'🍳',
      team:'Kids who want breakfast food for dinner',
      situation:'Nobody wants a normal dinner tonight. Convince your parents to let everyone eat pancakes, eggs, and toast for dinner instead — just for fun.' },
    { cat:'😄 Fun & Silly', judge:'Boss', emoji:'☕',
      team:'Employees who want to work from a café or park',
      situation:'The whole team wants to work outside — at a café or in the park — for just one day. Convince the boss it will make everyone more creative and happy.' },
    { cat:'😄 Fun & Silly', judge:'Grandma', emoji:'🎮',
      team:'Grandchildren who want grandma to try video games',
      situation:'The whole family wants grandma to try playing a simple video game for the first time. Convince her it is easy, very fun, and a great way to spend time together.' },
    { cat:'😄 Fun & Silly', judge:'Principal', emoji:'🎩',
      team:'Students who want a silly hat day',
      situation:'The whole school wants one day where everyone can wear their silliest or funniest hat to school. Convince the principal it will make everyone smile and bring the school together.' },
    { cat:'😄 Fun & Silly', judge:'Mom & Dad', emoji:'📱',
      team:'Kids who want to make a funny family video',
      situation:'All the children want the whole family to make a short funny video together and post it online. Convince your parents it will be a fun memory and totally harmless.' },
    { cat:'😄 Fun & Silly', judge:'Coach', emoji:'🎵',
      team:'Players who want music during training',
      situation:'The whole team wants to play their favourite music out loud during every training session. Convince the coach it will make everyone more excited and work harder.' },
    { cat:'😄 Fun & Silly', judge:'Teacher', emoji:'🗳️',
      team:'Students who want to choose the next topic',
      situation:'The whole class wants to vote and choose what topic they study next. Convince the teacher that letting students choose will make everyone much more interested in learning.' },
    { cat:'😄 Fun & Silly', judge:'Mom & Dad', emoji:'🧺',
      team:'Kids who want a picnic on the living room floor',
      situation:'Everyone wants to eat dinner on a big blanket on the living room floor like a picnic instead of at the table. Convince your parents it will be a fun and different evening.' },
    { cat:'😄 Fun & Silly', judge:'Boss', emoji:'🦸',
      team:'Employees who want a superhero costume day',
      situation:'The whole team wants to wear superhero costumes to the office for one day. Convince the boss it will be a great way to laugh together and make the day more fun.' },
    { cat:'😄 Fun & Silly', judge:'Librarian', emoji:'🌿',
      team:'Students who want to read outside today',
      situation:'The weather is beautiful and the whole group wants to take their books and read outside under the trees. Convince the librarian to let everyone go outside just for today.' },
    { cat:'😄 Fun & Silly', judge:'Grandparents', emoji:'🎢',
      team:'Grandchildren who want grandparents on a roller coaster',
      situation:'Your group wants your grandparents to try a roller coaster for the very first time. Convince them it is safe, quick, and they will love the feeling.' },
    { cat:'😄 Fun & Silly', judge:'Teacher', emoji:'🎬',
      team:'Students who want a movie day as a reward',
      situation:'The class has been working very hard all week. Convince the teacher to have a movie day instead of a normal lesson as a special reward for everyone.' },
    { cat:'😄 Fun & Silly', judge:'Mom & Dad', emoji:'👨‍🍳',
      team:'Kids who want to cook the whole family dinner',
      situation:'All the children want to plan and cook dinner for the whole family tonight — all by themselves. Convince your parents to stay out of the kitchen and let the kids take over.' },
    { cat:'😄 Fun & Silly', judge:'Gym Manager', emoji:'🍫',
      team:'Members who want a dessert bar in the gym',
      situation:'The whole group wants the gym to add a fun dance class and a small dessert bar after workouts. Convince the manager it will make people enjoy the gym much more.' },
    { cat:'😄 Fun & Silly', judge:'Neighbour', emoji:'🏅',
      team:'A group who wants a silly sports day in the street',
      situation:'Your group wants to set up a fun and silly sports day on the street — with egg-and-spoon races, sack races, and more. Convince your neighbour to close the street and join in.' },
    { cat:'😄 Fun & Silly', judge:'Principal', emoji:'🐻',
      team:'Students who want a funny school mascot',
      situation:'Students want to create a funny mascot costume that someone wears at school events. Convince the principal it will make the school more fun and everyone will love it.' },
    { cat:'😄 Fun & Silly', judge:'Mom & Dad', emoji:'🔄',
      team:'Kids who want a family role-swap day',
      situation:'All the children want the whole family to swap their daily jobs and roles for one day — kids act as parents, parents act as kids. Convince mom and dad to give it a try.' },
    { cat:'😄 Fun & Silly', judge:'Teacher', emoji:'😴',
      team:'Students who want a nap time in class',
      situation:'Everyone in class is very tired and wants a 15-minute nap break in the middle of the lesson. Convince the teacher that a short rest will help everyone learn better after.' },
  ],

  // ── You're In The Scene ────────────────────────────────────────────────────
  scene: [
    {
      emoji: '☕',
      title: 'Coffee Shop Chaos',
      situation: "One customer can't decide what to order. The line is getting longer. Everyone has an opinion.",
      a: { label: 'The Lost Customer', hint: "You want 'something good' but have no idea what. You keep asking B and C for help." },
      b: { label: 'The Sleepy Barista', hint: "You just need A to pick something. Anything. Please. You've been here since 6am." },
      c: { label: 'The Helpful Friend', hint: "You have lots of drink ideas for A — but you change your mind every 10 seconds." },
      d: { label: 'The Person Behind in Line', hint: "You've waited too long. You shout suggestions at A and argue with C's ideas." },
    },
    {
      emoji: '🎉',
      title: 'The Party Escape',
      situation: "One person is trying to leave the party. Their friend refuses to let them go.",
      a: { label: 'The One Who Wants to Leave', hint: "You don't know anyone here. The music is too loud. You just want to go home." },
      b: { label: 'The Excited Friend', hint: "You brought A here. If A leaves, you'll feel bad. You NEED A to have fun." },
      c: { label: 'The Friendly Stranger', hint: "You want to be friends with A. You keep talking to A without noticing A wants to escape." },
      d: { label: 'The Party Host', hint: "Every time A moves toward the door, you appear with food, games, or a new activity." },
    },
    {
      emoji: '💼',
      title: 'The Worst Interview',
      situation: "A job interview is happening — and things keep going wrong for everyone in the room.",
      a: { label: 'The Nervous Candidate', hint: "You really need this job. But every answer you give sounds worse than the last." },
      b: { label: 'The Distracted Interviewer', hint: "You're supposed to ask A questions, but your phone keeps buzzing with urgent texts." },
      c: { label: 'The Too-Happy HR Person', hint: "You think everything A says is AMAZING — even when it's clearly not." },
      d: { label: 'The Next Candidate', hint: "You're waiting outside but you keep walking in at the worst possible moments." },
    },
    {
      emoji: '✈️',
      title: 'Flight Delay Madness',
      situation: "The flight is delayed. Nobody knows why. The gate keeps changing. People are getting upset.",
      a: { label: 'The Stressed Traveler', hint: "You MUST be somewhere important. You keep asking B what is going on." },
      b: { label: 'The Airport Staff', hint: "You want to help A but you don't actually have any real answers right now." },
      c: { label: 'The Confident Wrong Person', hint: "You've been here before. You give A a lot of advice. Most of it is wrong." },
      d: { label: 'The Phone Talker', hint: "You're on a call, saying everything that happens OUT LOUD. Very loudly." },
    },
    {
      emoji: '🏋️',
      title: 'Gym Day One',
      situation: "It's your first day at the gym. You have no idea what to do. Three people all want to help — sort of.",
      a: { label: 'The Lost Beginner', hint: "You don't know how anything works. You just press buttons and hope for the best." },
      b: { label: 'The Gym Expert', hint: "You've given A five tips already. A didn't ask for any of them. You have more." },
      c: { label: 'The Competitive One', hint: "You want to race A, out-lift A, or beat A at everything. Everything is a contest." },
      d: { label: 'The Gym Staff', hint: "Your job is to help A. But your phone is much more interesting right now." },
    },
    {
      emoji: '🍽️',
      title: 'Dinner Disaster',
      situation: "The host cooked for three hours. The food is… not great. Everyone is trying to react nicely.",
      a: { label: 'The Proud Host', hint: "You worked very hard. You are watching everyone's face very, very carefully." },
      b: { label: 'The Honest Guest', hint: "You can't fake a reaction. Your face always shows exactly what you think." },
      c: { label: 'The Worried Friend', hint: "You can see B's face. You jump in with nice words before A notices B's reaction." },
      d: { label: 'The Over-Actor', hint: "You're pretending to LOVE the food. Way too much. Nobody believes you." },
    },
    {
      emoji: '📚',
      title: 'Library War',
      situation: "Someone is very noisy in a quiet library. The librarian is coming. Someone is trying to help — but making things worse.",
      a: { label: 'The Stressed Student', hint: "You have an exam tomorrow. This noise is killing you. You need silence NOW." },
      b: { label: 'The Noisy One', hint: "You don't think you're loud. Every time C warns you, you get a little louder." },
      c: { label: 'The Librarian', hint: "You've told B to be quiet three times. You're very calm. This is your final warning." },
      d: { label: 'The Helper', hint: "You want to help A and C, but every idea you have makes B more upset." },
    },
    {
      emoji: '🏥',
      title: 'The Waiting Room',
      situation: "People are waiting at the doctor's office. Nobody knows how long the wait will be.",
      a: { label: 'The Very Impatient One', hint: "You've asked D 'how long?' several times already. You're going to ask again. Right now." },
      b: { label: 'The Very Calm One', hint: "You don't mind waiting at all. You have snacks and a book. You offer A a snack." },
      c: { label: 'The Oversharer', hint: "You want to tell everyone why you're here. In detail. You want everyone's opinion." },
      d: { label: 'The Receptionist', hint: "You don't know when anyone will be called. B won't stop asking. C won't stop talking." },
    },
    {
      emoji: '🛒',
      title: 'One Item Left',
      situation: "There is ONE item left on the shelf. Two people grabbed it at the same time. Neither will let go.",
      a: { label: 'The First Grabber', hint: "You saw it first. Your hand touched it first. It's yours. End of story." },
      b: { label: 'The Other Grabber', hint: "You ALSO saw it first. Your hand ALSO touched it first. It's yours. End of story." },
      c: { label: 'The Random Helper', hint: "You saw the whole thing. You're trying to find a fair answer. Your ideas are not great." },
      d: { label: 'The Store Worker', hint: "You have to solve this. You really don't want to. You just want to go back to work." },
    },
    {
      emoji: '🚗',
      title: 'Lost on a Road Trip',
      situation: "You're in a car together. You're lost. The GPS is broken. Everyone has a different plan.",
      a: { label: 'The Stubborn Driver', hint: "You won't stop. You won't ask for help. You have a 'feeling' about the right way." },
      b: { label: 'The Bad Navigator', hint: "You're reading the map. You've given three wrong turns. You won't say sorry." },
      c: { label: 'The Hungry Passenger', hint: "You stopped caring about directions. You just need food. Any food. Please." },
      d: { label: 'The Happy Passenger', hint: "Everything is great! This is an adventure! You don't understand why everyone is upset." },
    },
    {
      emoji: '🎬',
      title: 'Movie Night Fight',
      situation: "A group of friends want to watch a movie together. Nobody can agree on what to pick.",
      a: { label: 'The Horror Fan', hint: "Every good movie is scary. If it's not scary, why are you watching it?" },
      b: { label: 'The Romance Fan', hint: "You want something happy. No blood. No monsters. Something that makes you cry in a good way." },
      c: { label: 'The Smart Movie Person', hint: "You want a documentary or a foreign film. Something with meaning." },
      d: { label: 'The "Fine With Anything" Person', hint: "You say you're okay with anything. But you say 'no' to every single suggestion." },
    },
    {
      emoji: '🏨',
      title: 'Hotel Mix-Up',
      situation: "You arrive at the hotel. Your room isn't ready. Something went wrong with the booking.",
      a: { label: 'The Very Tired Guest', hint: "You've been traveling all day. You need a bed NOW. Your eyes are closing." },
      b: { label: 'The Calm Complainer', hint: "You are very polite and very serious. You will not leave without a solution and a discount." },
      c: { label: 'The Stranger in Line', hint: "You're also checking in. You keep giving B advice on how to complain better. It makes things worse." },
      d: { label: 'The Front Desk Person', hint: "You're sorry about everything. The rules say you can't do more. B will not accept this." },
    },
    {
      emoji: '🏪',
      title: 'Midnight Convenience Store',
      situation: "It's 2am. One person is buying very strange things. The cashier has a lot of questions.",
      a: { label: 'The Midnight Shopper', hint: "The things in your basket look weird, but you have a perfectly good reason for each one. You explain them all to B." },
      b: { label: 'The Sleepy Cashier', hint: "You're supposed to scan things, not ask questions. But you have SO many questions about A's basket." },
      c: { label: 'The Other Customer', hint: "You came for one thing. Now you're deep in B's shopping choices. You have strong opinions." },
      d: { label: 'The Store Manager', hint: "You keep calling A on the store phone to check on something. A keeps ignoring you to talk to B and C." },
    },
    {
      emoji: '🎓',
      title: 'Group Project Disaster',
      situation: "One person did all the work. The presentation is in 10 minutes. The others just arrived.",
      a: { label: 'The One Who Did Everything', hint: "You're exhausted and furious. You have 10 minutes to teach B, C, and D everything about the project." },
      b: { label: 'The Late Arrival', hint: "You're very sorry. You want to help. But you have no idea what this project is even about." },
      c: { label: 'The Confident One', hint: "You haven't read a single page, but you're ready to present. You have a great gut feeling about it." },
      d: { label: 'The Nervous One', hint: "You read everything but you're too scared to speak. You keep whispering facts to A very quietly." },
    },
    {
      emoji: '🎂',
      title: 'The Ruined Surprise Party',
      situation: "Someone planned a surprise party. The birthday person already knows. Nobody knows that they know.",
      a: { label: 'The Birthday Person', hint: "You found out about the party last week. You're pretending to be surprised. It's very, very hard." },
      b: { label: 'The Party Planner', hint: "You worked so hard on this. You need A's reaction to be perfect. You keep watching A's face." },
      c: { label: 'The One Who Told A', hint: "You're the one who accidentally told A about the party. You're hoping nobody finds out it was you." },
      d: { label: 'The Suspicious Guest', hint: "You can tell A already knows. You keep giving C long, slow, suspicious looks." },
    },
    {
      emoji: '🧘',
      title: 'Wrong Yoga Class',
      situation: "Someone walked into the wrong yoga class. It's not for beginners. The class has already started.",
      a: { label: 'The Lost Newcomer', hint: "You thought this was 'gentle yoga for beginners.' You were very wrong. You can't do any of this." },
      b: { label: 'The Serious Yogi', hint: "You've practiced for 10 years. You are very upset about the energy in the room right now." },
      c: { label: 'The Helpful Neighbor', hint: "You're next to A and want to help. Your whispered instructions are making A more confused." },
      d: { label: 'The Yoga Teacher', hint: "You can see A is struggling badly. You keep giving A 'gentle encouragement' in a very calm, slow voice." },
    },
    {
      emoji: '🐶',
      title: 'Dog Park Chaos',
      situation: "One dog is causing trouble at the dog park. The owners all have very different reactions.",
      a: { label: 'The Embarrassed Owner', hint: "Your dog is causing all the problems. You can't stop saying sorry to everyone." },
      b: { label: 'The Angry Dog Owner', hint: "Your dog is the victim here. You want an apology from A. A full apology. In writing." },
      c: { label: 'The Dog Whisperer', hint: "You believe you can fix this by talking to the dogs. You think it's working. It's not working." },
      d: { label: 'The Person Without a Dog', hint: "You just came to sit on a bench and relax. Somehow you are now the most involved person here." },
    },
    {
      emoji: '🎤',
      title: 'After the Karaoke Song',
      situation: "Someone just finished singing a very bad song. They think it was great. Everyone is trying to respond.",
      a: { label: 'The Happy Singer', hint: "You just finished. You thought it was great. You're waiting for everyone's honest feedback." },
      b: { label: 'The Supportive Friend', hint: "You're trying so hard to say something nice. You are running out of things to say." },
      c: { label: 'The Honest Music Lover', hint: "You care deeply about music. You're trying not to say what you really think. You're failing." },
      d: { label: 'The MC', hint: "You need to keep the energy going after that performance. It is much harder than you expected." },
    },
    {
      emoji: '🍕',
      title: 'The Pizza Order',
      situation: "The group needs to order one pizza. Nobody can agree. The delivery person is waiting on the phone.",
      a: { label: 'The Classic Person', hint: "Plain cheese. No toppings. Perfect pizza. Simple. Why is everyone making this so hard?" },
      b: { label: 'The Topping Maximalist', hint: "You want everything on it. Everything. The more toppings, the better. This is non-negotiable." },
      c: { label: 'The Dietary Restriction Person', hint: "You have a list of things you can't eat. It's a long list. You're reading it now. Slowly." },
      d: { label: 'The Delivery Person (on phone)', hint: "You've been listening to this argument for 5 minutes. You need a decision. RIGHT NOW." },
    },
    {
      emoji: '🚿',
      title: 'One Bathroom, No Time',
      situation: "Roommates share one bathroom. Everyone has to be somewhere by 8am. It's 7:45.",
      a: { label: 'The Running Late One', hint: "You must leave in 10 minutes. You are not ready at all. You are knocking very loudly." },
      b: { label: 'The One Inside', hint: "You've been in the bathroom for 40 minutes. You're still not done. You're singing." },
      c: { label: 'The Calm One', hint: "You woke up early. You already have coffee. You're watching everything fall apart with great interest." },
      d: { label: 'The One Still in Bed', hint: "Everyone keeps knocking on your door to wake you up. You have reasons for staying in bed." },
    },
    {
      emoji: '📦',
      title: 'Moving Day',
      situation: "Moving into a new place. The big sofa does not fit through the door. Everyone has a plan.",
      a: { label: 'The Owner', hint: "This is your sofa. You have opinions on how to move it. Your opinions change every two minutes." },
      b: { label: 'The Mover', hint: "You're getting paid to move things. You didn't know it would be this complicated. You're sweating." },
      c: { label: 'The Friend Who Came to Help', hint: "You said you'd help. You didn't know 'help' meant carrying heavy things. Your back hurts." },
      d: { label: 'The New Neighbor', hint: "You came to say hello. Now you're giving directions on how to angle the sofa through the door." },
    },
    {
      emoji: '🎮',
      title: 'Game Night Disaster',
      situation: "Board game night. One person is winning by a lot. One person has no idea what they're doing.",
      a: { label: 'The Competitive Player', hint: "You're here to win. You've been winning. You have no patience for beginners who slow things down." },
      b: { label: 'The New Player', hint: "This is your first time. You're losing badly. You think A is being mean on purpose." },
      c: { label: 'The Rule Explainer', hint: "You know every single rule and you need everyone to know that you know every single rule." },
      d: { label: 'The Snack Person', hint: "You came for the food and the company. You have zero interest in the game. You keep asking when it ends." },
    },
    {
      emoji: '🚌',
      title: 'The Last Seat on the Bus',
      situation: "One seat left on a very crowded bus. Three people want it. The bus driver is watching.",
      a: { label: 'The Exhausted Worker', hint: "You've been standing for two hours. Your legs are giving up. You need this seat more than anyone." },
      b: { label: 'The Person With Bags', hint: "You have six bags and nowhere to put them. You need this seat for the bags. It makes sense to you." },
      c: { label: 'The Too-Polite One', hint: "You want the seat, but you keep offering it to A and B. You need to stop doing this. Please sit down." },
      d: { label: 'The Bus Driver', hint: "You've been watching this in your mirror. You have one rule: sit down or stand up. Just decide. Please." },
    },
    {
      emoji: '🤒',
      title: 'The Sick Roommate',
      situation: "One roommate is sick at home. The others all react in very different ways.",
      a: { label: 'The Sick One', hint: "You feel terrible. You need soup and silence. Everyone is being very strange and you want them to stop." },
      b: { label: 'The Worried Caretaker', hint: "You looked up A's symptoms online. You have bad news. You're not a doctor but you have a diagnosis." },
      c: { label: 'The Germaphobe', hint: "You cannot be in the same room as A. You've been spraying disinfectant on everything, including B." },
      d: { label: 'The Unbothered One', hint: "You feel completely fine. You finished A's leftover soup. You don't understand why C is being so dramatic." },
    },
    {
      emoji: '🎠',
      title: 'Theme Park Queue',
      situation: "A 2-hour line for a ride. People are bored. Someone just jumped the queue near the front.",
      a: { label: 'The Excited One', hint: "You've wanted to go on this ride your whole life. The 2-hour wait is completely worth it. You're happy." },
      b: { label: 'The Bored One', hint: "You had no idea the line was this long. You want to leave. A keeps talking you out of it." },
      c: { label: 'The Queue Entertainer', hint: "You've decided to keep everyone happy with games and jokes. You do this for 2 hours. Nobody asked." },
      d: { label: 'The Queue Jumper', hint: "You just walked to the front of the line. You have a 'very good reason.' A and B have strong feelings about this." },
    },
    {
      emoji: '🏠',
      title: 'Escape Room: 5 Minutes Left',
      situation: "Your group is stuck in an escape room. 5 minutes left. You still haven't solved the last puzzle.",
      a: { label: 'The Leader', hint: "You've solved three clues already. You're in charge. Nobody is listening to you. You're losing your mind." },
      b: { label: 'The Panicker', hint: "You can't think. You keep picking things up and putting them back in the wrong place. Sorry." },
      c: { label: 'The One Who\'s Been Here Before', hint: "You did this room last year. You remember the answer but you don't want to ruin it for everyone." },
      d: { label: 'The Phone Cheater', hint: "The rules said no phones. You're on your phone. You found the answer online. Should you tell everyone?" },
    },
    {
      emoji: '🏖️',
      title: 'Beach Day Gone Wrong',
      situation: "A relaxing beach day. Nothing is relaxing.",
      a: { label: 'The Over-Prepared One', hint: "You brought sunscreen, chairs, umbrellas, food, a first-aid kit, and three towels. It's a lot." },
      b: { label: 'The Under-Prepared One', hint: "You brought nothing. You're already sunburned. You keep asking A for things. A has everything." },
      c: { label: 'The Sandcastle Builder', hint: "You're building a very serious sandcastle. You need space. You need silence. Don't talk to you right now." },
      d: { label: 'The Wave Runner', hint: "You keep running into the waves and splashing everyone. You think this is the best day ever." },
    },
    {
      emoji: '🗺️',
      title: 'Lost Tourist',
      situation: "A tourist is completely lost. They need help. Several people are trying to help — in very different ways.",
      a: { label: 'The Lost Tourist', hint: "You need to get to the train station. Your map is upside down. Your language skills are limited." },
      b: { label: 'The Helpful Local', hint: "You want to help A so much. But A's map is wrong and you both point in different directions." },
      c: { label: 'The Other Tourist', hint: "You're also lost, but you pretend you know where everything is. You're leading everyone the wrong way." },
      d: { label: 'The Street Food Seller', hint: "You keep offering everyone food instead of directions. But everyone is slowly getting interested in the food." },
    },
    {
      emoji: '🥗',
      title: 'The Unhealthy Order',
      situation: "At a restaurant. One person ordered something very unhealthy. The others have opinions.",
      a: { label: 'The Happy Indulger', hint: "You ordered the biggest thing on the menu. You're very happy. You will not explain or apologize." },
      b: { label: 'The Healthy Eater', hint: "You've eaten clean for three months. A's order is everything you've given up. You have feelings." },
      c: { label: 'The Nutritionist Friend', hint: "You didn't want to say anything. But now you can't stop. You're listing facts at A. A doesn't care." },
      d: { label: 'The Server', hint: "You just want to take everyone's order and go. This table has been talking for 15 minutes. Please." },
    },
    {
      emoji: '🌧️',
      title: 'One Umbrella, No Cover',
      situation: "It's suddenly raining very hard. One person has an umbrella. The others do not.",
      a: { label: 'The Umbrella Owner', hint: "It's YOUR umbrella. You're deciding who gets to share it. This is a lot of pressure." },
      b: { label: 'The One Getting Wet', hint: "You're standing in the rain right now. You're looking at A. You're very, very wet." },
      c: { label: 'The Negotiator', hint: "You're trying to find a fair system for sharing the umbrella. You have a presentation ready." },
      d: { label: 'The One Who Doesn\'t Mind Rain', hint: "You think everyone is overreacting. You like rain. You keep saying so. Nobody cares." },
    },
  ],

};
