const GAME_DATA = {

  // ── Emotion Cards（25 種情緒）──────────────────────────────────────────────
  emotion: [
    { word: 'Happy',             emoji: '😄' },
    { word: 'Sad',                emoji: '😢' },
    { word: 'Angry',              emoji: '😠' },
    { word: 'Excited',            emoji: '🤩' },
    { word: 'Nervous',            emoji: '😬' },
    { word: 'Sleepy',             emoji: '😴' },
    { word: 'Surprised',          emoji: '😲' },
    { word: 'Confused',           emoji: '😕' },
    { word: 'Proud',              emoji: '🥇' },
    { word: 'Jealous',            emoji: '😒' },
    { word: 'Shy',                emoji: '🙈' },
    { word: 'Scared',             emoji: '😨' },
    { word: 'Bored',              emoji: '🥱' },
    { word: 'Silly',              emoji: '🤪' },
    { word: 'Calm',               emoji: '😌' },
    { word: 'Shocked',            emoji: '⚡' },
    { word: 'Grumpy',             emoji: '😤' },
    { word: 'Curious',            emoji: '🧐' },
    { word: 'Embarrassed',        emoji: '😳' },
    { word: 'Lonely',             emoji: '🥺' },
    { word: 'Hopeful',            emoji: '🤞' },
    { word: 'Disgusted',          emoji: '🤢' },
    { word: 'Relieved',           emoji: '😮‍💨' },
    { word: 'Confident',          emoji: '😎' },
    { word: 'Tired',              emoji: '😪' },
  ],

  // ── Pick a Side! ───────────────────────────────────────────────────────────
  hottake: [
    "Texting 'haha' when you didn't actually laugh is lying, and we all do it every day.",
    "Cold pizza the next morning tastes better than hot pizza the night before.",
    "Watching a movie at home is better than going to the cinema in every possible way.",
    "Small talk about the weather is a beautiful human tradition, not a boring one.",
    "A messy desk is a sign of a busy mind, not a lazy person.",
    "People who reply to messages instantly are scarier than people who reply two days later.",
    "If you need three alarms to wake up, the problem is not the alarms.",
    "Group video calls should have a 30-minute limit — by law.",
    "Buying books you never read still counts as a hobby.",
    "The window seat is objectively the best seat, and aisle-seat people know it.",
  ],

  // ── Sophie's Choice ────────────────────────────────────────────────────────
  sophies: [
    { cat: '💼 Work',
      situation: 'You spend three weeks preparing a major presentation. The day before the big meeting, your supervisor reviews it, then presents it entirely as their own work in front of the executives, who are visibly impressed. This same supervisor is otherwise a great mentor, and is deciding whether to give you a promotion next month.',
      a: 'Confront your supervisor directly and demand credit, even if it damages the relationship right before a promotion decision.',
      b: 'Stay quiet and protect the promotion instead. The credit is already gone, and this relationship can still help your career.',
    },
    { cat: '🏥 Health',
      situation: 'You are an ER triage nurse. The waiting room is packed, and a wealthy celebrity walks in with a minor ankle sprain. Your hospital director quietly asks you to fast-track them, hinting at a huge donation to the hospital, but that means delaying an elderly patient with a high fever who has been waiting far longer.',
      a: 'Fast-track the celebrity. The donation could fund better care for thousands of future patients.',
      b: 'Treat people in the order they arrived. Medical need should never depend on someone with money.',
    },
    { cat: '❤️ Love',
      situation: 'After four happy years together, your partner is offered a dream job on the other side of the world, starting in two months. You love your own job, friends, and family right where you are, and moving means starting your career again from zero.',
      a: 'Move with them and rebuild your life from scratch. Some opportunities never come twice.',
      b: 'Ask them to stay, or try long distance instead. Your own life and career deserve to matter too.',
    },
    { cat: '👨‍👩‍👦 Family',
      situation: 'A parent leaves a modest $50,000 inheritance to be split equally between you and a sibling, but you spent five years as their unpaid full-time caregiver while the sibling rarely visited. When you ask for a larger share, the sibling refuses, saying they need every cent to cover their own debts.',
      a: 'Accept the equal split. Fighting over money will not bring a parent back, and family peace matters more.',
      b: 'Fight for a bigger share. Five years of unpaid caregiving is worth more than an equal split on paper.',
    },
    { cat: '💼 Work',
      situation: 'You are a teacher. The star player on the basketball team is failing your class with a 58%, which would bench him from the championship game on Friday. The principal strongly suggests you raise the grade to a passing 60%, since college scouts are coming specifically to watch him play.',
      a: 'Hold the line and fail him. A grade should reflect the work done, not the game schedule.',
      b: 'Raise the grade. One scholarship could change the direction of an entire life.',
    },
    { cat: '💰 Money',
      situation: 'Late at night you find a designer backpack stuffed with $10,000 cash on the floor of a taxi, with no ID and no name inside. The driver seems visibly stressed, worrying aloud about paying rent this month.',
      a: 'Hand the bag straight to the driver. He is right there, he clearly needs it, and finders-keepers rules feel wrong tonight.',
      b: 'Take it to the police station instead. It is not your money to give away, even with good intentions.',
    },
    { cat: '💼 Work',
      situation: 'You are a sous chef the night the most brutal food critic in the city is dining in. Your head chef drops a premium steak on the kitchen floor, sears it briefly to kill the germs, and tells you to plate it anyway. The kitchen is completely out of that cut of meat, and a bad review could bankrupt the restaurant.',
      a: 'Refuse to serve it and tell the critic the dish is unavailable, even if a bad review might sink the restaurant.',
      b: 'Plate it and send it out. One risky steak feels smaller than every job in this kitchen.',
    },
    { cat: '⚖️ Ethics & Law',
      situation: 'Walking through an empty parking lot at night, you see someone smash a car window and start hotwiring the engine, then realize it is the 19-year-old son of a coworker, who has been struggling with addiction. The police in this city are notoriously corrupt and brutal, and calling them could end far worse than the crime itself.',
      a: 'Call the police anyway. A crime is a crime, and looking away does not actually help him.',
      b: 'Step in yourself and stop him without police involvement, protecting him from a system that could destroy his life.',
    },
    { cat: '⚖️ Ethics & Law',
      situation: 'You watch a struggling delivery driver accidentally dent a $200,000 sports car, then beg you not to report it, since reporting means he loses his job and cannot feed his kids. You already snapped a photo of the license plate. Minutes later, the wealthy owner of the car returns and asks if you saw who did it.',
      a: 'Show the owner the photo. It is still his property that was damaged, whoever ends up paying for it.',
      b: 'Say you saw nothing. One dent on a rich car matters far less than a family able to eat.',
    },
    { cat: '⚖️ Ethics & Law',
      situation: 'At 2am, you wake to screaming and a violent argument through the thin wall of your apartment, then a voice yells for it to stop, followed by a loud thud. The neighbor is a known gang member with a history of retaliation, and would instantly know it was you who called, since your name is right on your door.',
      a: 'Call the police immediately. Someone could be in real danger, and that outweighs the risk to yourself.',
      b: 'Stay silent and let it pass. Protecting yourself from a violent neighbor is not selfish, it is survival.',
    },
    { cat: '❤️ Love',
      situation: 'Your best friend, drunk and in tears, confesses she has secretly been in love with your boyfriend for a year, swearing nothing ever happened between them. The next morning you glimpse a text on his phone from her, hinting they already kissed once before and worrying that you now suspect it.',
      a: 'Confront your boyfriend right now. You deserve the truth immediately, not a slow reveal.',
      b: 'Say nothing for now and watch how they behave. Acting too fast might mean missing what is really going on.',
    },
    { cat: '👨‍👩‍👦 Family',
      situation: 'Your sibling brings a new partner to a big family dinner, and it turns out to be your worst, most toxic ex, the one who once broke your heart. Your sibling is already talking about moving in together, and the ex quietly begs you not to ruin this, insisting they have truly changed.',
      a: 'Pull your sibling aside and tell them everything you know. They deserve to walk in with open eyes.',
      b: 'Stay quiet and let them find out on their own. People really can change, and it is not only your story to tell.',
    },
    { cat: '🤝 Friendship',
      situation: 'As Maid of Honor, two hours before the ceremony you overhear the groom on the phone with a secret lover, saying today is just a formality for his family and that he still plans to leave next year. Your friend is glowing with happiness, and her parents are already crying tears of joy in the front row.',
      a: 'Pull your friend aside privately before the ceremony, even if it destroys the day she has dreamed of.',
      b: 'Let the wedding happen and tell her after the honeymoon. Some truths can wait a few more days without changing the outcome.',
    },
    { cat: '👨‍👩‍👦 Family',
      situation: 'At a dinner hosted by intimidating in-laws, their signature dish tastes awful, but trying to be polite, you gush that it is the best thing you have ever eaten. The mother beams with pride, grabs a huge serving spoon, and piles you a full second tray to finish alone.',
      a: 'Push through and eat the whole tray. You started this performance, so you might as well finish it.',
      b: 'Come clean that you were just being polite. An awkward moment now beats years of giant second helpings.',
    },
    { cat: '💼 Work',
      situation: 'Five minutes into your dream-job interview, you notice a huge piece of spinach wedged in the front teeth of the interviewer, shifting every time they talk. At this exact moment, they are giving a passionate speech about how much they value absolute honesty and attention to detail.',
      a: 'Politely point it out right away. They just described exactly the kind of employee they want to hire.',
      b: 'Say nothing and power through the interview. It is not your job to fix an unrelated, awkward moment.',
    },
    { cat: '🎉 Social',
      situation: 'Walking out of a crowded store into the mall, security alarms suddenly blare and everyone turns to stare. You realize you completely forgot you were trying on a jacket from the display rack, security tag still dangling from the sleeve, and a very dramatic security guard is now charging straight at you.',
      a: 'Stop immediately and calmly explain the honest mistake before it becomes a bigger scene.',
      b: 'Keep walking like nothing happened and let the guard catch up to you. Panicking now would only make it look worse.',
    },
    { cat: '💼 Work',
      situation: 'You just finished a brutal call with a famously difficult client. Thinking the meeting has ended, you turn to a coworker and loudly complain that the client is completely incompetent. Your mouse actually slipped though. You only minimized the window, and the client is still there, frozen and staring straight at you.',
      a: 'Own it immediately and apologize sincerely. A fast, honest apology repairs more than it feels like in the moment.',
      b: 'Claim it was a glitch and pretend you were talking about a movie character. A confident save might just work.',
    },
    { cat: '💼 Work',
      situation: 'Mid-presentation to your biggest client, a desktop notification from home pops up on the shared screen, complaining about smelly gym socks left on the sofa and a reminder to buy toilet paper. Your mouse freezes for ten agonizing seconds while the client CEO clears his throat and asks about those numbers, and the socks.',
      a: 'Laugh it off with a quick joke and dive straight back into the numbers like nothing happened.',
      b: 'Address it directly with a self-deprecating joke about your laundry habits. Owning it head-on can turn embarrassment into charm.',
    },
    { cat: '⚖️ Ethics & Law',
      situation: 'As prosecutor, your only evidence against a dangerous suspect is a supposedly blind witness who says he heard the crime from a park bench. During a recess, he instinctively catches a dropped pen out of the air, proving his blindness, and his entire testimony, is a fraud.',
      a: 'Expose him as a fraud. The case has to stand on real evidence, not a lie you now know about.',
      b: 'Keep his secret and let the testimony stand. Letting a dangerous suspect walk free feels far worse than one fraudulent witness.',
    },
    { cat: '⚖️ Ethics & Law',
      situation: 'As a court-appointed psychiatrist, you are evaluating a wealthy CEO who claims total amnesia after a hit-and-run, which would make him unfit to stand trial. During a private session, he instinctively smiles at the mention of a childhood nickname only a private diary would know, before catching himself. The amnesia is clearly an act.',
      a: 'Report the real findings to the judge. Faking incompetence to dodge a trial should not be rewarded.',
      b: 'Write the diagnosis he is hoping for. It is not your job to be the one who sends him to prison.',
    },
    { cat: '⚖️ Ethics & Law',
      situation: 'As defense attorney, your entire case rests on a diagnosed dissociative identity disorder, where a violent alternate personality supposedly committed the murder, not the innocent host personality. In a private meeting, that violent alter lets slip a detail only someone truly present at the crime could know, revealing the whole disorder was a calculated act.',
      a: 'Expose the deception to the court. A cold, calculating killer should not escape justice through a lie you helped build.',
      b: 'Protect the secret and finish winning the case. Your duty is to defend a client, not to judge one.',
    },
    { cat: '⚖️ Ethics & Law',
      situation: 'As a traffic officer, you pull over an Uber driver and discover his license actually belongs to someone else, bought to dodge an expensive background check. In tears, he explains it is the only way he can afford life-saving medicine for his daughter, and losing the car means losing everything by next week.',
      a: 'Impound the car and report the fraud. An unlicensed driver on the road is a real risk to other people.',
      b: 'Let him go with a warning. Saving his daughter matters more than a piece of paper he could not afford.',
    },
    { cat: '⚖️ Ethics & Law',
      situation: 'Responding to a complaint, you find a low-income family secretly running an unlicensed restaurant out of their garage, feeding dozens of neighborhood workers who cannot afford regular prices. The income is funding chemotherapy for their grandmother, but there are no health permits, and no food safety inspections.',
      a: 'Shut the kitchen down. Food safety rules exist to prevent an outbreak that could hurt far more people.',
      b: 'Look the other way this time. Ongoing chemotherapy and dozens of family meals depend on this staying open.',
    },
    { cat: '⚖️ Ethics & Law',
      situation: 'Reviewing security licenses, you discover a well-loved luxury building guard is working under a bought, fake ID, since a record from 15 years ago bars him from getting licensed legally. For five years he has been an exemplary employee who once risked his life stopping a burglary, and he is the sole income for his family.',
      a: 'Report the fraud and enforce the rules. Licensing exists for a reason, no matter how good a record has been since.',
      b: 'Quietly clear his file. Five years of proven, honest work should count for more than a decade-old mistake.',
    },
    { cat: '🤝 Friendship',
      situation: 'Your best friend runs a small local charity event and asks you to audit the ticket sales just to check the math. The spreadsheet reveals a clear $500 shortfall, and the digital trail shows your friend took the money for personal use. Their family is currently facing eviction, and this charity currently feeds over 100 families in the community every week.',
      a: 'Report the missing funds to the board. A charity built on covered-up theft is not one worth protecting.',
      b: 'Quietly fix the spreadsheet yourself. The meals of a hundred families matter more than exposing one desperate mistake.',
    },
    { cat: '🤝 Friendship',
      situation: 'A new volunteer soccer coach has completely turned around the struggling youth team at your community center, giving local kids pride and purpose. While filing his paperwork, you discover he lied about holding the mandatory coaching certification, and has a minor, decade-old misdemeanor on record. Reporting it means the league disqualifies the whole team instantly.',
      a: 'Report it and follow league policy. Rules about who works with kids exist for good reasons, even when someone is doing great work.',
      b: 'Shred the paperwork and let him keep coaching. The good he is doing for these kids right now outweighs a technicality from years ago.',
    },
    { cat: '🏫 School',
      situation: 'As team leader on a project worth 60% of your grade, one member misses the final deadline, so you stay up all night finishing their part yourself and submit flawless work. The next morning you learn they missed it because a parent was suddenly hospitalized, but the rest of the group is furious about including their name anyway.',
      a: 'Tell the professor exactly what happened, contribution and circumstances both. Full honesty protects everyone, including the missing teammate.',
      b: 'Leave their name on the project and say nothing. A hospitalized parent is excuse enough.',
    },
    { cat: '⚖️ Ethics & Law',
      situation: 'The beloved dog of your elderly, isolated neighbor escapes the yard and bites a delivery driver badly enough to draw blood, and you are the only witness. Reporting the bite means the dog is likely confiscated and euthanized, and a doctor has already warned that losing the dog could seriously harm the fragile health of your neighbor.',
      a: 'Report the bite. Public safety has to come first, especially once blood has already been drawn.',
      b: 'Stay silent and quietly ask your neighbor to fix the fence instead. Their health and their only companion matter more than one bad afternoon.',
    },
    { cat: '🏥 Health',
      situation: 'You lead a clinical trial for a promising new cancer drug, strictly required to give half the patients a placebo in order to legally prove the drug works. One placebo patient, a young parent, is deteriorating fast and will not survive the three remaining months of the trial without the real medication.',
      a: 'Secretly switch the placebo for the real drug. One life in front of you matters more than the integrity of a spreadsheet.',
      b: 'Keep the trial exactly as designed. Breaking protocol could invalidate a drug that saves far more lives down the road.',
    },
    { cat: '🏥 Health',
      situation: 'As transplant coordinator, one liver has just become available for two equally compatible patients. Patient A is a brilliant scientist close to a cheap malaria cure that could save hundreds of thousands of lives worldwide. Patient B is a 14-year-old child with a full life still ahead of them.',
      a: 'Give it to the scientist. Maximizing lives saved worldwide has to outweigh the personal outcome of one recipient.',
      b: 'Give it to the child. A transplant list should judge the years of life given back, not the future potential of one patient.',
    },
    { cat: '💰 Money',
      situation: 'You order a basic $400 television online, but the delivery box actually contains a top-of-the-line $2,000 model. The receipt lists the cheap television under your name and address, the driver is long gone, and the automated tracking system already marks the order as successfully delivered.',
      a: 'Call customer service and report the mix-up. It is still not the item you paid for.',
      b: 'Keep it and say nothing. A shipping mistake by a billion-dollar company is not exactly your responsibility to fix.',
    },
    { cat: '🤝 Friendship',
      situation: 'It is the 30th birthday dinner of your best friend, which you promised months ago to attend. An hour before you are due to leave, a cousin you have not seen in five years surprises you in town for one night only, holding two expensive tickets to see your favorite team play tonight.',
      a: 'Go to the birthday dinner. You made that promise first, and milestones like this do not come back around.',
      b: 'Go to the game with your cousin. A once-in-five-years visit and a gift like that might never happen again.',
    },
    { cat: '💼 Work',
      situation: 'While closing the register, you accidentally drop a $100 bill into a gap behind the counter, permanently lost inside the vent. Your manager notices the shortfall the next day and, assuming it is theft, blames the morning shift worker, someone you do not even like, threatening to cut their hours as punishment.',
      a: 'Admit what really happened, even if it means you are the one who gets blamed or fined instead.',
      b: 'Stay quiet and let it go. Speaking up now risks your own job over money that is genuinely gone either way.',
    },
    { cat: '🤝 Friendship',
      situation: 'While pet-sitting for vacationing neighbors, you accidentally let their cat slip out the door, and it runs off for good despite hours of searching. At the shelter you find a cat that looks just like it, and could quietly swap it in before they ever notice a thing.',
      a: 'Call them and tell them the truth right away, even though it will ruin the rest of their vacation.',
      b: 'Adopt the look-alike and say nothing. Sparing them a needless, unfixable heartbreak feels kinder than confessing.',
    },
    { cat: '🤝 Friendship',
      situation: 'Your closest friend just finished a novel they spent three years writing, and asks you to be the first honest reader. It is genuinely bad, with a confusing plot and flat characters, and tomorrow they are paying a non-refundable $1,000 to self-publish 500 physical copies.',
      a: 'Tell them the truth now, even if it is painful, before they spend $1,000 they cannot get back.',
      b: 'Tell them it is amazing and let them publish it. Their confidence and their dream matter more than your personal opinion.',
    },
    { cat: '💼 Work',
      situation: 'A laid-off former coworker lists you as a reference for a job they desperately need. You know them to be kind but genuinely unreliable and disorganized at work, and the hiring manager calls, ready to trust whatever you say about their work ethic.',
      a: 'Tell the honest truth about their work habits, even knowing it likely costs them the job.',
      b: 'Give them a glowing reference anyway. A desperate need for income matters more than a decision made by a stranger.',
    },
    { cat: '❤️ Love',
      situation: 'You finally confess a year-long crush to a close friend in a heartfelt letter. He is touched, but gently explains he is gay and asks you to keep it secret, since he is not ready to come out. Your overprotective sibling assumes he led you on, and publicly calls him a jerk in front of your entire friend group.',
      a: 'Tell your sibling the truth to defend the reputation of your friend, even though it forces him out before he is ready.',
      b: 'Stay silent and protect his secret, even while everyone around you thinks he is the villain of the story.',
    },
    { cat: '🏫 School',
      situation: 'Late at the library, you witness your favorite professor, happily married to another university dean, kissing a classmate. The professor is currently writing your recommendation letter for a life-changing scholarship. The next day, that classmate admits to the affair and begs you to help report the professor for using their grading power to manipulate them.',
      a: 'Support your classmate and report the professor, even knowing it could cost you the recommendation letter.',
      b: 'Stay silent and protect your scholarship instead. It is not entirely your secret or your fight to bring forward.',
    },
  ],

  // ── Persuade Together! ─────────────────────────────────────────────────────
  persuade: [
    { cat:'🏢 Workplace', judge:'Office Manager', emoji:'🎧',
      team:'Employees who want to wear headphones at their desks',
      situation:'The office manager banned headphones at work, worried it makes the team seem unfriendly. Convince the manager that headphones actually help everyone focus and get more done.' },
    { cat:'🏫 School', judge:'Principal', emoji:'📱',
      team:'Students who want phones allowed during lunch break',
      situation:'The principal banned phones on campus after students got distracted in class. Convince the principal that phones should at least be allowed during lunch break.' },
    { cat:'🏠 Family', judge:'Parent', emoji:'🐶',
      team:'Kids who want to get a family dog',
      situation:'One parent thinks a dog is too much work for the family. Convince them that everyone will help take care of a new dog.' },
    { cat:'🏋️ Gym', judge:'Gym Owner', emoji:'🎶',
      team:'Members who want louder music during workouts',
      situation:'The gym owner keeps the music very quiet so people can talk. Convince the owner that louder music would make workouts more fun.' },
    { cat:'🏘️ Apartment', judge:'Building Manager', emoji:'🎉',
      team:'Residents who want to host a rooftop party',
      situation:'The building manager worries a rooftop party will get too loud and cause complaints. Convince the manager to allow one supervised party this summer.' },
    { cat:'✈️ Travel', judge:'Trip Organizer', emoji:'🏖️',
      team:'Friends who want to change the group trip destination',
      situation:'The trip organizer already booked a mountain cabin, but half the group wants a beach trip instead. Convince the organizer to switch the destination before it\'s too late.' },
    { cat:'🍽️ Restaurant', judge:'Restaurant Owner', emoji:'🌶️',
      team:'Regular customers who want a spicier menu option',
      situation:'The restaurant owner thinks the current menu is spicy enough for most customers. Convince the owner to add one very spicy dish to the menu.' },
    { cat:'⚽ Sports Team', judge:'Team Coach', emoji:'🎽',
      team:'Players who want to change the team jersey design',
      situation:'The coach likes the current jersey design and doesn\'t want to spend money changing it. Convince the coach that a new design would boost team spirit.' },
    { cat:'📚 Book Club', judge:'Book Club Host', emoji:'🎬',
      team:'Members who want to watch the movie instead of reading the book this month',
      situation:'The host insists the group always reads the full book before meeting. Convince the host to make an exception and discuss the movie version this one time.' },
    { cat:'🎂 Birthday Party', judge:'Party Planner (a close friend)', emoji:'🎈',
      team:'Friends who want to throw a surprise party',
      situation:'The party planner thinks surprise parties are stressful and risky. Convince them that a surprise party is worth the risk for this birthday.' },
  ],

  // ── Word Wolf ────────────────────────────────────────────────────────────
  // Almost everyone gets word "a", one secret Wolf gets word "b" instead.
  wordwolf: [
    { cat:'🍔 Food & Drink', emojiA:'☕', emojiB:'🍵', a:'Coffee', b:'Tea' },
    { cat:'🍔 Food & Drink', emojiA:'🍕', emojiB:'🍔', a:'Pizza', b:'Hamburger' },
    { cat:'🍔 Food & Drink', emojiA:'🎂', emojiB:'🍪', a:'Cake', b:'Cookie' },
    { cat:'🍔 Food & Drink', emojiA:'🍎', emojiB:'🍊', a:'Apple', b:'Orange' },
    { cat:'🍔 Food & Drink', emojiA:'🍚', emojiB:'🍜', a:'Rice', b:'Noodles' },
    { cat:'🐾 Animals', emojiA:'🐱', emojiB:'🐶', a:'Cat', b:'Dog' },
    { cat:'🐾 Animals', emojiA:'🦁', emojiB:'🐯', a:'Lion', b:'Tiger' },
    { cat:'🐾 Animals', emojiA:'🐬', emojiB:'🦈', a:'Dolphin', b:'Shark' },
    { cat:'🐾 Animals', emojiA:'🦋', emojiB:'🐝', a:'Butterfly', b:'Bee' },
    { cat:'🐾 Animals', emojiA:'🐴', emojiB:'🦓', a:'Horse', b:'Zebra' },
    { cat:'🗺️ Places', emojiA:'🌊', emojiB:'🏞️', a:'Ocean', b:'Lake' },
    { cat:'🗺️ Places', emojiA:'🏔️', emojiB:'⛰️', a:'Mountain', b:'Hill' },
    { cat:'🗺️ Places', emojiA:'🏜️', emojiB:'🏖️', a:'Desert', b:'Beach' },
    { cat:'🗺️ Places', emojiA:'🏘️', emojiB:'🏙️', a:'Village', b:'City' },
    { cat:'🗺️ Places', emojiA:'🏨', emojiB:'⛺', a:'Hotel', b:'Campsite' },
    { cat:'🗺️ Places', emojiA:'📚', emojiB:'📖', a:'Library', b:'Bookstore' },
    { cat:'🚗 Transport', emojiA:'✈️', emojiB:'🚁', a:'Airplane', b:'Helicopter' },
    { cat:'🚗 Transport', emojiA:'🚲', emojiB:'🏍️', a:'Bicycle', b:'Motorcycle' },
    { cat:'🚗 Transport', emojiA:'🚆', emojiB:'🚇', a:'Train', b:'Subway' },
    { cat:'🚗 Transport', emojiA:'🚗', emojiB:'🚕', a:'Car', b:'Taxi' },
    { cat:'🚗 Transport', emojiA:'🚢', emojiB:'⛵', a:'Ship', b:'Sailboat' },
    { cat:'🎵 Music', emojiA:'🎸', emojiB:'🎻', a:'Guitar', b:'Violin' },
    { cat:'🎵 Music', emojiA:'🎺', emojiB:'🎷', a:'Trumpet', b:'Saxophone' },
    { cat:'🎵 Music', emojiA:'🥁', emojiB:'🎹', a:'Drum', b:'Piano' },
    { cat:'💼 Jobs', emojiA:'🩺', emojiB:'💉', a:'Doctor', b:'Nurse' },
    { cat:'💼 Jobs', emojiA:'👮', emojiB:'🧑‍🚒', a:'Police Officer', b:'Firefighter' },
    { cat:'💼 Jobs', emojiA:'👨‍🍳', emojiB:'🧑‍🍽️', a:'Chef', b:'Waiter' },
    { cat:'💼 Jobs', emojiA:'👨‍🏫', emojiB:'🎓', a:'Teacher', b:'Professor' },
    { cat:'☀️ Weather', emojiA:'❄️', emojiB:'🍂', a:'Winter', b:'Autumn' },
    { cat:'☀️ Weather', emojiA:'🌧️', emojiB:'🌫️', a:'Rain', b:'Fog' },
    { cat:'☀️ Weather', emojiA:'☀️', emojiB:'🌙', a:'Sun', b:'Moon' },
    { cat:'🎯 Activities', emojiA:'⚽', emojiB:'🏀', a:'Soccer', b:'Basketball' },
    { cat:'🎯 Activities', emojiA:'🏊', emojiB:'🏄', a:'Swimming', b:'Surfing' },
    { cat:'🎯 Activities', emojiA:'🎨', emojiB:'✏️', a:'Painting', b:'Drawing' },
    { cat:'🎒 Objects', emojiA:'☔', emojiB:'🧥', a:'Umbrella', b:'Raincoat' },
    { cat:'🎒 Objects', emojiA:'🎒', emojiB:'🧳', a:'Backpack', b:'Suitcase' },
    { cat:'🎒 Objects', emojiA:'📷', emojiB:'🔭', a:'Camera', b:'Telescope' },
    { cat:'🎒 Objects', emojiA:'🤖', emojiB:'👽', a:'Robot', b:'Alien' },
    { cat:'🍔 Food & Drink', emojiA:'🥛', emojiB:'🧃', a:'Milk', b:'Juice' },
    { cat:'🍔 Food & Drink', emojiA:'🍞', emojiB:'🥯', a:'Bread', b:'Bagel' },
    { cat:'🍔 Food & Drink', emojiA:'🍲', emojiB:'🍛', a:'Soup', b:'Curry' },
    { cat:'🍔 Food & Drink', emojiA:'🍌', emojiB:'🥭', a:'Banana', b:'Mango' },
    { cat:'🍔 Food & Drink', emojiA:'🍓', emojiB:'🍒', a:'Strawberry', b:'Cherry' },
    { cat:'🍔 Food & Drink', emojiA:'🍉', emojiB:'🍍', a:'Watermelon', b:'Pineapple' },
    { cat:'🍔 Food & Drink', emojiA:'🍫', emojiB:'🍬', a:'Chocolate', b:'Candy' },
    { cat:'🍔 Food & Drink', emojiA:'🍿', emojiB:'🍟', a:'Popcorn', b:'French Fries' },
    { cat:'🍔 Food & Drink', emojiA:'🥪', emojiB:'🌯', a:'Sandwich', b:'Burrito' },
    { cat:'🍔 Food & Drink', emojiA:'🍣', emojiB:'🥟', a:'Sushi', b:'Dumpling' },
    { cat:'🍔 Food & Drink', emojiA:'🍦', emojiB:'🍧', a:'Ice Cream', b:'Shaved Ice' },
    { cat:'🍔 Food & Drink', emojiA:'🍺', emojiB:'🍷', a:'Beer', b:'Wine' },
    { cat:'🍔 Food & Drink', emojiA:'🥚', emojiB:'🥓', a:'Egg', b:'Bacon' },
    { cat:'🍔 Food & Drink', emojiA:'🥞', emojiB:'🧇', a:'Pancake', b:'Waffle' },
    { cat:'🍔 Food & Drink', emojiA:'🥗', emojiB:'🥙', a:'Salad', b:'Wrap' },
    { cat:'🐾 Animals', emojiA:'🐘', emojiB:'🦏', a:'Elephant', b:'Rhino' },
    { cat:'🐾 Animals', emojiA:'🐒', emojiB:'🦍', a:'Monkey', b:'Gorilla' },
    { cat:'🐾 Animals', emojiA:'🐰', emojiB:'🐿️', a:'Rabbit', b:'Squirrel' },
    { cat:'🐾 Animals', emojiA:'🐸', emojiB:'🐢', a:'Frog', b:'Turtle' },
    { cat:'🐾 Animals', emojiA:'🐍', emojiB:'🦎', a:'Snake', b:'Lizard' },
    { cat:'🐾 Animals', emojiA:'🦉', emojiB:'🦅', a:'Owl', b:'Eagle' },
    { cat:'🐾 Animals', emojiA:'🐧', emojiB:'🦭', a:'Penguin', b:'Seal' },
    { cat:'🐾 Animals', emojiA:'🐺', emojiB:'🦊', a:'Wolf', b:'Fox' },
    { cat:'🐾 Animals', emojiA:'🦌', emojiB:'🐐', a:'Deer', b:'Goat' },
    { cat:'🐾 Animals', emojiA:'🐑', emojiB:'🐄', a:'Sheep', b:'Cow' },
    { cat:'🐾 Animals', emojiA:'🐷', emojiB:'🦛', a:'Pig', b:'Hippo' },
    { cat:'🐾 Animals', emojiA:'🐔', emojiB:'🦆', a:'Chicken', b:'Duck' },
    { cat:'🐾 Animals', emojiA:'🕷️', emojiB:'🦂', a:'Spider', b:'Scorpion' },
    { cat:'🐾 Animals', emojiA:'🐋', emojiB:'🐙', a:'Whale', b:'Octopus' },
    { cat:'🐾 Animals', emojiA:'🐫', emojiB:'🦙', a:'Camel', b:'Llama' },
    { cat:'🐾 Animals', emojiA:'🐹', emojiB:'🐭', a:'Hamster', b:'Mouse' },
    { cat:'🐾 Animals', emojiA:'🦢', emojiB:'🦩', a:'Swan', b:'Flamingo' },
    { cat:'🐾 Animals', emojiA:'🐊', emojiB:'🦖', a:'Crocodile', b:'Dinosaur' },
    { cat:'🗺️ Places', emojiA:'🏫', emojiB:'🎓', a:'School', b:'University' },
    { cat:'🗺️ Places', emojiA:'🏥', emojiB:'💊', a:'Hospital', b:'Pharmacy' },
    { cat:'🗺️ Places', emojiA:'⛪', emojiB:'🛕', a:'Church', b:'Temple' },
    { cat:'🗺️ Places', emojiA:'🛫', emojiB:'🚉', a:'Airport', b:'Train Station' },
    { cat:'🗺️ Places', emojiA:'🍽️', emojiB:'🚚', a:'Restaurant', b:'Food Truck' },
    { cat:'🗺️ Places', emojiA:'🏛️', emojiB:'🖼️', a:'Museum', b:'Art Gallery' },
    { cat:'🗺️ Places', emojiA:'🌳', emojiB:'🌷', a:'Park', b:'Garden' },
    { cat:'🗺️ Places', emojiA:'🚜', emojiB:'🐄', a:'Farm', b:'Ranch' },
    { cat:'🗺️ Places', emojiA:'🏟️', emojiB:'🏋️', a:'Stadium', b:'Gym' },
    { cat:'🗺️ Places', emojiA:'🌉', emojiB:'🕳️', a:'Bridge', b:'Tunnel' },
    { cat:'🗺️ Places', emojiA:'🏰', emojiB:'🏯', a:'Castle', b:'Palace' },
    { cat:'🗺️ Places', emojiA:'🌲', emojiB:'🌴', a:'Forest', b:'Jungle' },
    { cat:'🗺️ Places', emojiA:'🦁', emojiB:'🐠', a:'Zoo', b:'Aquarium' },
    { cat:'🗺️ Places', emojiA:'🏭', emojiB:'🏗️', a:'Factory', b:'Construction Site' },
    { cat:'🗺️ Places', emojiA:'🛒', emojiB:'🏪', a:'Supermarket', b:'Convenience Store' },
    { cat:'🚗 Transport', emojiA:'🚌', emojiB:'🚐', a:'Bus', b:'Van' },
    { cat:'🚗 Transport', emojiA:'🚂', emojiB:'🚋', a:'Locomotive', b:'Tram' },
    { cat:'🚗 Transport', emojiA:'🛵', emojiB:'🛴', a:'Scooter', b:'Kick Scooter' },
    { cat:'🚗 Transport', emojiA:'🚀', emojiB:'🛰️', a:'Rocket', b:'Satellite' },
    { cat:'🚗 Transport', emojiA:'⛴️', emojiB:'🛳️', a:'Ferry', b:'Cruise Ship' },
    { cat:'🚗 Transport', emojiA:'🚡', emojiB:'🎢', a:'Cable Car', b:'Roller Coaster' },
    { cat:'🚗 Transport', emojiA:'🛹', emojiB:'⛸️', a:'Skateboard', b:'Ice Skates' },
    { cat:'🚗 Transport', emojiA:'🚒', emojiB:'🚑', a:'Fire Truck', b:'Ambulance' },
    { cat:'🎵 Music', emojiA:'🎤', emojiB:'🎧', a:'Microphone', b:'Headphones' },
    { cat:'🎵 Music', emojiA:'🪕', emojiB:'🪗', a:'Banjo', b:'Ukulele' },
    { cat:'🎵 Music', emojiA:'🎻', emojiB:'🪗', a:'Cello', b:'Accordion' },
    { cat:'🎵 Music', emojiA:'📻', emojiB:'🔊', a:'Radio', b:'Speaker' },
    { cat:'🎵 Music', emojiA:'🎙️', emojiB:'📢', a:'Podcast Mic', b:'Megaphone' },
    { cat:'💼 Jobs', emojiA:'👨‍⚖️', emojiB:'🧑‍⚖️', a:'Judge', b:'Lawyer' },
    { cat:'💼 Jobs', emojiA:'🧑‍🌾', emojiB:'🌻', a:'Farmer', b:'Gardener' },
    { cat:'💼 Jobs', emojiA:'👷', emojiB:'🏗️', a:'Construction Worker', b:'Engineer' },
    { cat:'💼 Jobs', emojiA:'🧑‍🚀', emojiB:'🧑‍✈️', a:'Astronaut', b:'Pilot' },
    { cat:'💼 Jobs', emojiA:'🧑‍🎨', emojiB:'🧑‍💻', a:'Artist', b:'Programmer' },
    { cat:'💼 Jobs', emojiA:'💊', emojiB:'🧑‍🔬', a:'Pharmacist', b:'Scientist' },
    { cat:'💼 Jobs', emojiA:'🕵️', emojiB:'🔎', a:'Detective', b:'Private Investigator' },
    { cat:'💼 Jobs', emojiA:'🧑‍🏭', emojiB:'🧑‍🔧', a:'Factory Worker', b:'Mechanic' },
    { cat:'💼 Jobs', emojiA:'💡', emojiB:'🚿', a:'Electrician', b:'Plumber' },
    { cat:'💼 Jobs', emojiA:'🎤', emojiB:'🎬', a:'Singer', b:'Director' },
    { cat:'💼 Jobs', emojiA:'💼', emojiB:'🏦', a:'Businessman', b:'Banker' },
    { cat:'☀️ Weather', emojiA:'🌪️', emojiB:'🌀', a:'Tornado', b:'Hurricane' },
    { cat:'☀️ Weather', emojiA:'⛈️', emojiB:'🌩️', a:'Thunderstorm', b:'Lightning' },
    { cat:'☀️ Weather', emojiA:'🌈', emojiB:'🌦️', a:'Rainbow', b:'Drizzle' },
    { cat:'☀️ Weather', emojiA:'🌤️', emojiB:'⛅', a:'Sunny', b:'Cloudy' },
    { cat:'🌳 Nature', emojiA:'🌸', emojiB:'🌺', a:'Cherry Blossom', b:'Hibiscus' },
    { cat:'🌳 Nature', emojiA:'🌵', emojiB:'🌴', a:'Cactus', b:'Palm Tree' },
    { cat:'🌳 Nature', emojiA:'🍄', emojiB:'🌿', a:'Mushroom', b:'Herb' },
    { cat:'🌳 Nature', emojiA:'🍁', emojiB:'🍂', a:'Maple Leaf', b:'Autumn Leaf' },
    { cat:'🌳 Nature', emojiA:'🌻', emojiB:'🌼', a:'Sunflower', b:'Daisy' },
    { cat:'🌳 Nature', emojiA:'🌾', emojiB:'🌱', a:'Wheat', b:'Sprout' },
    { cat:'🌳 Nature', emojiA:'🪨', emojiB:'💎', a:'Rock', b:'Gemstone' },
    { cat:'🌳 Nature', emojiA:'🔥', emojiB:'🌋', a:'Fire', b:'Volcano' },
    { cat:'🎯 Activities', emojiA:'🎾', emojiB:'🏓', a:'Tennis', b:'Table Tennis' },
    { cat:'🎯 Activities', emojiA:'⛳', emojiB:'🏒', a:'Golf', b:'Hockey' },
    { cat:'🎯 Activities', emojiA:'🏹', emojiB:'🎯', a:'Archery', b:'Darts' },
    { cat:'🎯 Activities', emojiA:'🧗', emojiB:'🏂', a:'Rock Climbing', b:'Snowboarding' },
    { cat:'🎯 Activities', emojiA:'🚴', emojiB:'🏃', a:'Cycling', b:'Running' },
    { cat:'🎯 Activities', emojiA:'🥊', emojiB:'🤼', a:'Boxing', b:'Wrestling' },
    { cat:'🎯 Activities', emojiA:'🎳', emojiB:'🎱', a:'Bowling', b:'Billiards' },
    { cat:'🎯 Activities', emojiA:'🧘', emojiB:'💃', a:'Yoga', b:'Dancing' },
    { cat:'🎯 Activities', emojiA:'🎣', emojiB:'🏕️', a:'Fishing', b:'Camping' },
    { cat:'🎯 Activities', emojiA:'🎮', emojiB:'🕹️', a:'Video Games', b:'Arcade' },
    { cat:'🎯 Activities', emojiA:'🧩', emojiB:'🎲', a:'Puzzle', b:'Board Game' },
    { cat:'🎯 Activities', emojiA:'📖', emojiB:'🎧', a:'Reading', b:'Listening to Music' },
    { cat:'🎒 Objects', emojiA:'🛋️', emojiB:'🪑', a:'Sofa', b:'Chair' },
    { cat:'🎒 Objects', emojiA:'🛏️', emojiB:'🛌', a:'Bed', b:'Hammock' },
    { cat:'🎒 Objects', emojiA:'🪟', emojiB:'🚪', a:'Window', b:'Door' },
    { cat:'🎒 Objects', emojiA:'🕯️', emojiB:'💡', a:'Candle', b:'Light Bulb' },
    { cat:'🎒 Objects', emojiA:'⏰', emojiB:'⌚', a:'Alarm Clock', b:'Wristwatch' },
    { cat:'🎒 Objects', emojiA:'📱', emojiB:'📞', a:'Smartphone', b:'Telephone' },
    { cat:'🎒 Objects', emojiA:'💻', emojiB:'🖥️', a:'Laptop', b:'Desktop Computer' },
    { cat:'🎒 Objects', emojiA:'🔑', emojiB:'🔒', a:'Key', b:'Lock' },
    { cat:'🎒 Objects', emojiA:'🧺', emojiB:'🧹', a:'Laundry Basket', b:'Broom' },
    { cat:'🎒 Objects', emojiA:'🪞', emojiB:'🖼️', a:'Mirror', b:'Picture Frame' },
    { cat:'🎒 Objects', emojiA:'🧯', emojiB:'🧰', a:'Fire Extinguisher', b:'Toolbox' },
    { cat:'🍽️ Kitchen', emojiA:'🍳', emojiB:'🥘', a:'Frying Pan', b:'Pot' },
    { cat:'🍽️ Kitchen', emojiA:'🔪', emojiB:'🥄', a:'Knife', b:'Spoon' },
    { cat:'🍽️ Kitchen', emojiA:'🧊', emojiB:'🔥', a:'Ice', b:'Stove' },
    { cat:'🍽️ Kitchen', emojiA:'🧂', emojiB:'🍯', a:'Salt', b:'Honey' },
    { cat:'🍽️ Kitchen', emojiA:'🫖', emojiB:'☕', a:'Kettle', b:'Coffee Maker' },
    { cat:'🍽️ Kitchen', emojiA:'🧁', emojiB:'🍩', a:'Cupcake', b:'Donut' },
    { cat:'🍽️ Kitchen', emojiA:'🥤', emojiB:'🧋', a:'Soda', b:'Bubble Tea' },
    { cat:'🍽️ Kitchen', emojiA:'🍽️', emojiB:'🥣', a:'Plate', b:'Bowl' },
    { cat:'📚 School', emojiA:'📓', emojiB:'📝', a:'Notebook', b:'Notepad' },
    { cat:'📚 School', emojiA:'✏️', emojiB:'🖊️', a:'Pencil', b:'Pen' },
    { cat:'📚 School', emojiA:'📐', emojiB:'📏', a:'Protractor', b:'Ruler' },
    { cat:'📚 School', emojiA:'✏️', emojiB:'📚', a:'Pencil Case', b:'Textbook' },
    { cat:'📚 School', emojiA:'🖨️', emojiB:'📠', a:'Printer', b:'Fax Machine' },
    { cat:'📚 School', emojiA:'🎓', emojiB:'📜', a:'Diploma', b:'Certificate' },
    { cat:'💻 Technology', emojiA:'🖱️', emojiB:'⌨️', a:'Trackpad', b:'Keyboard' },
    { cat:'💻 Technology', emojiA:'📷', emojiB:'🎥', a:'Webcam', b:'Video Camera' },
    { cat:'💻 Technology', emojiA:'🔋', emojiB:'🔌', a:'Battery', b:'Charger' },
    { cat:'💻 Technology', emojiA:'🎮', emojiB:'🕶️', a:'Game Controller', b:'VR Headset' },
    { cat:'💻 Technology', emojiA:'🖨️', emojiB:'📠', a:'3D Printer', b:'Scanner' },
    { cat:'💻 Technology', emojiA:'💾', emojiB:'💿', a:'Hard Drive', b:'Compact Disc' },
    { cat:'💻 Technology', emojiA:'🤖', emojiB:'🦾', a:'Android', b:'Robotic Arm' },
    { cat:'💻 Technology', emojiA:'📺', emojiB:'🖥️', a:'Television', b:'Monitor' },
    { cat:'💻 Technology', emojiA:'🔦', emojiB:'🏮', a:'Flashlight', b:'Lantern' },
    { cat:'👕 Clothing', emojiA:'👕', emojiB:'👔', a:'T-Shirt', b:'Dress Shirt' },
    { cat:'👕 Clothing', emojiA:'👖', emojiB:'🩳', a:'Jeans', b:'Shorts' },
    { cat:'👕 Clothing', emojiA:'👗', emojiB:'👘', a:'Dress', b:'Kimono' },
    { cat:'👕 Clothing', emojiA:'🧢', emojiB:'🎩', a:'Cap', b:'Top Hat' },
    { cat:'👕 Clothing', emojiA:'👟', emojiB:'🥾', a:'Sneakers', b:'Hiking Boots' },
    { cat:'👕 Clothing', emojiA:'🧤', emojiB:'🧣', a:'Gloves', b:'Scarf' },
    { cat:'👕 Clothing', emojiA:'👜', emojiB:'👛', a:'Handbag', b:'Wallet' },
    { cat:'👕 Clothing', emojiA:'👠', emojiB:'🩰', a:'High Heels', b:'Ballet Flats' },
    { cat:'👕 Clothing', emojiA:'🕶️', emojiB:'👓', a:'Sunglasses', b:'Eyeglasses' },
    { cat:'👕 Clothing', emojiA:'🧥', emojiB:'🦺', a:'Coat', b:'Vest' },
    { cat:'🎉 Holidays', emojiA:'🎄', emojiB:'🎃', a:'Christmas', b:'Halloween' },
    { cat:'🎉 Holidays', emojiA:'🎆', emojiB:'🎇', a:'Fireworks', b:'Sparklers' },
    { cat:'🎉 Holidays', emojiA:'🎁', emojiB:'🎈', a:'Present', b:'Balloon' },
    { cat:'🎉 Holidays', emojiA:'🎊', emojiB:'🎉', a:'Confetti', b:'Party Popper' },
    { cat:'🎉 Holidays', emojiA:'🕯️', emojiB:'🪔', a:'Birthday Candle', b:'Oil Lamp' },
    { cat:'🎉 Holidays', emojiA:'🥮', emojiB:'🧧', a:'Mooncake', b:'Red Envelope' },
    { cat:'🎬 Entertainment', emojiA:'🎬', emojiB:'📺', a:'Movie', b:'TV Show' },
    { cat:'🎬 Entertainment', emojiA:'🎭', emojiB:'🎪', a:'Theater', b:'Circus' },
    { cat:'🎬 Entertainment', emojiA:'🗿', emojiB:'📸', a:'Sculpture', b:'Photography' },
    { cat:'🎬 Entertainment', emojiA:'🎸', emojiB:'🎤', a:'Band', b:'Solo Singer' },
    { cat:'🎬 Entertainment', emojiA:'📖', emojiB:'📰', a:'Novel', b:'Newspaper' },
    { cat:'🎬 Entertainment', emojiA:'🎡', emojiB:'🎠', a:'Ferris Wheel', b:'Carousel' },
    { cat:'🎬 Entertainment', emojiA:'🃏', emojiB:'♟️', a:'Card Game', b:'Chess' },
    { cat:'🎬 Entertainment', emojiA:'🎩', emojiB:'🎎', a:'Magic Show', b:'Puppet Show' },
    { cat:'🎬 Entertainment', emojiA:'🦸', emojiB:'🦹', a:'Superhero', b:'Villain' },
    { cat:'🎬 Entertainment', emojiA:'👻', emojiB:'🧟', a:'Ghost', b:'Zombie' },
    { cat:'🌳 Nature', emojiA:'🐚', emojiB:'🪸', a:'Seashell', b:'Coral' },
    { cat:'🌳 Nature', emojiA:'🌊', emojiB:'🏄', a:'Wave', b:'Surfboard' },
    { cat:'🫀 Body', emojiA:'🦷', emojiB:'🦴', a:'Tooth', b:'Bone' },
    { cat:'🫀 Body', emojiA:'👁️', emojiB:'👂', a:'Eye', b:'Ear' },
    { cat:'🫀 Body', emojiA:'🧠', emojiB:'❤️', a:'Brain', b:'Heart' },
    { cat:'🫀 Body', emojiA:'🤚', emojiB:'🦶', a:'Hand', b:'Foot' },
  ],

  // ── You're In The Scene ────────────────────────────────────────────────────
  scene: [
    {
      cat: '🍕 Food & Dining',
      emoji: '🧾',
      title: 'The Birthday Bill',
      situation: "The birthday dinner is over. The bill has arrived. Nobody agrees on how to split it.",
      a: { label: 'The Birthday Person', hint: "You assumed you wouldn't pay anything. You also ordered the most expensive dish. You're watching the discussion very nervously." },
      b: { label: 'The Math Person', hint: "You have the calculator out. Everyone should pay EXACTLY what they ordered — down to the last cent. You will not round up." },
      c: { label: 'The One Who Only Had Water', hint: "You ate almost nothing. An equal split means you pay for everyone's steak. You're quietly doing the math and getting upset." },
      d: { label: 'The Waiter', hint: "You need this table for the next group. You come back every 30 seconds to ask if they're ready. Your smile is getting tighter." },
      e: { label: 'The One Who Forgot Their Wallet', hint: "This is the third dinner in a row you've 'forgotten' it. You're hoping nobody is counting. Somebody is counting." },
      f: { label: 'The Rich Friend', hint: "You could easily pay for everyone. You're staying silent just to see how long this lasts. You're enjoying it." },
    },
    {
      cat: '🍕 Food & Dining',
      emoji: '🕵️',
      title: 'The Midnight Snack Mystery',
      situation: "Someone ate the leftovers that clearly had a name written on them. The kitchen meeting starts now.",
      a: { label: 'The Victim', hint: "Your labeled food is gone. You called this meeting. You have a list of suspects and you're not afraid to use it." },
      b: { label: 'The Guilty One', hint: "You ate it at 2am. It was delicious. You are acting more shocked than anyone else in the room." },
      c: { label: 'The Detective Roommate', hint: "You've been waiting your whole life for a mystery like this. You ask everyone very serious questions and take notes." },
      d: { label: 'The Witness', hint: "You know exactly who did it. You're enjoying the power far too much to reveal it yet." },
      e: { label: 'The New Roommate', hint: "You moved in yesterday. You don't know anyone's name. You think this meeting is about the rent." },
      f: { label: 'The One Ordering Pizza', hint: "You think this whole meeting is ridiculous. You are loudly ordering a pizza on the phone in the middle of it." },
    },
    {
      cat: '🎉 Social',
      emoji: '🎤',
      title: 'The Karaoke Hostage',
      situation: "One person grabbed the microphone an hour ago and will not give it back.",
      a: { label: 'The Mic Hogger', hint: "You're on song number six. You believe everyone loves it. You've already queued five more." },
      b: { label: 'The Next Singer', hint: "Your song has been 'next' for an hour. You stand up ready every time a song ends. Every time, you sit back down." },
      c: { label: 'The Birthday Person', hint: "This is YOUR party and you haven't sung once. You are being very polite. You will not be polite much longer." },
      d: { label: 'The Fake Fan', hint: "You cheer for A so loudly that A thinks the whole room wants more. You just love the chaos." },
      e: { label: 'The Staff Member', hint: "The room's time ended 20 minutes ago. You knock, open the door, and get completely ignored. Every single time." },
      f: { label: 'The One Who Doesn\'t Sing', hint: "You were dragged here against your will. Someone keeps trying to hand YOU the second microphone." },
    },
    {
      cat: '🎉 Social',
      emoji: '📸',
      title: 'The Impossible Group Photo',
      situation: "A big reunion is ending. All they need is ONE good group photo. It is not going well.",
      a: { label: 'The Photographer', hint: "You're holding three phones and getting instructions from everyone at once. Nobody listens to yours." },
      b: { label: 'The Blinker', hint: "You have blinked in every photo ever taken of you. Everyone knows this about you. The pressure is enormous." },
      c: { label: 'The Perfectionist', hint: "Photo number 47 was almost perfect — except your hair. One more. Just one more. Forever." },
      d: { label: 'The Helpful Stranger', hint: "You offered to take the photo so everyone could be in it. You have no idea how this phone works. You may be filming a video." },
      e: { label: 'The One in a Hurry', hint: "Your taxi arrives in four minutes. You announce this after every single photo." },
      f: { label: 'The Photobomber', hint: "You don't know any of these people. You are in every photo anyway. You have great poses." },
    },
    {
      cat: '💼 Work & School',
      emoji: '📚',
      title: 'The Night Before the Deadline',
      situation: "The group project is due tomorrow at 9am. This is the first full meeting. It shows.",
      a: { label: 'The Only One Who Worked', hint: "You did 90% of the project alone. You're deciding whether to say it now — or tomorrow, in front of the teacher." },
      b: { label: 'The Excuse Master', hint: "You've had a different excuse every week. Tonight's excuse is your finest work yet." },
      c: { label: 'The Ghost', hint: "This is the first meeting you've ever attended. You're acting like you've been here the whole time." },
      d: { label: 'The Idea Person', hint: "You just had a HUGE new idea for the project. It's due tomorrow. You want to start over from zero." },
      e: { label: 'The Note Taker', hint: "You write everything down beautifully, in three colours. You have never done anything else." },
      f: { label: 'The Optimist', hint: "You truly believe the team can finish everything tonight. You have believed this every night for a month." },
    },
    {
      cat: '💼 Work & School',
      emoji: '🌡️',
      title: 'The Thermostat War',
      situation: "The office has one thermostat. It has divided the team into two armies.",
      a: { label: 'The Freezing One', hint: "You wear a winter coat at your desk. You turn the heat up every time you walk past the thermostat. You trust no one." },
      b: { label: 'The Melting One', hint: "You are dying of heat. You turn it back down every time. You and A have never once discussed this directly." },
      c: { label: 'The Office Manager', hint: "Today you installed a locked plastic box over the thermostat. You are very proud. Everyone is furious." },
      d: { label: 'The Peacekeeper', hint: "You keep suggesting compromises that nobody wants. You are now more stressed than anyone in the office." },
      e: { label: 'The Prepared One', hint: "You have your own fan AND your own heater under your desk. You share neither. You still have strong opinions." },
      f: { label: 'The New Employee', hint: "It's your first day. You just want to know where your chair is. Both armies are trying to recruit you." },
    },
    {
      cat: '✈️ Travel',
      emoji: '🏨',
      title: 'The Double-Booked Room',
      situation: "Two exhausted travellers arrive at the hotel — and the system gave them both the same room.",
      a: { label: 'The Tired Parent', hint: "You've travelled 14 hours with two kids. That room is yours. You are not moving from this front desk." },
      b: { label: 'The Organized Guest', hint: "You booked eight months ago. You have printed proof. You brought a folder. You are opening the folder now." },
      c: { label: 'The New Receptionist', hint: "It's your second day. The computer says the room belongs to… both of them. The manager is not answering the phone." },
      d: { label: 'The Kid', hint: "You just want to go to the pool. You ask about the pool every 30 seconds — to anyone who makes eye contact." },
      e: { label: 'The Manager on Vacation', hint: "You finally answer the phone — from a beach. Your solutions help nobody. The music behind you is very loud." },
      f: { label: 'The Guest Already in the Room', hint: "Surprise — you're already IN that room. You come down in a bathrobe to complain about all the noise." },
    },
    {
      cat: '✈️ Travel',
      emoji: '🛍️',
      title: 'The Souvenir Negotiation',
      situation: "A tourist wants the lamp. The shop owner wants triple the price. Nobody in this market is innocent.",
      a: { label: 'The Tourist', hint: "You offered half price because a travel blog told you to. You have no idea what you are doing. You really want the lamp." },
      b: { label: 'The Shop Owner', hint: "You tripled the price the moment A walked in. You act deeply insulted by every offer. This is your favourite game." },
      c: { label: 'The Travel Partner', hint: "You keep whispering 'just walk away, they'll follow us' — the blog said so. You are no longer sure the blog was right." },
      d: { label: 'The Local Friend', hint: "You're translating for both sides — but you soften every insult. The negotiation now makes no sense to anyone." },
      e: { label: 'The Rival Shopkeeper', hint: "You shout better offers from across the street. You don't even sell lamps." },
      f: { label: 'The Tour Guide', hint: "The bus leaves in five minutes. You are physically dragging A away in the middle of the deal." },
    },
    {
      cat: '☕ Everyday',
      emoji: '🛗',
      title: 'Stuck in the Elevator',
      situation: "The elevator stopped between floors. Six strangers. No idea how long this will take.",
      a: { label: 'The Calm One', hint: "You are staying calm. Very calm. TOO calm. You have told everyone how calm you are nine times now." },
      b: { label: 'The Elevator Expert', hint: "You watched a documentary about elevators once. You are now the self-appointed leader of this group." },
      c: { label: 'The Loud Caller', hint: "You're describing everything on the phone to a friend, loudly. You have full signal. You are not sharing your phone." },
      d: { label: 'The Security Voice', hint: "You're on the speaker. You keep saying 'help is on the way' with absolutely no details. You are clearly eating something crunchy." },
      e: { label: 'The One Late for a Date', hint: "Your first date is waiting at the restaurant upstairs. You keep writing and deleting the same text message." },
      f: { label: 'The Delivery Person', hint: "The food you're delivering is for the restaurant upstairs. It smells incredible. Everyone is staring at the bag." },
    },
    {
      cat: '☕ Everyday',
      emoji: '🚗',
      title: 'The Parking Spot Standoff',
      situation: "One parking spot. Two cars. Neither driver is willing to move. The supermarket is watching.",
      a: { label: 'The First Driver', hint: "You saw the spot first and your signal was on. That makes it legally yours — you think. You're not actually sure." },
      b: { label: 'The Other Driver', hint: "You were closer and you're already halfway in. You are not backing out. You have all day. You brought snacks." },
      c: { label: 'The Passenger', hint: "You're in B's car. You know B is wrong. You are too embarrassed to say it. You keep sliding lower in your seat." },
      d: { label: 'The Parking Attendant', hint: "There is an empty spot ten meters away. You keep pointing at it. Nobody has looked at you once." },
      e: { label: 'The Trapped Shopper', hint: "Your car is parked between the two cars. You just want to load your groceries and leave. You are now a hostage." },
      f: { label: 'The Driving Instructor', hint: "You're in the car behind with a student driver, narrating everything as a live lesson on exactly what NOT to do." },
    },
  ],

  // ── Forbidden Words ──────────────────────────────────────────────────────
  // Simple, everyday words that could naturally slip into conversation —
  // easy to say, easy to accidentally blurt out.
  forbidden: [
    { word: 'Coffee',    emoji: '☕' },
    { word: 'Weekend',   emoji: '📅' },
    { word: 'Tired',     emoji: '😴' },
    { word: 'Hungry',    emoji: '🍽️' },
    { word: 'Rain',      emoji: '🌧️' },
    { word: 'Money',     emoji: '💰' },
    { word: 'Phone',     emoji: '📱' },
    { word: 'Music',     emoji: '🎵' },
    { word: 'Movie',     emoji: '🎬' },
    { word: 'Friend',    emoji: '👫' },
    { word: 'Family',    emoji: '👨‍👩‍👧' },
    { word: 'School',    emoji: '🏫' },
    { word: 'Work',      emoji: '💼' },
    { word: 'Home',      emoji: '🏠' },
    { word: 'Water',     emoji: '💧' },
    { word: 'Sleep',     emoji: '🛌' },
    { word: 'Happy',     emoji: '😄' },
    { word: 'Busy',      emoji: '⏳' },
    { word: 'Birthday',  emoji: '🎂' },
    { word: 'Travel',    emoji: '✈️' },
    { word: 'Photo',     emoji: '📷' },
    { word: 'Internet',  emoji: '🌐' },
    { word: 'Computer',  emoji: '💻' },
    { word: 'Weather',   emoji: '☁️' },
    { word: 'Breakfast', emoji: '🍳' },
    { word: 'Lunch',     emoji: '🥪' },
    { word: 'Dinner',    emoji: '🍛' },
    { word: 'Summer',    emoji: '☀️' },
    { word: 'Winter',    emoji: '❄️' },
    { word: 'Morning',   emoji: '🌅' },
    { word: 'Night',     emoji: '🌙' },
    { word: 'Traffic',   emoji: '🚗' },
    { word: 'Exercise',  emoji: '🏃' },
    { word: 'Shopping',  emoji: '🛍️' },
    { word: 'Vacation',  emoji: '🏖️' },
    { word: 'Game',      emoji: '🎮' },
    { word: 'Book',      emoji: '📖' },
    { word: 'Dog',       emoji: '🐶' },
    { word: 'Cat',       emoji: '🐱' },
    { word: 'Party',     emoji: '🎉' },
    { word: 'Bus',       emoji: '🚌' },
    { word: 'Train',     emoji: '🚆' },
    { word: 'Restaurant',emoji: '🍴' },
    { word: 'TV',        emoji: '📺' },
    { word: 'Email',     emoji: '📧' },
    { word: 'Meeting',   emoji: '🤝' },
    { word: 'Homework',  emoji: '📝' },
    { word: 'Doctor',    emoji: '🩺' },
    { word: 'Hospital',  emoji: '🏥' },
    { word: 'Baby',      emoji: '👶' },
    { word: 'Wedding',   emoji: '💍' },
    { word: 'Gym',       emoji: '🏋️' },
    { word: 'Shower',    emoji: '🚿' },
    { word: 'Wallet',    emoji: '👛' },
    { word: 'Umbrella',  emoji: '☂️' },
    { word: 'Snow',      emoji: '☃️' },
    { word: 'Mountain',  emoji: '⛰️' },
    { word: 'Concert',   emoji: '🎤' },
    { word: 'Airport',   emoji: '🛫' },
    { word: 'Present',   emoji: '🎁' },
    { word: 'Pizza',        emoji: '🍕' },
    { word: 'Burger',       emoji: '🍔' },
    { word: 'Sandwich',     emoji: '🥙' },
    { word: 'Salad',        emoji: '🥗' },
    { word: 'Soup',         emoji: '🍲' },
    { word: 'Noodles',      emoji: '🍜' },
    { word: 'Rice',         emoji: '🍚' },
    { word: 'Bread',        emoji: '🍞' },
    { word: 'Cheese',       emoji: '🧀' },
    { word: 'Chocolate',    emoji: '🍫' },
    { word: 'Candy',        emoji: '🍬' },
    { word: 'Cookie',       emoji: '🍪' },
    { word: 'Cake',         emoji: '🍰' },
    { word: 'Fruit',        emoji: '🍇' },
    { word: 'Vegetable',    emoji: '🥦' },
    { word: 'Apple',        emoji: '🍎' },
    { word: 'Banana',       emoji: '🍌' },
    { word: 'Orange',       emoji: '🍊' },
    { word: 'Milk',         emoji: '🥛' },
    { word: 'Juice',        emoji: '🧃' },
    { word: 'Tea',          emoji: '🍵' },
    { word: 'Beer',         emoji: '🍺' },
    { word: 'Wine',         emoji: '🍷' },
    { word: 'Snack',        emoji: '🍿' },
    { word: 'Egg',          emoji: '🥚' },
    { word: 'Chicken',      emoji: '🍗' },
    { word: 'Fish',         emoji: '🐟' },
    { word: 'Meat',         emoji: '🥩' },
    { word: 'Sugar',        emoji: '🥄' },
    { word: 'Salt',         emoji: '🧂' },
    { word: 'Beach',        emoji: '🏖️' },
    { word: 'Park',         emoji: '🌳' },
    { word: 'Zoo',          emoji: '🦁' },
    { word: 'Museum',       emoji: '🏛️' },
    { word: 'Library',      emoji: '📚' },
    { word: 'Office',       emoji: '🏢' },
    { word: 'Kitchen',      emoji: '🥘' },
    { word: 'Bedroom',      emoji: '🛏️' },
    { word: 'Bathroom',     emoji: '🚽' },
    { word: 'Garden',       emoji: '🌷' },
    { word: 'Church',       emoji: '⛪' },
    { word: 'Bank',         emoji: '🏦' },
    { word: 'Supermarket',  emoji: '🛒' },
    { word: 'Mall',         emoji: '🏬' },
    { word: 'Bakery',       emoji: '🥐' },
    { word: 'Pharmacy',     emoji: '💊' },
    { word: 'Farm',         emoji: '🚜' },
    { word: 'Forest',       emoji: '🌲' },
    { word: 'River',        emoji: '🏞️' },
    { word: 'Island',       emoji: '🏝️' },
    { word: 'Ocean',        emoji: '🌊' },
    { word: 'Sun',          emoji: '🌞' },
    { word: 'Moon',         emoji: '🌛' },
    { word: 'Star',         emoji: '⭐' },
    { word: 'Cloud',        emoji: '🌥️' },
    { word: 'Wind',         emoji: '🌬️' },
    { word: 'Storm',        emoji: '⛈️' },
    { word: 'Thunder',      emoji: '⚡' },
    { word: 'Fog',          emoji: '🌫️' },
    { word: 'Ice',          emoji: '🧊' },
    { word: 'Fire',         emoji: '🔥' },
    { word: 'Sand',         emoji: '🏜️' },
    { word: 'Rock',         emoji: '🪨' },
    { word: 'Tree',         emoji: '🌴' },
    { word: 'Flower',       emoji: '🌸' },
    { word: 'Car',          emoji: '🚙' },
    { word: 'Bike',         emoji: '🚲' },
    { word: 'Taxi',         emoji: '🚕' },
    { word: 'Ship',         emoji: '🚢' },
    { word: 'Boat',         emoji: '⛵' },
    { word: 'Subway',       emoji: '🚇' },
    { word: 'Motorcycle',   emoji: '🏍️' },
    { word: 'Truck',        emoji: '🚚' },
    { word: 'Laptop',       emoji: '🖥️' },
    { word: 'Headphones',   emoji: '🎧' },
    { word: 'Charger',      emoji: '🔌' },
    { word: 'Battery',      emoji: '🔋' },
    { word: 'Password',     emoji: '🔑' },
    { word: 'WiFi',         emoji: '📶' },
    { word: 'App',          emoji: '📲' },
    { word: 'Website',      emoji: '🖱️' },
    { word: 'Video',        emoji: '🎥' },
    { word: 'Chair',        emoji: '🪑' },
    { word: 'Bed',          emoji: '🛏️' },
    { word: 'Sofa',         emoji: '🛋️' },
    { word: 'Mirror',       emoji: '🪞' },
    { word: 'Window',       emoji: '🪟' },
    { word: 'Door',         emoji: '🚪' },
    { word: 'Key',          emoji: '🗝️' },
    { word: 'Lamp',         emoji: '💡' },
    { word: 'Clock',        emoji: '⏰' },
    { word: 'Blanket',      emoji: '🧣' },
    { word: 'Pillow',       emoji: '🛌' },
    { word: 'Towel',        emoji: '🧻' },
    { word: 'Soap',         emoji: '🧼' },
    { word: 'Toothbrush',   emoji: '🪥' },
    { word: 'Fridge',       emoji: '🧊' },
    { word: 'Headache',     emoji: '🤕' },
    { word: 'Fever',        emoji: '🤒' },
    { word: 'Cough',        emoji: '😷' },
    { word: 'Medicine',     emoji: '💊' },
    { word: 'Vitamin',      emoji: '💊' },
    { word: 'Diet',         emoji: '🥗' },
    { word: 'Hair',         emoji: '💇' },
    { word: 'Smile',        emoji: '😊' },
    { word: 'Tears',        emoji: '😢' },
    { word: 'Today',        emoji: '📆' },
    { word: 'Tomorrow',     emoji: '🗓️' },
    { word: 'Yesterday',    emoji: '📅' },
    { word: 'Holiday',      emoji: '🎊' },
    { word: 'Schedule',     emoji: '🗓️' },
    { word: 'Deadline',     emoji: '⏰' },
    { word: 'Interview',    emoji: '🎙️' },
    { word: 'Salary',       emoji: '💵' },
    { word: 'Boss',         emoji: '👔' },
    { word: 'Customer',     emoji: '🛍️' },
    { word: 'Client',       emoji: '🤝' },
    { word: 'Project',      emoji: '📊' },
    { word: 'Report',       emoji: '📄' },
    { word: 'Presentation', emoji: '📊' },
    { word: 'Exam',         emoji: '📝' },
    { word: 'Grade',        emoji: '🎓' },
    { word: 'Diploma',      emoji: '🎓' },
    { word: 'Degree',       emoji: '🎓' },
    { word: 'Teacher',      emoji: '👩‍🏫' },
    { word: 'Student',      emoji: '🎒' },
    { word: 'Shirt',        emoji: '👕' },
    { word: 'Shoes',        emoji: '👟' },
    { word: 'Jacket',       emoji: '🧥' },
    { word: 'Hat',          emoji: '🧢' },
    { word: 'Socks',        emoji: '🧦' },
    { word: 'Jeans',        emoji: '👖' },
    { word: 'Dress',        emoji: '👗' },
    { word: 'Sweater',      emoji: '🧶' },
    { word: 'Glasses',      emoji: '👓' },
    { word: 'Watch',        emoji: '⌚' },
    { word: 'Secret',       emoji: '🤫' },
    { word: 'Idea',         emoji: '💡' },
    { word: 'Dream',        emoji: '💭' },
    { word: 'Habit',        emoji: '🔁' },
  ],

  // ── Dare Conquest（board-game dares — silly, spicier interactive prompts, {player} is filled
  //    with a random other player; every prompt carries a `seconds` time limit）──
  conquest: [
    { cat: '📖 Hero Story', text: 'Tell a 15-second made-up story where {player} is the hero who saves the day.', seconds: 15 },
    { cat: '🎁 Perfect Gift', text: "Tell {player} what gift you'd get them if you had unlimited money, and explain why, in 15 seconds.", seconds: 15 },
    { cat: '💖 Real Compliment', text: 'Give {player} a real, kind compliment in the next 10 seconds.', seconds: 10 },
    { cat: '🔥 Roast', text: 'Tease {player} in a funny way for 15 seconds, then let them tease you right back.', seconds: 15 },
    { cat: '🙏 Big Apology', text: 'Say sorry to {player} in a very dramatic way, for something you made up, in 15 seconds.', seconds: 15 },
    { cat: '💔 Dramatic Breakup', text: "Break up with {player} in a big dramatic way within 15 seconds, even though you were never dating.", seconds: 15 },
    { cat: '💍 Surprise Proposal', text: 'Get on one knee and ask {player} to marry you within 15 seconds.', seconds: 15 },
    { cat: '⚖️ Win Debate', text: 'Explain for 15 seconds why you should win this game more than {player}.', seconds: 15 },
    { cat: '🎯 Habit Callout', text: "Tell {player} one small habit of theirs that bothers you, in a funny way, in 10 seconds.", seconds: 10 },
    { cat: '🎙️ TV Interview', text: 'Interview {player} like on a TV show for 20 seconds — ask one fun question and react big to their answer.', seconds: 20 },
    { cat: '🧦 Silly Trade', text: 'Try to trade something silly with {player}, like your sock for their pen, for 20 seconds.', seconds: 20 },
    { cat: '🎭 Copy Them', text: 'Copy the way {player} talks for 15 seconds.', seconds: 15 },
    { cat: '🥊 Trash Talk', text: 'Talk big and act like you and {player} are about to fight for a big prize, for 10 seconds.', seconds: 10 },
    { cat: '🕵️ Detective Act', text: 'Pretend {player} did something silly and wrong, and question them like a detective, in 15 seconds.', seconds: 15 },
    { cat: '💘 Pickup Line', text: 'Use your silliest pickup line on {player} — you have 10 seconds.', seconds: 10 },
    { cat: '🎂 Birthday Song', text: 'Sing "Happy Birthday" to {player} like it\'s really their birthday — you have 15 seconds.', seconds: 15 },
    { cat: '🏆 Award Speech', text: "Give {player} a funny made-up award and explain why they earned it, in 15 seconds.", seconds: 15 },
    { cat: '🗳️ Elimination Vote', text: 'If one player had to leave this game right now, who would you pick? Say why in 15 seconds.', seconds: 15 },
    { cat: '📊 Trust Ranking', text: 'Rank every other player from "trust least" to "trust most," out loud, in 20 seconds.', seconds: 20 },
    { cat: '😤 Fake Fight', text: 'Start a pretend argument with {player} about something small, like who ate the last snack — keep it going for 20 seconds.', seconds: 20 },
    { cat: '🥸 Full Copycat', text: "Copy the way {player} stands, talks, and one thing they often say, for 10 seconds.", seconds: 10 },
    { cat: '🎬 Origin Story', text: 'Make up a funny, dramatic story about why {player} made you upset, for 15 seconds.', seconds: 15 },
    { cat: '🫵 Straight Talk', text: 'Tell {player}, right to their face, one thing you two don\'t agree on — in a fun way, in 15 seconds.', seconds: 15 },
    { cat: '💬 Whisper', text: 'Whisper one nice compliment to {player} within 10 seconds.', seconds: 10 },
    { cat: '💌 Secret Note', text: 'Write a short secret compliment note to {player} and read it out loud, within 10 seconds.', seconds: 10 },
    { cat: '🥹 Long-Lost Friend', text: "Greet {player} like you haven't seen each other in 20 years, for 10 seconds straight, even though you just talked minutes ago.", seconds: 10 },
    { cat: '🫡 Honest Feedback', text: "Give {player} one honest piece of feedback about how they're playing the game, in 15 seconds.", seconds: 15 },
    { cat: '🥂 Wedding Toast', text: 'Give {player} a short, warm toast like you\'re at their wedding — you have 15 seconds.', seconds: 15 },
    { cat: '💌 Confession', text: "Tell {player} how you really feel about them (real or made up!), in 15 seconds.", seconds: 15 },
    { cat: '🏷️ New Nickname', text: 'Give {player} a brand-new nickname right now, and explain why it fits, in 10 seconds.', seconds: 10 },
    { cat: '🤝 Alliance Pitch', text: 'Try to convince {player} to team up with you for the rest of the game, in 15 seconds.', seconds: 15 },
    { cat: '🫡 Loyalty Pledge', text: 'Promise {player} your loyalty for the rest of the game, in the most dramatic way you can, in 10 seconds.', seconds: 10 },
    { cat: '🫣 First Impression', text: 'Tell {player}, right now, what you honestly thought of them the first time you met, in 15 seconds.', seconds: 15 },
    { cat: '👀 Staring Contest', text: 'Have a staring contest with {player} for 10 seconds without laughing.', seconds: 10 },
    { cat: '🤝 Secret Handshake', text: 'Make up a silly secret handshake with {player} and do it together, in 15 seconds.', seconds: 15 },
    { cat: '🎉 Congratulations', text: 'Congratulate {player} like they just won a huge prize, even though they didn\'t, in 10 seconds.', seconds: 10 },
    { cat: '📺 Sales Pitch', text: 'Try to sell {player} something silly, like your left shoe, in 15 seconds.', seconds: 15 },
    { cat: '🔮 Fortune Teller', text: 'Tell {player} a made-up, funny prediction about their future, in 15 seconds.', seconds: 15 },
    { cat: '🙌 Thank You Speech', text: 'Thank {player} for something they never actually did, in a dramatic way, in 10 seconds.', seconds: 10 },
    { cat: '🏁 Rival Trash Talk', text: 'Talk trash to {player} like you\'re both about to race each other, for 10 seconds.', seconds: 10 },
    { cat: '💖 Compliment Battle', text: 'Give {player} a compliment, then challenge them to top it with one for you, in 15 seconds.', seconds: 15 },
    { cat: '📰 Fun Fact', text: 'Tell the group one made-up, silly fun fact about {player}, in 15 seconds.', seconds: 15 },
    { cat: '🎉 Personal Cheer', text: 'Do a 10-second cheer just for {player}.', seconds: 10 },
    { cat: '🍕 Guess Their Favorite', text: "Guess {player}'s favorite food out loud, then ask if you're right, in 10 seconds.", seconds: 10 },
    { cat: '🎤 Duet', text: 'Sing one line of a song to {player}, then have them sing the next line back, in 15 seconds.', seconds: 15 },
    { cat: '🪞 Mirror Game', text: "Copy {player}'s exact movements for 10 seconds like a mirror.", seconds: 10 },
    { cat: '🕊️ Peace Treaty', text: 'Make peace with {player} in an overly dramatic speech, even though you were never fighting, in 15 seconds.', seconds: 15 },
    { cat: '⚖️ Silly Debate', text: 'Pick a silly topic and argue about it with {player} for 15 seconds.', seconds: 15 },
    { cat: '👋 Farewell Speech', text: 'Give {player} a dramatic goodbye speech, like you\'re leaving forever, in 15 seconds.', seconds: 15 },
    { cat: '🔮 Game Prediction', text: 'Tell {player}, to their face, whether you think they\'ll win or lose this game, and why, in 15 seconds.', seconds: 15 },
  ],

  // ── Dare Conquest — Truths, used only when the current player picks "Truth" in the
  //    Truth or Dare choice screen; no timer, just an honest answer out loud. All personal
  //    disclosure questions about the player themselves (kept mild, nothing too extreme) ──
  conquestTruth: [
    { cat: '🤥 White Lie', text: "What's a small lie you told someone this week?", seconds: 15 },
    { cat: '🔍 Search History', text: "What's a strange thing you searched online recently?", seconds: 15 },
    { cat: '😨 Irrational Fear', text: "What's a fear you have that doesn't really make sense?", seconds: 20 },
    { cat: '👶 Childhood Trouble', text: "What's the biggest trouble you got into as a kid?", seconds: 20 },
    { cat: '🎭 Hidden Talent', text: "What's a talent you have that almost nobody here knows about?", seconds: 15 },
    { cat: '😬 Cringe Memory', text: "What's the most embarrassing thing you've done to impress someone?", seconds: 20 },
    { cat: '🎯 Secret Pet Peeve', text: "What's something small that bothers you, but you never tell people?", seconds: 15 },
    { cat: '📱 Last Text', text: 'What was the last text message you sent, word for word?', seconds: 10 },
    { cat: '🃏 Fake It', text: "What's something you pretend to understand but really don't?", seconds: 15 },
    { cat: '🍕 Weird Combo', text: "What's a food combination you love that other people think is strange?", seconds: 15 },
    { cat: '😏 Petty Moment', text: "What's the smallest, silliest thing you've done to get back at someone?", seconds: 20 },
    { cat: '💬 Most-Used Emoji', text: "What's your most-used emoji, and why do you like it?", seconds: 10 },
    { cat: '📏 Rule You Break', text: "What's a small rule you break often?", seconds: 15 },
    { cat: '🏠 Home Alone', text: "What's something a little weird you do when you're home alone?", seconds: 15 },
    { cat: '🙄 Compliment Fishing', text: "What's a compliment you secretly want people to give you?", seconds: 15 },
    { cat: '😳 Most Embarrassing Moment', text: "What's the most embarrassing thing that's happened to you in public?", seconds: 20 },
    { cat: '🎬 Guilty Show', text: "What's a show or movie you love but feel embarrassed to admit?", seconds: 15 },
    { cat: '💭 Overthought It', text: "What's a small thing you're still thinking about from years ago?", seconds: 20 },
    { cat: '🍿 Messiest Moment', text: "What's the messiest situation you've ever caused by accident?", seconds: 20 },
    { cat: '💸 Money Truth', text: "What's the silliest thing you've ever spent money on?", seconds: 15 },
    { cat: '📵 Ghosting', text: "Have you ever suddenly stopped replying to someone? What happened?", seconds: 20 },
    { cat: '🫥 Fake Friendly', text: "Have you ever pretended to like someone more than you really did?", seconds: 15 },
    { cat: '🥶 Cold Take', text: "What's something everyone else seems to love that you just don't understand?", seconds: 15 },
    { cat: '🫦 Crush Confession', text: "Have you ever had a crush on a friend who had no idea?", seconds: 15 },
    { cat: '🧟 Toxic Trait', text: "What's a bad habit you have in relationships that you haven't fixed?", seconds: 20 },
    { cat: '🫨 Overreaction', text: "What's the smallest thing that's ever made you really angry?", seconds: 15 },
    { cat: '🎢 Regret', text: "What's a decision you made that you still regret?", seconds: 20 },
    { cat: '🫢 Caught Red-Handed', text: "What's something you did that you never got caught for — until now?", seconds: 20 },
    { cat: '🎒 School Days', text: "What's the funniest thing that happened to you in school?", seconds: 20 },
    { cat: '🚗 Road Trip Mishap', text: "What's the worst thing that happened to you on a trip?", seconds: 20 },
    { cat: '🎁 Bad Gift', text: "What's the worst gift you've ever received, and did you pretend to like it?", seconds: 15 },
    { cat: '🥤 First Job', text: "What's the strangest thing that happened at your first job?", seconds: 20 },
    { cat: '📸 Old Photo', text: "What's an old photo of you that you hope nobody ever finds?", seconds: 15 },
    { cat: '🎮 Game Rage', text: "What's a game you've gotten way too upset about while playing?", seconds: 15 },
    { cat: '🐾 Pet Story', text: "What's the funniest thing a pet of yours has ever done?", seconds: 20 },
    { cat: '🍳 Kitchen Fail', text: "What's the worst thing you've ever cooked or burned?", seconds: 15 },
    { cat: '😅 Guilty Pleasure Song', text: "What's a song you love but feel embarrassed about?", seconds: 15 },
    { cat: '🫣 First Impression', text: "What did you honestly think about {player} the first time you met them?", seconds: 15 },
    { cat: '🤝 Most Trusted', text: "Out of everyone here, who would you trust the most with a secret? Why?", seconds: 15 },
    { cat: '🎪 Drama Magnet', text: "Who in this room seems most likely to start drama by accident? Why them?", seconds: 20 },
    { cat: '🤐 Untold Secret', text: "What's a secret about {player} that you could tell them right now?", seconds: 20 },
    { cat: '🥊 Least Wanted Rival', text: "Who here would you least want to compete against, honestly?", seconds: 15 },
    { cat: '🫡 Honest Feedback', text: "What's one honest thing you'd tell {player} if they asked for feedback?", seconds: 20 },
    { cat: '🎯 Called It', text: "Who do you think will be the first to lose in this game? Why?", seconds: 15 },
    { cat: '🤑 Green With Envy', text: "Who are you a little jealous of in this room right now?", seconds: 15 },
    { cat: '🧊 Hardest to Read', text: "Who in this room is the hardest person to understand?", seconds: 15 },
    { cat: '🫶 Biggest Heart', text: "Who in this room do you think is the kindest person? Why?", seconds: 15 },
    { cat: '🔎 Self Search', text: "What's the last thing you searched about yourself online?", seconds: 15 },
    { cat: '🚫 Bad Habit', text: "What's a bad habit you've been trying to quit?", seconds: 15 },
    { cat: '😅 Awkward Hangout', text: "What's the most awkward date or hangout you've ever been on?", seconds: 20 },
  ],

  // ── Secret Rule（每人抽到一條只有自己知道的說話規則，聊天時要一直遵守，
  //    最後大家互相猜對方的規則是什麼。全部採「關係型」：偷偷把在場所有人
  //    當成某一種對象來講話，一條規則就會改變整個人的語氣、用詞與稱呼，
  //    但不會像唱歌/拼字那樣一開口就穿幫。刻意用簡單字彙，方便語音即時反應）──
  secretRule: [
    { emoji: '👩‍🏫', rule: 'Talk to everyone like they are your students.',      example: '"Good question. Let me explain it."' },
    { emoji: '🛍️', rule: 'Talk to everyone like they are your customers.',     example: '"Of course! Happy to help with that."' },
    { emoji: '🙇', rule: 'Talk to everyone like they are much older than you.', example: '"That is very kind of you to say."' },
    { emoji: '🧒', rule: 'Talk to everyone like they are much younger than you.', example: '"Nice job! That was a smart idea."' },
    { emoji: '🎉', rule: 'Talk to everyone like they are old friends.',         example: '"Remember when we used to do that?"' },
    { emoji: '👋', rule: 'Talk to everyone like you just met them.',            example: '"Oh really? So what do you do?"' },
    { emoji: '💼', rule: 'Talk to everyone like they are your boss.',           example: '"Sure, I can take care of that."' },
    { emoji: '📋', rule: 'Talk to everyone like they work for you.',            example: '"Let me know how that is going."' },
    { emoji: '🎤', rule: 'Talk to everyone like they are a big audience.',      example: '"Everybody, you will love this one."' },
    { emoji: '🩺', rule: 'Talk to everyone like they are your patients.',       example: '"How are you feeling about that?"' },
    { emoji: '🕵️', rule: 'Talk to everyone like they are hiding something.',    example: '"Interesting... and what happened next?"' },
    { emoji: '⭐', rule: 'Talk to everyone like they are famous.',              example: '"Wow, it is amazing to hear that from you."' },
    { emoji: '🏠', rule: 'Talk to everyone like they are your family.',         example: '"You always say that. Come on."' },
    { emoji: '🧳', rule: 'Talk to everyone like they are visiting your city.',  example: '"You should try the place near the station."' },
    { emoji: '🏡', rule: 'Talk to everyone like they are your neighbors.',      example: '"I saw you outside the other day."' },
    { emoji: '🐣', rule: 'Talk to everyone like it is their first day here.',   example: '"Do not worry, everyone feels that way."' },
  ],

  // ── Secret Rule — 主持人可隨機抽的聊天主題，讓大家有話題可以聊 ──
  secretRuleTopics: [
    'What did you do last weekend?',
    'What is your dream job?',
    'What is the best meal you have ever had?',
    'Where would you travel if the trip was free?',
    'What is your favorite way to relax?',
    'Which app do you use the most?',
    'What is a skill you want to learn?',
    'Cats or dogs — and why?',
    'What is the best gift you have ever received?',
    'What does your morning routine look like?',
    'What was your favorite subject in school?',
    'What is something you are really bad at?',
    'What is your favorite season, and why?',
    'What was the last movie or show you watched?',
    'What would you do with one extra free day?',
    'What food would you never eat again?',
    'Who is someone you look up to?',
    'What is your favorite childhood memory?',
    'Big city or countryside — where would you live?',
    'What is a small thing that makes you happy?',
    'What is the best advice you have ever received?',
    'What do you like to spend money on?',
    'What is your favorite holiday of the year?',
    'What is a habit you want to change?',
    'If you could meet anyone, who would it be?',
    'What kind of music do you listen to?',
    'What is the hardest part of learning English?',
    'What did you want to be when you were a kid?',
    'What does your perfect weekend look like?',
    'What is something new you tried this year?',
  ],
};
