/* Original, short English prompts for the optional Crazy Talk mode.
 * Lines are ready to say. Tasks give one clear, immediate spoken action.
 * No physical dares or real accusations. The public pool is not a secret;
 * only each saved assignment is private. Keep the original first-60 line IDs.
 */
var TALK_CRAZY = (() => {
  'use strict';
  const lines = [
    'I\'m in love with my cup.',
    'I love Indian accents.',
    'I like the smell of my feet.',
    'I want to marry my pillow.',
    'My belly just said hello.',
    'I am secretly three chickens.',
    'My left foot wants a divorce.',
    'My cup understands me.',
    'I kissed my sandwich goodbye.',
    'My eyebrows are judging you.',
    'I miss my past life as a chicken.',
    'My knees are older than me.',
    'My socks deserve a love song.',
    'I am too handsome to wash dishes.',
    'My armpits have formed a band.',
    'I think my feet are flirting.',
    'I eat noodles with my serious face.',
    'My belly button is my best friend.',
    'I would like to date the moon.',
    'My dance moves scare the furniture.',
    'I am a very lonely piece of cheese.',
    'My left sock is the smart one.',
    'I slept like a baby. A screaming baby.',
    'I practice kissing with my cup.',
    'My voice is sponsored by cheese.',
    'My brain smells like burnt toast.',
    'I brought my sexy voice today.',
    'My nose deserves its own birthday.',
    'I want a tiny crown for each toe.',
    'My forehead is open for business.',
    'I am emotionally a boiled egg.',
    'I just fell in love with my lunch.',
    'I am the prettiest potato here.',
    'My toes have a secret club.',
    'I apologize to everyone except my chair.',
    'I think the ceiling is flirting with me.',
    'I have a chicken trapped in my voice.',
    'I am the president of bad dancing.',
    'I named my belly Sir Noodles.',
    'I smell like a rich onion.',
    'My hair woke up before me.',
    'My ears have stopped taking questions.',
    'I am saving this laugh for my wedding.',
    'I dream about kissing a giant noodle.',
    'I would hug a ghost for free.',
    'Please do not break my cup\'s heart.',
    'I want to smell a cloud.',
    'My shower knows all my songs.',
    'My mirror and I are dating.',
    'I love you more than my left sock.',
    'I am jealous of this chair\'s confidence.',
    'My tongue needs a holiday.',
    'I have a crush on my own laugh.',
    'My stomach just asked for a microphone.',
    'I think my shadow is prettier than me.',
    'I want to be someone\'s favorite potato.',
    'My feet smell expensive today.',
    'I came here to find a chicken husband.',
    'I think soup should have a belly button.',
    'I would kiss you, but my cup gets jealous.',
  ];
  const tasks = [
    'Cluck like a chicken.',
    'Speak like a robot.',
    'Say "I\'m in love with my cup."',
    'Ask "Do you like the smell of your feet?"',
    'Sing your next sentence.',
    'Say "I love you" in a different accent.',
    'Moo like a cow.',
    'Say "banana" like it is a secret.',
    'Talk like a sleepy baby.',
    'Say "Your Majesty" to someone.',
    'Make a fake burp.',
    'Say "My feet are famous."',
    'Whisper "The cheese is watching."',
    'Say "Breaking news!" before your next sentence.',
    'Say "Wow!" in three different voices.',
    'Laugh like an evil chicken.',
    'Say "I kissed my breakfast."',
    'Bark once, then say "Sorry."',
    'Tell your chair "I love you."',
    'Repeat someone\'s last word like a parrot.',
    'Say "I\'m a princess" in a deep voice.',
    'Say "Oh no!" in a tiny voice.',
    'Count to three like a hungry monster.',
    'Say "I\'m beautiful" like you just discovered it.',
    'Speak one sentence in slow motion.',
    'Make a goat sound.',
    'Introduce yourself as "Doctor Banana."',
    'Say "Clap, clap, clap!" like a bored crowd.',
    'Sing a silly song.',
    'Ask "Can I smell your socks?"',
    'Say "I object!" like a cartoon judge.',
    'Sigh like a tired elephant.',
    'Say "Please clap" after your next answer.',
    'Say "I missed you" to your cup.',
    'Ask "Would you date a chicken?"',
    'Make a kissing sound, then say "Oops."',
  ];
  const pool = Object.freeze([
    ...lines.map(text => ({ kind: 'line', text })),
    ...tasks.map(text => ({ kind: 'task', text })),
  ].map((prompt, i) => Object.freeze({
    id: 'crazy-' + String(i + 1).padStart(3, '0'), ...prompt,
  })));
  return Object.freeze({ pool });
})();
if (typeof module !== 'undefined' && module.exports) module.exports = TALK_CRAZY;
