/* Original, short English prompts for the optional Crazy Talk mode.
 * Lines can slip into a conversation; tasks invite a small spoken performance.
 * No physical dares or real accusations. The public pool is not a secret;
 * only each saved assignment is private. Keep the original first-60 line IDs.
 */
var TALK_CRAZY = (() => {
  'use strict';
  const lines = [
    'I think the fridge should have a vote.',
    'I agree with everything except the part where I have to do something.',
    'This sounds like a job for a very small duck.',
    'I once trained for this exact moment. I was wrong about the moment.',
    'I have a serious question. Where do socks go on holiday?',
    'I need a holiday from my holiday plans.',
    'I would like to thank my spoon for its support.',
    'My best ideas arrive five minutes after the meeting ends.',
    'Please imagine me wearing a tiny crown.',
    'I have checked the facts. The facts asked me to leave.',
    'Breaking news: my left sock has a different opinion.',
    'I agree, but only if the moon agrees too.',
    'That is exactly what a secret penguin would say.',
    'I am not late. I am a surprise guest.',
    'We should invite a talking cactus to our next meeting.',
    'I support this plan with both elbows.',
    'My brain is loading. Please enjoy this short silence.',
    'This conversation needs a theme song about cheese.',
    'I have decided to become a part-time cloud.',
    'I tried being normal this morning. Very tiring.',
    'In my kingdom, every Tuesday is soup day.',
    'I brought no facts, but I brought a very confident face.',
    'The answer came to me in a dream about noodles.',
    'Would this idea still work if we were all ducks?',
    'I think this deserves a tiny parade.',
    'My future self just sent me a message: buy more bananas.',
    'Please put that in the official notebook of nonsense.',
    'I cannot accept this award. Nobody offered me one.',
    'I have a question, a complaint, and half a biscuit.',
    'I believe a sandwich is just a very small building.',
    'My plan has three steps. I have forgotten all three.',
    'I am giving this idea five stars and one worried face.',
    'A wizard told me to say this. He seemed very polite.',
    'We need a backup plan and a backup banana.',
    'I cannot promise success, but I can promise a dramatic pause.',
    'I was born ready. Then I got confused.',
    'I vote for the option with the most comfortable shoes.',
    'Please hold your questions until I have invented the answers.',
    'I am saving this moment for my imaginary museum.',
    'I would like a refund for yesterday. It was not what I expected.',
    'I think our group needs a Minister of Snacks.',
    'I am deeply moved. Mostly because my chair has wheels.',
    'I have no experience, which means I have no bad habits yet.',
    'I would like to cancel gravity for the next five minutes.',
    'This plan has been approved by a rubber duck.',
    'I am emotionally ready to become a teapot.',
    'Let us keep this simple: one castle, two goats, no homework.',
    'Sorry, I was thinking about a squirrel in a business suit.',
    'I practiced this answer in the shower. The shower disagreed.',
    'If this were a movie, a tiny trumpet would play now.',
    'I have been waiting my whole life to say something this unhelpful.',
    'We should hold the next meeting inside a giant cake.',
    'My official answer is yes. My unofficial answer is jelly.',
    'I have a plan, but the plan is currently under a blanket.',
    'I am very good at keeping secrets. Even from myself.',
    'I would like a round of applause for doing almost nothing.',
    'Let me be clear: the umbrella knows too much.',
    'I am putting on my serious face. It may not fit.',
    'I came here to solve one problem and create two more.',
    'I think every good idea needs a tiny hat.',
  ];
  const tasks = [
    'Defend a terrible idea as if it will save the world: every home needs a slide instead of stairs.',
    'Give a serious weather report for this conversation. Predict a storm of opinions and a chance of snacks.',
    'Sell the group a completely useless product: a waterproof towel. Explain why it costs so much.',
    'Apologize for something impossible: you accidentally moved Tuesday. Offer a very silly way to fix it.',
    'Speak as a tired tour guide showing visitors around your own brain. Warn them about one area.',
    'Turn the next ordinary comment into breaking news. Add one shocked quote from an imaginary witness.',
    'Explain why you deserve an award for a tiny daily task, such as opening a bag or finding your keys.',
    'Give this conversation a movie title. Describe the dramatic scene that would appear in its trailer.',
    'Announce that you are running for president of the kitchen. Make two strange promises.',
    'Act as a very proud chef. Present a dish made from three things that are definitely not food.',
    'Pretend you are from the future. Warn everyone about a very small problem, such as squeaky shoes.',
    'Offer expert advice on a problem you clearly invented. Use a serious voice and a useless solution.',
    'Tell a short story that sounds heroic until you reveal it was only about getting out of bed.',
    'Explain the current topic to a visitor from space. Get one ordinary human habit completely wrong.',
    'Make a grand apology on behalf of Mondays. Explain what they were trying to achieve.',
    'Give a terrible idea an expensive name. Explain why rich people would pay for it.',
    'Start a very serious debate about whether soup needs a roof. Give one reason for each side.',
    'Describe your morning as if you were a sports reporter. Make brushing your teeth sound exciting.',
    'Pretend the group has just won a prize nobody wants. Give a proud acceptance speech.',
    'Announce a new rule for this imaginary town: people must sing before entering a lift. Defend the rule aloud.',
    'Give a formal job interview answer for the job of professional nap tester.',
    'Give a dramatic goodbye speech to an imaginary biscuit you are about to eat.',
    'Offer the group an impossible holiday. Explain the hotel, the food, and one very strange local rule.',
    'Explain a simple daily task as if it were a secret mission. Give the task a serious code name.',
    'Pretend you invented silence. Explain how people can buy the expensive version.',
    'Describe this conversation as a restaurant review. Rate the opinions, the pauses, and the service.',
    'Tell everyone about your imaginary rival. Your biggest fight was over something tiny, such as a pen.',
    'Make a serious complaint to the sun. Explain how its service has disappointed you.',
    'Introduce yourself as the new coach of a team that always loses. Give an oddly hopeful speech.',
    'Invent an excuse for missing an imaginary meeting. Make it stranger every time you explain a detail.',
    'Predict a silly world record that someone in this group could set. Explain the official rules.',
    'Give a royal announcement about an ordinary problem, such as having no clean cups.',
    'Explain why your imaginary shop sells only empty boxes. Describe its most expensive box.',
    'Pretend you are a mystery writer. Make one harmless thing about this topic sound deeply mysterious.',
    'Give advice from your 100-year-old future self. Make the first tip wise and the second tip ridiculous.',
    'Turn a small opinion about this topic into a grand promise. Then add one tiny, silly condition.',
  ];
  const pool = Object.freeze([
    ...lines.map(text => ({ kind: 'line', text })),
    ...tasks.map(text => ({ kind: 'task', text })),
  ].map((prompt, i) => Object.freeze({
    id: 'crazy-' + String(i + 1).padStart(3, '0'), ...prompt,
  })));
  return Object.freeze({ pool });
})();
if (typeof module !== 'undefined' && module.exports) module.exports = TALK_CRAZY;
