/* Original, short English lines for the optional Crazy Talk mode.
 * These are playful spoken lines, never physical dares or real accusations.
 * This public static pool is not a secret; only each saved assignment is private.
 */
var TALK_CRAZY = (() => {
  'use strict';
  const texts = [
    'I think the fridge should have a vote.',
    'Sorry, my invisible manager says no.',
    'This sounds like a job for a very small duck.',
    'Can we discuss the elephant? I mean my toy elephant.',
    'I have a serious question. Where do socks go on holiday?',
    'My chair has been listening very carefully.',
    'I would like to thank my spoon for its support.',
    'A potato could solve this, but it is busy today.',
    'Please imagine me wearing a tiny crown.',
    'I need three seconds to ask my imaginary lawyer.',
    'Breaking news: my left sock has a different opinion.',
    'I agree, but only if the moon agrees too.',
    'That is exactly what a secret penguin would say.',
    'I am not the boss. The pillow is the boss.',
    'We should invite a talking cactus to our next meeting.',
    'I support this plan with both elbows.',
    'My brain is loading. Please enjoy this short silence.',
    'This conversation needs a theme song about cheese.',
    'I have decided to become a part-time cloud.',
    'Let us give the floor to the invisible hamster.',
    'In my kingdom, every Tuesday is soup day.',
    'I brought no facts, but I brought a very confident face.',
    'The answer came to me in a dream about noodles.',
    'Would this idea still work if we were all ducks?',
    'I think this deserves a tiny parade.',
    'My future self just sent me a message: buy more bananas.',
    'Please put that in the official notebook of nonsense.',
    'I would like to speak on behalf of all lonely slippers.',
    'Before we decide, let us consider the feelings of the ceiling.',
    'I believe a sandwich is just a very small building.',
    'My imaginary assistant is taking imaginary notes.',
    'I am giving this idea five invisible stars.',
    'A wizard told me to say this. He seemed very polite.',
    'We need a backup plan and a backup banana.',
    'I cannot promise success, but I can promise a dramatic pause.',
    'This reminds me of my brief career as a garden gnome.',
    'I vote for the option with the most comfortable shoes.',
    'Let us ask a fish. It may have a fresh point of view.',
    'I am saving this moment for my imaginary museum.',
    'The official prize is one invisible pineapple.',
    'I think our group needs a Minister of Snacks.',
    'My inner chicken is very excited about this.',
    'There is only one problem: the dragon is still asleep.',
    'I would like to cancel gravity for the next five minutes.',
    'This plan has been approved by a rubber duck.',
    'I am emotionally ready to become a teapot.',
    'Let us keep this simple: one castle, two goats, no homework.',
    'Sorry, I was thinking about a squirrel in a business suit.',
    'I can explain everything, except why my shoes look suspicious.',
    'If this were a movie, a tiny trumpet would play now.',
    'I am asking this question for a very shy dinosaur.',
    'We should hold the next meeting inside a giant cake.',
    'My official answer is yes. My unofficial answer is jelly.',
    'I have a plan, but the plan is currently under a blanket.',
    'Somewhere, a goldfish is very proud of us.',
    'I would like a round of applause for this imaginary sandwich.',
    'Let me be clear: the umbrella knows too much.',
    'I am putting on my serious face. It may not fit.',
    'This is a small step for us and a big step for my hamster.',
    'I think every good idea needs a tiny hat.',
  ];
  const pool = Object.freeze(texts.map((text, i) => Object.freeze({
    id: 'crazy-' + String(i + 1).padStart(3, '0'), kind: 'line', text,
  })));
  return Object.freeze({ pool });
})();
if (typeof module !== 'undefined' && module.exports) module.exports = TALK_CRAZY;
