/* Original plain-English topics. Follow-ups are choices, not a required interview. */
const TALK_CATEGORIES = [
  {id:'connection',zh:'人際與信任',en:'Connection & trust'},
  {id:'self',zh:'自我與成長',en:'Self & growth'},
  {id:'belonging',zh:'群體與界線',en:'Belonging & boundaries'},
  {id:'work',zh:'工作與金錢',en:'Work & money'},
  {id:'fairness',zh:'公平與自由',en:'Fairness & freedom'},
  {id:'digital',zh:'科技與網路生活',en:'Technology & online life'},
  {id:'ethics',zh:'日常倫理與選擇',en:'Everyday ethics & choices'},
  {id:'future',zh:'社會與未來',en:'Society & the future'},
];
// Explain the main question itself: its meaning, scope, and a way to answer.
// Keep examples optional and leave room for different views; do not add a new task.
const TALK_EXPLANATIONS = {
  comfortable: 'Here, "be yourself" means feeling able to speak, act, or show feelings without trying hard to make a good impression. The question asks what another person does, or what they are like, that gives you that freedom.\n\nYou could name one thing, such as accepting disagreement or being comfortable with silence, and explain how it helps you feel at ease.',
  support: 'This question asks what kind of support you personally find helpful when something is worrying or upsetting you. Support could mean listening, offering advice, helping with a task, or giving you some space.\n\nChoose the response you would want and explain what it gives you. Your answer can depend on the situation; you do not need to describe a private problem.',
  cancel: 'The question asks which part of a last-minute cancellation affects how you feel about it. That could be why the friend cancelled, how they told you, how often it happens, or the time you had set aside.\n\nYou can begin by choosing the detail that matters most to you and explaining why. Different details may make the same cancellation feel understandable or disappointing.',
  care: 'This asks how you recognize care in an everyday action. A small action might be remembering a preference, noticing that you are tired, or making time to reply. Its meaning can matter more than its size or cost.\n\nName an action that would make you feel cared for, then explain what you would understand from it: perhaps that someone notices you, remembers you, or wants to help.',
  contact: 'The question is about what keeps a friendship feeling close when regular conversation is not possible. Staying close might mean trusting each other, feeling remembered, or being able to reconnect easily.\n\nYou could describe a habit or an understanding between friends that would help you. Explain how it supports the connection, even when messages or meetings are infrequent.',
  help: 'This asks what your first response would be when you notice a possible need but have not been invited to help. You might ask what is needed, make a small offer, help directly, or wait.\n\nExplain which response you would choose and why it fits. You can include what you would need to know before acting, especially if you are unsure whether the person wants help.',
  space: 'There are two connected parts to this question: when you need time alone, and what you want other people to understand about that need. Time alone could help you rest, think, enjoy something, or recover after being around people.\n\nYou can describe one situation and explain what being alone does for you. Then say what you would want a friend to understand about it.',
  change: 'Changing your mind means revising an opinion or decision after seeing it differently. This question asks what makes that process easier: useful evidence, a patient conversation, time to reflect, or feeling free to admit uncertainty.\n\nChoose something that helps you reconsider a view and explain why. You can speak generally without sharing a belief you would rather keep private.',
  time: 'This question asks what you would choose to do with a few hours that suddenly became yours. A good use of that time could be rest, enjoyment, connection, finishing something, or having no plan.\n\nSay how you would like to spend the afternoon and what makes that choice appealing. The reason behind your choice helps others understand what you need or value at the moment.',
  enough: 'Here, "enough" means the point at which you feel satisfied with something you want, such as money, free time, recognition, or possessions. The question asks how you would recognize that point.\n\nPick one kind of thing and describe a sign that you had enough of it. Your sign might be an amount, a feeling of security, or the freedom to stop worrying about getting more.',
  approval: 'To "shape our choices" means to influence what we decide to do. The question asks how much weight other people\'s opinions should have compared with our own needs, values, and judgment.\n\nYou could use an ordinary choice, such as work or how to spend time, to explain whose opinion you would consider and how much influence you would give it. Your own balance may depend on the decision.',
  uncertainty: 'The question asks when acting with some uncertainty is better than waiting to feel more certain. Feeling sure can mean having enough information, confidence in your choice, or confidence about the result.\n\nYou could describe a type of decision and explain why you would act now or wait. How serious the possible result is, and whether you can change course later, may affect your answer.',
  different: 'This asks which differences can feel enjoyable or comfortable within a friendship. Differences might involve interests, habits, personality, tastes, or ways of seeing the world. Enjoying a difference can mean learning from it or simply liking that you are not the same.\n\nChoose one kind of difference and explain what makes it easy for you to appreciate.',
  welcome: 'Feeling welcome means sensing that there is a place for you in a group and that your presence is wanted. The question asks what helps create that feeling when you are new.\n\nYou could name a small action, a way people talk, or an atmosphere that would help you join in comfortably. Explain what that would communicate to you, such as interest, patience, or room to participate at your own pace.',
  travel: 'The question asks what friends should discuss and agree on before travelling together. An agreement is a shared expectation about something that could affect everyone, such as budget, pace, meals, or time apart.\n\nChoose one or two matters you would want to settle first and explain why. You can focus on what would help you enjoy the trip, rather than planning a whole journey.',
  family: 'Family expectations are hopes or beliefs about how an adult should live, such as their work, relationships, or responsibilities. This question asks how much influence those expectations should have on the adult\'s choices.\n\nYou could explain an area where family input seems valuable to you, or a limit you would want to keep. Describe the balance you find reasonable and the reason for it.',
  tradition: 'A tradition is something people keep doing and pass on, such as a celebration, a meal, or a shared custom. The question asks what gives it enough value to continue.\n\nYou could identify a reason for keeping a tradition, such as connection, shared memory, enjoyment, or a belief it expresses. Explain why that reason matters to you; you can also say when changing part of the tradition would still preserve its value.',
  boundaries: 'This asks what makes declining a request or invitation feel respectful to the person receiving the answer. Saying no sets a limit, but tone, clarity, timing, or a brief explanation can affect how that limit is understood.\n\nDescribe what you would appreciate when someone says no to you, or how you would want to say it yourself. Explain what makes that approach feel considerate.',
  pay: 'This asks which reasons should guide how much a job pays. Possible reasons include the effort involved, the skills required, the risks, and how much the work helps others. Different people may find different reasons more important.\n\nYou can choose one reason you consider important and explain why it should affect pay. If two reasons point to different amounts, you can say which you think should matter more.',
  ambition: 'A "good career" here means working life that feels worthwhile or suitable for the person doing it. The question asks what makes it good beyond salary and the status of a job title.\n\nYou could focus on freedom, learning, stability, relationships, useful work, or time for the rest of life. Choose something that matters to you and explain how it would improve your experience of working.',
  rest: 'To "earn their rest" means having to do enough work or achieve enough before a break feels deserved. The question asks whether rest should depend on what a person has done, or whether needing rest can be a sufficient reason.\n\nExplain the view you find reasonable and why. You can use an ordinary workday or day at home to show what your view would mean in practice.',
  teamwork: 'Sharing credit means deciding how people\'s contributions are recognized when a team succeeds. Contributions can differ in time, skill, ideas, responsibility, or support that is less visible.\n\nThe question asks what a fair way of giving recognition would look like. You could explain one principle you would use and how it would recognize people whose contributions are different.',
  failure: 'The question asks what allows a mistake to help someone learn. That might involve understanding what went wrong, getting useful feedback, having a chance to try again, or changing how a task is done.\n\nChoose a condition you think matters and explain how it turns the experience into learning. You can use a simple or imagined mistake; a personal failure story is not required.',
  meaning: 'For work to give life meaning, it might provide a sense of purpose, identity, or doing something worthwhile. This question asks whether you need that feeling to come from your job.\n\nYou could explain how important meaning at work is to you and why. It is also possible to value a job for supporting other meaningful parts of life, such as relationships, interests, or community.',
  rules: 'Treating everyone the same can mean applying the same rules or giving everyone the same amount of help. Being fair can also involve considering differences in people\'s needs or circumstances.\n\nThe question asks whether equal treatment is always enough for fairness. You can use one simple example to explain when the same treatment seems fair to you, or when a difference in treatment seems reasonable.',
  chances: 'A "fair chance" means having a reasonable opportunity to take part or work toward a goal. People may have different amounts of time, money, health, knowledge, or support at the start.\n\nThis question asks what would need to be true for you to call the opportunity fair. You can focus on one area, such as learning or finding work, and explain which starting conditions matter most.',
  freedom: 'Personal freedom means being able to make choices about your own life and behavior. A shared space is somewhere those choices also affect other people, such as a home, workplace, or public area.\n\nThe question asks where you would place a reasonable limit. You could choose one shared situation and explain which choices people should be free to make, and what effect on others would justify a boundary.',
  voice: 'To "have a say" means having some influence over a decision. That could mean being listened to, helping shape the options, voting, or making the final choice.\n\nThis question asks who should have that influence when a decision affects a group. You could choose a simple group decision and explain whose views should count and why. You can distinguish being heard from having the final authority.',
  secondchance: 'A second chance means being allowed to try again after a mistake or harmful action. The question asks what, if anything, someone should do before others are willing to offer that opportunity.\n\nYou could consider acknowledging the problem, making repairs, apologizing, or showing changed behavior. Explain which step would matter most to you and what it would demonstrate.',
  merit: 'Effort refers to what someone works at or chooses to do. Luck includes helpful or difficult circumstances they did not choose, such as timing, opportunities, or their starting point.\n\nThe question asks how you see the influence of each on success. Choose a kind of success and explain what role you think effort and luck play. You can describe their relationship without giving an exact percentage.',
  privacy: 'Personal information can include your location, habits, contacts, or other details about your life. Sharing it may make a service easier to use or give you a benefit.\n\nThe question asks what would make that exchange acceptable to you. You can name a situation in which you would share, or a boundary you would keep, and explain how the benefit, the information, or your trust in the recipient affects your choice.',
  ai: 'This asks where you would welcome help from AI and where you would prefer to do the thinking or work yourself. Help can range from suggesting ideas to completing a task or recommending a decision.\n\nChoose a task and explain what kind of help, if any, you would want. Accuracy, privacy, learning, personal expression, or responsibility for the result could all influence your preference.',
  onlinefriend: 'An online friendship may develop mainly through messages, voice, or shared activities on the internet. "Feel real" means that the connection matters to you and feels like a friendship you can rely on.\n\nThe question asks what gives it that quality. You could focus on trust, consistency, shared experiences, or mutual care, and explain why your chosen quality makes the connection meaningful.',
  news: 'Trusting information means being willing to believe it is accurate enough to rely on. Online, that judgment may depend on who created it, the evidence offered, and whether other reliable sources support it.\n\nThe question asks what gives you confidence in a claim. Describe a sign you look for or a check you would make, and explain why it makes the information more believable to you.',
  attention: 'Our attention is the time and focus we give to something. Choosing freely online means having meaningful control over what we notice and how long we stay with it. Features such as recommendations or notifications may also influence that choice.\n\nThe question asks how much control you think we have. You can describe an ordinary online habit and explain what feels chosen, influenced, or difficult to stop.',
  publicmistakes: 'An old online mistake might be a post or comment that continues to affect how someone is treated years later. "Follow someone" means that it keeps influencing their relationships, reputation, or opportunities.\n\nThe question asks how long that past action should remain relevant. Explain what would matter to your judgment, such as the harm, how long ago it happened, or what the person has done since.',
  honesty: 'The question asks whether telling the truth is always the kinder choice. Kindness here can include caring about someone\'s feelings, helping them understand a situation, or giving them information they need.\n\nYou could explain a situation in which honesty seems caring, or one in which the way or timing of telling the truth matters. Use it to show what you consider when judging kindness.',
  loyalty: 'Loyalty means standing by someone or remaining committed to a relationship. This question asks what that commitment should look like when you believe your friend has made a wrong choice.\n\nYou could explain whether support would mean agreeing, disagreeing privately, speaking up, or helping them take responsibility. Choose the response that best fits your understanding of being a loyal friend and explain why.',
  giving: 'The question assumes your ability to help is limited, so you cannot meet every need. Help might mean time, money, practical work, or emotional support. It asks how you decide where that limited help should go.\n\nExplain a reason that would guide your choice, such as urgency, closeness, or the difference you could make. You can speak generally without describing your own finances or circumstances.',
  promise: 'A promise creates an expectation that someone will do what they said. Calling it "reasonable" to break a promise means believing there is a strong enough reason to change that commitment.\n\nThe question asks what kind of reason could justify this. You could describe a change in circumstances and explain why it would, or would not, be enough to release someone from their promise.',
  goodintentions: 'Good intentions mean that someone meant to help or do something positive, even though their action caused harm. The question asks how much their intention should affect our judgment of what happened.\n\nYou can explain the weight you would give to what they meant compared with the actual effect. You may also describe what their intention changes about how you think they should respond afterward.',
  smallchoices: 'Everyday purchases can affect people or places beyond the buyer, such as the people making a product or the waste it creates. This question asks how much attention we should give those effects when choosing what to buy.\n\nExplain the level of responsibility you find reasonable. You could consider what a buyer can know and what choices are available within their time or budget.',
  climate: 'Sharing the effort means deciding who should make which changes or carry which costs to protect the environment. The work could be shared among individuals, businesses, communities, or governments.\n\nThe question asks what would make that division reasonable. You could explain one basis for sharing it, such as ability to act, resources, or contribution to the problem, and why that basis matters.',
  city: 'A good place to live could offer safety, housing, transport, green space, services, or a sense of belonging. "Everyone" asks you to consider people with different ages, resources, and daily needs.\n\nThe question is asking which things you think all residents should be able to access. Choose something you see as essential and explain how it helps people live well, even if their lives are different.',
  generations: 'People who live after us include future generations whose choices may be affected by what we do today. What we "owe" them means the responsibilities we have toward their well-being and opportunities.\n\nThe question asks what those responsibilities should include. You could choose something we might preserve, improve, or avoid damaging, and explain why it matters for people we may never meet.',
  education: 'To "prepare people for" something means helping them develop knowledge or abilities they can use later. Education might prepare people for work, independent living, relationships, public life, or continued learning.\n\nThe question asks which purposes should matter most. Choose an ability or part of life you think education should support, and explain what makes it valuable.',
  animals: 'Responsibilities are things we believe people should do, or avoid doing, because animals can be affected by our choices. They might involve care, living conditions, protection from harm, or the places animals live.\n\nThe question asks what those duties should be. You can focus on pets, farm animals, or wildlife, then explain a responsibility you think people have and why.',
  communitychange: 'A small shared action is something a group does together on a limited scale. For it to "matter," it might improve a few lives, create a useful habit, or contribute to a larger change.\n\nThis question asks what helps people believe the action is worth taking. You could name a sign of progress or a reason to participate, and explain how it makes the possible impact feel real.',
};
const TALK_TOPICS = Object.entries({
  connection: [
    ['comfortable','🌿','Feeling at ease','自在 真實 信任 朋友',
      'What helps you feel that you can be yourself around someone?',
      'What does being yourself mean when you are with other people?',
      'Can changing how you act for someone be a form of care?',
      'Where is the line between being honest and being unkind?',
      'What could a group do to make it easier to disagree openly?'],
    ['support','☕','Being there','支持 傾聽 建議 關心',
      'When something is bothering you, what do you want a friend to do?',
      'What makes listening feel different from simply staying quiet?',
      'Why might useful advice still feel unwelcome?',
      'When should a friend challenge you instead of taking your side?',
      'How could you ask what kind of support someone wants?'],
    ['cancel','📅','A change of plans','取消 約定 期待 時間',
      'A friend cancels your plans at the last minute. What matters most to you?',
      'Is the hardest part the lost time, the reason, or feeling less important?',
      'How might the same cancellation look from your friend\'s side?',
      'How much should a promise limit our freedom to change plans?',
      'What would make it possible to trust the next plan?'],
    ['care','🍊','Small signs of care','關愛 表達 付出 照顧',
      'What small thing can someone do that makes you feel they care?',
      'Why do some small actions matter more than expensive gifts?',
      'Can someone care deeply but show it in a way you do not enjoy?',
      'How much should we change the way we show care for another person?',
      'How could two people talk about care without keeping a score?'],
    ['contact','💬','Staying close','聯絡 友誼 距離 回訊息',
      'What helps you stay close to a friend you do not talk to every day?',
      'What makes a long silence feel safe or uncertain?',
      'Could frequent messages create pressure instead of closeness?',
      'What do friends owe each other when their lives become very different?',
      'What kind of contact could work for people with different needs?'],
    ['help','🤝','Offering help','幫助 尊重 自主 接受',
      'If a friend seems to need help but has not asked, what would you do?',
      'What makes help easy or hard to accept?',
      'When could doing nothing be a respectful choice?',
      'When does helping someone become deciding for them?',
      'How could you offer help while leaving room for a real no?'],
  ],
  self: [
    ['space','🌙','A little space','獨處 空間 寂寞 休息',
      'When do you want time alone? What would you like others to understand?',
      'What is the difference between being alone and feeling lonely?',
      'Why might someone read a need for space as rejection?',
      'How do you balance your need for space with someone else\'s need for closeness?',
      'What could you say that protects your time without leaving someone guessing?'],
    ['change','🌱','Changing your mind','改變 成長 觀點 固執',
      'What makes it easier for you to say, "I have changed my mind"?',
      'What kind of evidence or conversation helps you reconsider an idea?',
      'Why might keeping an old belief feel safer than changing it?',
      'When is staying firm a strength, and when does it stop us from learning?',
      'How could a group make changing your mind feel welcome?'],
    ['time','🪴','A free afternoon','時間 休閒 充實 生產力',
      'If you suddenly had a free afternoon, how would you want to spend it?',
      'What makes time feel well spent to you?',
      'Why can rest feel like wasting time even when we need it?',
      'Who should decide whether a day was useful?',
      'What small change would make your week closer to the life you want?'],
    ['enough','🌤️','Having enough','滿足 慾望 比較 成功',
      'How would you know that you have enough of something you want?',
      'Does enough mean comfort, safety, freedom, or something else?',
      'How might your idea of enough change if your friends had much more?',
      'Can wanting more and feeling thankful exist together?',
      'What would help you choose a goal that feels like your own?'],
    ['approval','🪞','Being liked','認同 討好 自我 期待',
      'How much should other people\'s opinions shape our choices?',
      'Whose opinion do you find useful, and why?',
      'Could ignoring every opinion make us less aware of others?',
      'When does caring about others become giving up your own needs?',
      'How could someone test a choice without asking everyone to approve it?'],
    ['uncertainty','🧭','Not having an answer','不確定 決定 風險 方向',
      'When is it better to make a choice before you feel sure?',
      'What kind of uncertainty is hardest to live with?',
      'What could be lost by waiting for more information?',
      'How should a choice change when other people share the risk?',
      'What would a small, reversible first step look like?'],
  ],
  belonging: [
    ['different','🧩','Being different','差異 包容 價值觀 相處',
      'What differences between friends are easy for you to enjoy?',
      'What makes a difference interesting rather than upsetting?',
      'Could a shared value still lead two people to opposite choices?',
      'Which differences can a friendship hold, and where might a limit be needed?',
      'How could you ask about a difficult difference without trying to win?'],
    ['welcome','🏡','Feeling welcome','歸屬 新人 群體 包容',
      'When you join a new group, what helps you feel welcome?',
      'What is the difference between being invited and feeling included?',
      'Could an activity that welcomes one person make another uncomfortable?',
      'How much should a group change for a new member?',
      'What could this group do to include quiet people without putting them on the spot?'],
    ['travel','🧳','Going somewhere together','旅行 朋友 協調 妥協',
      'Before a trip with friends, what would you want to agree on?',
      'Which travel choices reveal what matters to people?',
      'Could spending part of a trip apart make the friendship stronger?',
      'When should the group follow the majority, and when should one person\'s need come first?',
      'What agreement could leave room for both shared time and freedom?'],
    ['family','🏠','Family expectations','家庭 期待 自主 責任',
      'How much should family expectations shape an adult\'s life?',
      'When do expectations feel like support, and when do they feel like pressure?',
      'What might a family be afraid of when they resist someone\'s choice?',
      'Does receiving support create a duty to follow someone\'s wishes?',
      'How could a person show care while choosing a different path?'],
    ['tradition','🕯️','Keeping a tradition','傳統 文化 改變 世代',
      'What makes a tradition worth keeping?',
      'Is its value in the activity, the memory, or the people sharing it?',
      'How might the same tradition feel to someone new to the group?',
      'When should belonging matter more than doing things the old way?',
      'How could a tradition change while keeping what people love about it?'],
    ['boundaries','🚪','Saying no','拒絕 界線 群體 壓力',
      'What makes a no feel respectful rather than unfriendly?',
      'Why is saying no easier in some relationships than others?',
      'Could always saying yes make a relationship less honest?',
      'When do we owe someone a reason for saying no?',
      'How could a group make it easier to decline without losing a sense of belonging?'],
  ],
  work: [
    ['pay','💰','What pay should reflect','薪資 金錢 價值 勞動',
      'What should decide how much a job pays?',
      'Should pay reflect effort, skill, risk, or how much people need the work?',
      'Why might work that helps many people still be paid less?',
      'Should equal effort mean equal pay when results are different?',
      'What would a fair pay decision need to take into account?'],
    ['ambition','⛰️','A good career','職涯 野心 成功 升遷',
      'What makes a career good beyond its title or salary?',
      'Which parts of work affect life outside work the most?',
      'Why might turning down a promotion be a good choice?',
      'How much present comfort is worth giving up for future opportunities?',
      'What would you ask before accepting a job that looks successful to others?'],
    ['rest','🛋️','The right to rest','休息 工作 加班 責任',
      'Should people need to earn their rest?',
      'What makes rest feel acceptable in a workplace?',
      'How does one person\'s rest affect coworkers who cover for them?',
      'Who should carry the cost when a team has more work than time?',
      'What rule could protect rest without leaving urgent needs ignored?'],
    ['teamwork','🧱','Sharing the credit','合作 功勞 團隊 公平',
      'How should a team share credit when people contribute in different ways?',
      'Which kinds of useful work are easy to overlook?',
      'Could the person who speaks least be doing the most important work?',
      'Should rewards be equal, or should they match each person\'s contribution?',
      'How could a team notice effort without turning everything into a competition?'],
    ['failure','🔧','Room to fail','失敗 錯誤 學習 工作',
      'What makes a mistake a useful part of learning?',
      'What support helps someone learn instead of hide a mistake?',
      'Why might a good decision still lead to a bad result?',
      'How much failure should be accepted when other people bear the cost?',
      'What should a team do after a mistake besides asking who caused it?'],
    ['meaning','🛠️','Meaningful work','意義 工作 生活 熱情',
      'Does a job need to give your life meaning?',
      'What kinds of work feel valuable even when they are not enjoyable?',
      'Could a simple job leave more room for a meaningful life?',
      'Is it fair to expect people to accept less pay for work they care about?',
      'Where else could someone find meaning if their job is mainly a way to earn money?'],
  ],
  fairness: [
    ['rules','⚖️','The same rule for everyone','公平 規則 例外 平等',
      'Is treating everyone the same always fair?',
      'What is the difference between the same treatment and the same chance?',
      'When could making an exception help a rule serve its purpose?',
      'Who should decide which needs deserve an exception?',
      'How could a group explain exceptions without making rules feel meaningless?'],
    ['chances','🌉','A fair starting point','機會 起點 資源 平等',
      'What would it mean for everyone to have a fair chance?',
      'Which advantages are easy to see, and which are easy to miss?',
      'How might the same opportunity help two people very differently?',
      'Should more help go to those who need it most or those likely to benefit most?',
      'What could a school or workplace change to make access more fair?'],
    ['freedom','🕊️','Freedom in shared spaces','自由 限制 共享 空間',
      'Where should personal freedom end in a shared space?',
      'What makes one person\'s choice become everyone\'s problem?',
      'Could a rule that feels annoying to you give someone else more freedom?',
      'When should we accept discomfort to protect another person\'s choice?',
      'How could people agree on a rule when their needs conflict?'],
    ['voice','🎙️','Having a say','發言 民主 多數 決策',
      'Who should have a say in a decision that affects a group?',
      'Does having a vote mean someone has been heard?',
      'What can a small minority notice that the majority misses?',
      'When should experience matter more than an equal vote?',
      'What process could help a group decide without silencing people?'],
    ['secondchance','🔄','A second chance','第二次 機會 原諒 責任',
      'What should someone do before being given a second chance?',
      'What would count as a real sign of change?',
      'Why might someone who was hurt still not want to reconnect?',
      'Can we support change while keeping firm limits?',
      'What would a second chance with clear responsibilities look like?'],
    ['merit','🎲','Effort and luck','努力 運氣 成就 責任',
      'How much of success comes from effort, and how much from luck?',
      'What parts of a result can a person actually control?',
      'Why might two people who work equally hard get very different results?',
      'Does benefiting from luck create a responsibility to help others?',
      'How could we praise effort without blaming people for every setback?'],
  ],
  digital: [
    ['privacy','🔒','Privacy or convenience','隱私 便利 資料 科技',
      'When would you share personal information to make life easier?',
      'What makes some information feel more private than other information?',
      'Could a convenient service be hard to refuse even when you dislike its rules?',
      'What should happen when one person shares information about someone else?',
      'What would a clear and fair choice about data look like?'],
    ['ai','🤖','Thinking with AI','人工智慧 AI 思考 學習 工作',
      'Which tasks would you want AI to help with, and which would you keep for yourself?',
      'What is the difference between getting help and giving up your own judgment?',
      'Could an imperfect AI tool still make an activity easier to join?',
      'Who should be responsible when someone follows bad AI advice?',
      'What habit could help people use AI while still learning to think for themselves?'],
    ['onlinefriend','📱','Friendship online','網路 友誼 關係 社群',
      'What makes an online friendship feel real?',
      'What can people learn about each other through words alone?',
      'Could it be easier to be honest with someone you have never met?',
      'What do online friends owe each other when they can leave with one click?',
      'What would help an online group build trust over time?'],
    ['news','📰','What we choose to believe','新聞 資訊 相信 謠言',
      'What makes you trust information you find online?',
      'How do confidence, detail, and popularity affect what seems true?',
      'Why might a story feel believable because we want it to be true?',
      'How much checking should we do before passing information to others?',
      'How could you question a shared story without making a friend feel attacked?'],
    ['attention','⏳','Who gets our attention','注意力 手機 時間 演算法',
      'How freely do we choose what gets our attention online?',
      'What is the difference between enjoying an app and finding it hard to leave?',
      'Could the same feature help one person connect and distract another?',
      'How should responsibility be shared between users and the people designing apps?',
      'What would an app that respects your time do differently?'],
    ['publicmistakes','💭','A mistake that stays online','網路 錯誤 公審 遺忘',
      'Should an old online mistake follow someone for years?',
      'What matters about the harm, the time passed, and the person\'s response?',
      'Why might removing a post feel fair to one person and unfair to another?',
      'How do we balance remembering harm with allowing people to change?',
      'What would a useful public response look like beyond punishment?'],
  ],
  ethics: [
    ['honesty','🪟','A kind truth','誠實 善意 謊言 真相',
      'Is it always kinder to tell the truth?',
      'How do timing and choice of words change the effect of an honest message?',
      'Could keeping quiet protect yourself more than the other person?',
      'When does someone\'s right to know matter more than their comfort?',
      'How could you tell a difficult truth without using honesty as an excuse to hurt?'],
    ['loyalty','🧵','Standing by a friend','忠誠 朋友 對錯 支持',
      'What does loyalty to a friend mean when you think they are wrong?',
      'What is the difference between supporting a person and supporting their action?',
      'How might the person hurt by your friend see your silence?',
      'When should fairness matter more than taking your friend\'s side?',
      'What could you say that protects the friendship while challenging the action?'],
    ['giving','🎁','Choosing whom to help','幫助 捐助 距離 資源',
      'If you can only help a little, how do you choose whom to help?',
      'Does feeling close to someone change what you think you owe them?',
      'What needs are easy to miss because the people affected are far away?',
      'Should help go where it does the most good or where we feel the most responsibility?',
      'How could someone make a thoughtful choice without needing a perfect answer?'],
    ['promise','🪢','Keeping a promise','承諾 改變 責任 信任',
      'When is it reasonable to break a promise?',
      'What makes a promise different from a plan or a hope?',
      'How might keeping one promise cause harm somewhere else?',
      'Should a promise still hold when the situation changes in a way no one expected?',
      'What should someone do when they can no longer keep their word?'],
    ['goodintentions','🌼','Good intentions, real effects','善意 結果 責任 道歉',
      'When an action hurts someone, how much should good intentions matter?',
      'What can intentions tell us that the result alone cannot?',
      'Why might an explanation sound like an excuse to the person hurt?',
      'How should responsibility change when the harm was hard to predict?',
      'What would a helpful apology include besides saying you meant well?'],
    ['smallchoices','🛒','The cost of a small choice','消費 道德 選擇 便利',
      'How much should we think about the effects of everyday purchases?',
      'What information would help you decide whether a choice matches your values?',
      'How does having less money or time change what choices are realistic?',
      'How much responsibility belongs to shoppers, businesses, and governments?',
      'What is one manageable change that would matter without requiring perfection?'],
  ],
  future: [
    ['climate','🌍','Sharing environmental costs','環境 氣候 責任 成本',
      'How should people share the effort of protecting the environment?',
      'What makes an environmental change feel possible in daily life?',
      'How might the same change cost much more for some people than others?',
      'Should those who caused more harm, or those who can afford more, do more?',
      'What would make a shared environmental plan feel fair enough to support?'],
    ['city','🏙️','A place for everyone','城市 住宅 公共 空間',
      'What should a good place to live offer everyone?',
      'Which needs are easy to overlook when a city is designed?',
      'How might a child, an older person, and a night worker use the same street?',
      'How should a city choose when quiet, housing, jobs, and green space compete?',
      'What small change could make a shared place work for more people?'],
    ['generations','🌳','People we will never meet','世代 未來 資源 責任',
      'What do we owe people who will live after us?',
      'Which choices today could limit their options?',
      'How might future people have needs we cannot predict?',
      'How much should people today give up for benefits they will never see?',
      'What principle could help us make long-term choices under uncertainty?'],
    ['education','📚','What learning is for','教育 學習 學校 未來',
      'What should education prepare people for?',
      'Which useful abilities are hard to measure with a test?',
      'Could a lesson be valuable even if it never helps someone get a job?',
      'How should schools balance shared knowledge with each person\'s interests?',
      'What would you add to a learning space for people with different starting points?'],
    ['animals','🐾','Care beyond people','動物 照顧 倫理 自然',
      'What responsibilities do people have toward animals?',
      'Why do we feel differently about pets, farm animals, and wild animals?',
      'How might tradition or livelihood shape a person\'s view of animal care?',
      'When human needs and animal well-being conflict, what should guide the choice?',
      'What improvement could people with different views still agree to support?'],
    ['communitychange','🌻','Making a difference together','社區 改變 行動 希望',
      'What makes people believe a small shared action can matter?',
      'What is the difference between a meaningful action and a symbolic one?',
      'Could an action help even if it does not solve the whole problem?',
      'How do we balance a practical first step with the need for bigger change?',
      'What could a small group try, learn from, and adjust together?'],
  ],
}).flatMap(([category, rows]) => rows.map(([id, emoji, title, keywords, question, ...questions]) => ({
  id, category, emoji, title, keywords, question, starter: TALK_EXPLANATIONS[id], followUp: questions[0],
  followUps: questions.map((question, i) => ({stage:['understand','perspective','tradeoff','practice'][i],question})),
})));
const TALK_LIBRARY = (() => {
  function search(category = '', query = '') {
    const words = String(query).trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);
    return TALK_TOPICS.filter(topic => {
      const group = TALK_CATEGORIES.find(c => c.id === topic.category);
      const text = [topic.title, topic.keywords, topic.question, topic.starter, ...topic.followUps.map(q => q.question), group.zh, group.en].join(' ').toLocaleLowerCase();
      return (!category || category === topic.category) && words.every(word => text.includes(word));
    });
  }
  function draw(category = '', query = '', exclude = [], random = Math.random) {
    const matches = search(category, query);
    const fresh = matches.filter(topic => !exclude.includes(topic.id));
    const pool = fresh.length ? fresh : matches;
    return pool.length ? pool[Math.floor(random() * pool.length)] : null;
  }
  function custom({title = '', question = '', starter = '', followUps = ''}) {
    question = String(question).trim(); title = String(title).trim(); starter = String(starter).trim();
    const questions = String(followUps).split(/\r?\n/).map(q => q.trim()).filter(Boolean);
    if (!question || question.length > 500 || title.length > 80 || starter.length > 600 || questions.length > 8 || questions.some(q => q.length > 300)) throw new Error('invalid_topic');
    return {id:'custom',emoji:'✏️',title,question,starter,followUp:questions[0] || '',
      followUps:questions.map(question => ({stage:'custom',question}))};
  }
  return {search, draw, custom};
})();
if (typeof module !== 'undefined' && module.exports) module.exports = {TALK_TOPICS, TALK_CATEGORIES, TALK_LIBRARY};
