'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const E = require('../bluff-king-engine.js');
const bank = Array.from({ length: 70 }, (_, i) => ({ id: 'test-' + i, canonicalKnowledgeId: 'test-knowledge-' + i, locale: 'en', term: 'Test topic ' + i, publicPrompt: 'Explain this test topic.', hintMode: i % 3 === 0 ? 'choices' : i % 3 === 1 ? 'category' : 'none', publicHints: i % 3 === 0 ? ['A', 'B', 'C'] : i % 3 === 1 ? ['A'] : [], secretAnswer: 'SECRET_' + i, supportingFacts: ['Fact one', 'Fact two'], revealExplanation: 'Test only.', sources: [{ title: 'Test', url: 'https://example.invalid/test' }], verificationStatus: 'verified', verifiedAt: '2026-10-06', enabled: true }));
let next = 0; const opts = { now: 1000, rng: () => 0, uuid: () => 'generated-' + ++next };
function setup(count = 3, code = 'TEST') { const s = E.blankStore(); E.applyCommand(s, 'identity-0', { room: code, action: 'create', name: 'P0', participate: true }, bank, opts); for (let i = 1; i < count; i++) E.applyCommand(s, 'identity-' + i, { room: code, action: 'join', name: 'P' + i, participate: true }, bank, opts); return s; }
function command(s, action, who = 'identity-0', data = {}, code = 'TEST') { const room = s.rooms[code]; const input = { room: code, action, commandId: 'command_' + String(++next).padStart(8, '0'), expectedVersion: room.version, roundId: room.round?.id, ...data }; E.applyCommand(s, who, input, bank, opts); return input; }
function discussion(s) { command(s, 'start'); command(s, 'confirmTopic'); command(s, 'beginDiscussion'); }
for (const count of [3, 6, 9]) test(`${count} players: fixed roster, exactly one Thinker and one Truth Teller; one circle`, () => {
  const s = setup(count); discussion(s); const room = s.rooms.TEST; const roles = room.roster.map(id => id === room.round.thinkerId ? 'thinker' : id === room.round.truthfulId ? 'truthful' : 'bluffer'); assert.equal(roles.filter(x => x === 'thinker').length, 1); assert.equal(roles.filter(x => x === 'truthful').length, 1); assert.equal(roles.filter(x => x === 'bluffer').length, count - 2);
  const order = [...room.round.spotlightOrder]; assert.equal(order.length, count - 1); assert.deepEqual(order, room.roster.filter(id => id !== room.round.thinkerId)); assert.deepEqual(E.projectView(s, 'identity-0', 'TEST', bank).round.spotlightOrder, order);
  assert.throws(() => command(s, 'identify', 'identity-0', { targetId: order[0] }), e => e.code === 'spotlight_incomplete');
  E.applyCommand(s, 'late-identity', { room: 'TEST', action: 'join', name: 'Late', participate: true }, bank, opts); assert.equal(room.roster.length, count); assert.equal(room.members.at(-1).seated, false);
  for (const id of order) { assert.equal(E.projectView(s, 'identity-0', 'TEST', bank).round.currentSpotlightId, id); command(s, 'nextSpotlight'); assert.equal(room.phase, 'discussion'); }
  assert.equal(room.round.allCovered, true); assert.equal(E.projectView(s, 'identity-0', 'TEST', bank).round.currentSpotlightId, null);
});
test('all six scoring examples, including negative and zero net points', () => {
  const cases = [ ['B', null, { A: 2, B: 2, C: 0, D: 0 }], ['C', null, { A: 0, B: 0, C: 2, D: 0 }], ['B', 'D', { A: 3, B: 2, C: 0, D: 0 }], ['C', 'D', { A: 0, B: 0, C: 2, D: 0 }], ['C', 'B', { A: -2, B: 0, C: 2, D: 0 }], ['B', 'B', { A: 0, B: 2, C: 0, D: 0 }] ];
  for (const [selected, challenge, expected] of cases) assert.deepEqual(Object.fromEntries(Object.entries(E.scoreRound(['A', 'B', 'C', 'D'], 'A', 'B', selected, challenge).delta).map(([id, d]) => [id, d.points])), expected);
});
test('challenge works before or after the circle; once only, no self, no elimination', () => {
  for (const late of [false, true]) { const s = setup(4); discussion(s); const r = s.rooms.TEST.round; if (late) for (let i = 0; i < 3; i++) command(s, 'nextSpotlight'); assert.throws(() => command(s, 'challenge', 'identity-0', { targetId: r.thinkerId }), e => e.code === 'invalid_target'); command(s, 'challenge', 'identity-0', { targetId: r.truthfulId }); assert.throws(() => command(s, 'challenge', 'identity-0', { targetId: s.rooms.TEST.roster[2] }), e => e.code === 'challenge_used'); assert.equal(s.rooms.TEST.roster.length, 4); assert.equal(s.rooms.TEST.phase, 'discussion'); if (!late) for (let i = 0; i < 3; i++) command(s, 'nextSpotlight'); command(s, 'identify', 'identity-0', { targetId: r.truthfulId }); assert.equal(s.rooms.TEST.scores[r.thinkerId], 0); assert.equal(s.rooms.TEST.scores[r.truthfulId], 2); }
});
test('duplicate commands and stale views cannot skip seats, spend twice, score twice or open two rounds', () => {
  const s = setup(); discussion(s); const first = command(s, 'nextSpotlight'); E.applyCommand(s, 'identity-0', first, bank, opts); assert.equal(s.rooms.TEST.round.coveredIds.length, 1);
  assert.throws(() => E.applyCommand(s, 'identity-0', { ...first, commandId: 'another_command_0001' }, bank, opts), e => e.code === 'stale_version');
  const challenge = command(s, 'challenge', 'identity-0', { targetId: s.rooms.TEST.round.truthfulId }); E.applyCommand(s, 'identity-0', challenge, bank, opts); command(s, 'nextSpotlight'); const final = command(s, 'identify', 'identity-0', { targetId: s.rooms.TEST.round.truthfulId }); const scores = { ...s.rooms.TEST.scores }; E.applyCommand(s, 'identity-0', final, bank, opts); assert.deepEqual(s.rooms.TEST.scores, scores);
  const nextRound = command(s, 'nextRound'); const rid = s.rooms.TEST.round.id; E.applyCommand(s, 'identity-0', nextRound, bank, opts); assert.equal(s.rooms.TEST.round.id, rid);
  assert.throws(() => command(s, 'confirmTopic', 'identity-0', { roundId: final.roundId }), e => e.code === 'stale_round');
});
test('only own role projects; host management and reconnect never add secret permissions', () => {
  const s = setup(3); E.applyCommand(s, 'spectator', { room: 'TEST', action: 'join', name: 'Spectator', participate: false }, bank, opts); command(s, 'start'); command(s, 'confirmTopic');
  const truthful = s.rooms.TEST.members.find(p => p.id === s.rooms.TEST.round.truthfulId); const stableRole = s.rooms.TEST.round.truthfulId;
  for (const id of ['identity-0', 'identity-2', 'spectator', 'unjoined']) { const v = E.projectView(s, id, 'TEST', bank, { private: true }); assert.ok(!JSON.stringify(v).includes('SECRET_')); assert.ok(!JSON.stringify(v).includes('truthfulId')); assert.ok(!JSON.stringify(v).includes('identityId')); }
  const secret = E.projectView(s, truthful.identityId, 'TEST', bank, { private: true }); assert.equal(secret.privateCard.role, 'truthful'); assert.ok(secret.privateCard.secretAnswer.startsWith('SECRET_')); assert.equal(E.projectView(s, truthful.identityId, 'TEST', bank, { private: true }).privateCard.secretAnswer, secret.privateCard.secretAnswer);
  command(s, 'transferHost', 'identity-0', { targetId: s.rooms.TEST.members.find(p => p.identityId === 'identity-2').id }); assert.ok(!JSON.stringify(E.projectView(s, 'identity-2', 'TEST', bank, { private: true })).includes('SECRET_')); assert.equal(s.rooms.TEST.round.truthfulId, stableRole);
  assert.throws(() => command(s, 'beginDiscussion', 'spectator'), e => e.code === 'thinker_only');
});
test('answer delivery persists through cancellation, restart, room changes and canonical translations', () => {
  const s = setup(); command(s, 'start'); command(s, 'confirmTopic'); const q = s.rooms.TEST.round.questionId; const truth = s.rooms.TEST.members.find(p => p.id === s.rooms.TEST.round.truthfulId); E.projectView(s, truth.identityId, 'TEST', bank, { private: true }); command(s, 'cancelRound'); assert.notEqual(s.rooms.TEST.round.questionId, q); assert.ok(s.identities[truth.identityId].known[bank.find(x => x.id === q).canonicalKnowledgeId]);
  E.applyCommand(s, 'identity-0', { room: 'OTHER', action: 'create', name: 'P0', participate: true }, bank, opts); E.applyCommand(s, 'identity-1', { room: 'OTHER', action: 'join', name: 'P1', participate: true }, bank, opts); E.applyCommand(s, 'identity-2', { room: 'OTHER', action: 'join', name: 'P2', participate: true }, bank, opts); command(s, 'start', 'identity-0', {}, 'OTHER'); assert.notEqual(s.rooms.OTHER.round.questionId, q);
  const translated = [{ ...bank.find(x => x.id === q), id: 'translated', locale: 'zh-TW' }]; assert.equal(E.availableQuestions(s, s.rooms.OTHER, translated).length, 0);
});
test('deck shortage reports remaining; no hidden reuse or history wipe', () => { const s = setup(); for (const id of Object.keys(s.identities)) s.identities[id].known = Object.fromEntries(bank.map(q => [q.canonicalKnowledgeId, { at: 1000, reason: 'test' }])); command(s, 'start'); const view = E.projectView(s, 'identity-0', 'TEST', bank); assert.equal(view.availability.remaining, 0); assert.equal(view.round.topic, null); assert.throws(() => command(s, 'confirmTopic'), e => e.code === 'deck_exhausted'); assert.equal(Object.keys(s.identities['identity-0'].known).length, 70); });
for (const count of [3, 6, 9]) test(`complete ${count}-player game: each Thinker once, no automatic phase changes, final standings and round clamp`, () => {
  const s = setup(count); command(s, 'start'); const originalRoster = [...s.rooms.TEST.roster]; const thinkers = [];
  for (let i = 0; i < count; i++) { const room = s.rooms.TEST; const r = room.round; const thinker = room.members.find(p => p.id === r.thinkerId).identityId; thinkers.push(r.thinkerId); command(s, 'confirmTopic'); command(s, 'beginDiscussion'); for (let j = 0; j < count - 1; j++) command(s, 'nextSpotlight', thinker); E.projectView(s, thinker, 'TEST', bank, { now: 1000 + 10000000 }); assert.equal(room.phase, 'discussion'); command(s, 'identify', thinker, { targetId: r.truthfulId }); assert.equal(room.phase, 'reveal'); for (const p of room.members) E.projectView(s, p.identityId, 'TEST', bank, { private: true }); assert.equal(room.phase, 'reveal'); command(s, 'nextRound'); }
  const view = E.projectView(s, 'identity-0', 'TEST', bank); assert.equal(view.phase, 'results'); assert.equal(view.round.number, count); assert.equal(view.round.total, count); assert.equal(view.availability.requiredRounds, 0); assert.deepEqual(thinkers, originalRoster); assert.equal(new Set(thinkers).size, count); assert.equal(view.history.length, count); assert.equal(Object.values(view.scores).reduce((a, b) => a + b, 0), count * 4);
  command(s, 'restart'); assert.equal(s.rooms.TEST.phase, 'lobby'); assert.ok(Object.values(s.identities).every(who => Object.keys(who.known).length === count));
});
test('public projection does not revive disconnected players or reveal per-player readiness', () => { const s = setup(); command(s, 'start'); command(s, 'confirmTopic'); command(s, 'ready', 'identity-1'); const v = E.projectView(s, 'identity-0', 'TEST', bank, { now: 100000 }); assert.equal(v.players.filter(p => p.connected).length, 0); assert.equal(v.round.readyCount, 1); assert.equal(v.round.allReady, false); assert.equal(v.privateCard, null); assert.ok(!JSON.stringify(v).includes('readyIds')); assert.equal(s.rooms.TEST.members[1].lastSeen, 1000); });
