// Real shared membership control DOM: correct seats, source transitions and own return.
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{webcrypto}=require('node:crypto');
function fixture(){class Node{constructor(){this.children=[];this.parent=null;this.textContent='';}get firstChild(){return this.children[0];}get lastChild(){return this.children.at(-1);}append(...nodes){for(const node of nodes){node.parent=this;this.children.push(node);}}replaceChildren(...nodes){this.children=[];this.append(...nodes);}remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);}}
 const body=new Node(),find=(node,id)=>node.id===id?node:node.children.map(n=>find(n,id)).find(Boolean);
 const document={body,hidden:false,documentElement:{lang:'en'},createElement:()=>new Node(),getElementById:id=>find(body,id),addEventListener(){}};
 const context=vm.createContext({crypto:webcrypto,Date,Promise,AbortSignal,document,window:{addEventListener(){}},setInterval:()=>1,clearInterval(){},fetch:async()=>({ok:true,json:async()=>({ok:true})})});vm.runInContext(fs.readFileSync(require.resolve('../hub-executor.js'),'utf8'),context);return{context,H:context.HUB_EXECUTOR,document};}
const ticket=game=>({game,capsule:'sealed-current',token:'own-private'});
const rows=[{playerNum:1,name:'First',active:true},{playerNum:2,name:'Away',active:false},{playerNum:3,name:'New',active:true,pending:true,memberStatus:'next_round'}];
const dixit={game:'dixit',playerNum:1,dixit:{roster:rows,membership:{enabled:true}}};
test('Bluff shows actual positive numbered players and excludes the unseated manager',()=>{const f=fixture();f.H.membershipControl({players:[{playerNum:0,name:'Manager'},...rows],membership:{enabled:true}},ticket('bluffking'),0);assert.equal(f.document.getElementById('hub-membership-controls').children[1].children.length,3);});
test('switching the same player page from story cards to CUT removes the previous participant panel',()=>{const f=fixture();f.H.membershipControl(dixit,ticket('dixit'));assert.ok(f.document.getElementById('hub-membership-controls'));f.H.membershipControl({game:'cut',cut:{roster:rows,membership:{enabled:true}}},ticket('cut'));assert.equal(f.document.getElementById('hub-membership-controls'),undefined);});
test('a legacy or missing executor card clears retained membership controls',()=>{const f=fixture();f.H.membershipControl(dixit,ticket('dixit'));f.H.observe({game:'scene'},'own-private');assert.equal(f.document.getElementById('hub-membership-controls'),undefined);});
test('away participants can return themselves while all other membership controls remain disabled',()=>{const f=fixture();f.H.membershipControl({...dixit,playerNum:2},ticket('dixit'));const controls=f.document.getElementById('hub-membership-controls').children[1].children;assert.deepEqual(controls.map(row=>row.lastChild.disabled),[true,false,true]);assert.equal(controls[1].lastChild.textContent,'Rejoin');});
test('the home manager retains every membership control even when its participating seat sits out',()=>{const f=fixture();f.H.membershipControl({...dixit,playerNum:2},ticket('dixit'),0);const controls=f.document.getElementById('hub-membership-controls').children[1].children;assert.deepEqual(controls.map(row=>row.lastChild.disabled),[false,false,false]);});
