// Independent Beta prompts: edit these without changing the original game.
const GAME_DATA = {
  forbidden: [
    { word: 'Horse', emoji: '🐴' },
    { word: 'Cow', emoji: '🐄' },
    { word: 'Sheep', emoji: '🐑' },
    { word: 'Pig', emoji: '🐷' },
    { word: 'Duck', emoji: '🦆' },
    { word: 'Rabbit', emoji: '🐰' },
    { word: 'Turtle', emoji: '🐢' },
    { word: 'Frog', emoji: '🐸' },
    { word: 'Bird', emoji: '🐦' },
    { word: 'Lion', emoji: '🦁' },
    { word: 'Tiger', emoji: '🐯' },
    { word: 'Bear', emoji: '🐻' },
    { word: 'Monkey', emoji: '🐵' },
    { word: 'Elephant', emoji: '🐘' },
    { word: 'Snake', emoji: '🐍' },
    { word: 'Spider', emoji: '🕷️' },
    { word: 'Butterfly', emoji: '🦋' },
    { word: 'Bee', emoji: '🐝' },
    { word: 'Ant', emoji: '🐜' },
    { word: 'Red', emoji: '🔴' },
    { word: 'Blue', emoji: '🔵' },
    { word: 'Green', emoji: '🟢' },
    { word: 'Yellow', emoji: '🟡' },
    { word: 'Purple', emoji: '🟣' },
    { word: 'Pink', emoji: '💗' },
    { word: 'Black', emoji: '⚫' },
    { word: 'White', emoji: '⚪' },
    { word: 'Brown', emoji: '🟤' },
    { word: 'Gray', emoji: '🩶' },
    { word: 'Hundred', emoji: '💯' },
    { word: 'Hand', emoji: '✋' },
    { word: 'Foot', emoji: '🦶' },
    { word: 'Eye', emoji: '👁️' },
    { word: 'Ear', emoji: '👂' },
    { word: 'Nose', emoji: '👃' },
    { word: 'Mouth', emoji: '👄' },
    { word: 'Finger', emoji: '☝️' },
    { word: 'Arm', emoji: '💪' },
    { word: 'Leg', emoji: '🦵' },
    { word: 'Back', emoji: '↩️' },
    { word: 'Knee', emoji: '🦵' },
    { word: 'Mother', emoji: '👩' },
    { word: 'Father', emoji: '👨' },
    { word: 'Sister', emoji: '👧' },
    { word: 'Brother', emoji: '👦' },
    { word: 'Cousin', emoji: '🧑' },
    { word: 'Uncle', emoji: '👨‍🦳' },
    { word: 'Aunt', emoji: '👩‍🦳' },
    { word: 'Grandmother', emoji: '👵' },
    { word: 'Grandfather', emoji: '👴' },
    { word: 'Neighbor', emoji: '🏘️' },
    { word: 'Stranger', emoji: '❓' },
    { word: 'Partner', emoji: '💑' },
    { word: 'Roommate', emoji: '🏠' },
    { word: 'Run', emoji: '🏃' },
    { word: 'Walk', emoji: '🚶' },
    { word: 'Jump', emoji: '🤸' },
    { word: 'Dance', emoji: '💃' },
    { word: 'Sing', emoji: '🎤' },
    { word: 'Laugh', emoji: '😂' },
    { word: 'Cry', emoji: '😢' },
    { word: 'Talk', emoji: '🗣️' },
    { word: 'Listen', emoji: '👂' },
    { word: 'Think', emoji: '🤔' },
    { word: 'Remember', emoji: '🧠' },
    { word: 'Forget', emoji: '🤷' },
    { word: 'Wait', emoji: '⏳' },
    { word: 'Worry', emoji: '😟' },
    { word: 'Shout', emoji: '📢' },
    { word: 'Whisper', emoji: '🤫' },
    { word: 'Argue', emoji: '😤' },
    { word: 'Apologize', emoji: '🙏' },
    { word: 'Promise', emoji: '🤞' },
    { word: 'Explain', emoji: '💡' },
    { word: 'Decide', emoji: '⚖️' },
    { word: 'Choose', emoji: '☑️' },
    { word: 'Guess', emoji: '🎲' },
    { word: 'Table', emoji: '🪑' },
    { word: 'Curtain', emoji: '🪟' },
    { word: 'Shelf', emoji: '📚' },
    { word: 'Drawer', emoji: '🗄️' },
    { word: 'Closet', emoji: '🚪' },
    { word: 'Roof', emoji: '🏠' },
    { word: 'Fence', emoji: '🚧' },
    { word: 'Staircase', emoji: '🪜' },
    { word: 'Elevator', emoji: '🛗' },
    { word: 'Basement', emoji: '🕳️' },
    { word: 'Spoon', emoji: '🥄' },
    { word: 'Fork', emoji: '🍴' },
    { word: 'Knife', emoji: '🔪' },
    { word: 'Cup', emoji: '☕' },
    { word: 'Glass', emoji: '🥛' },
    { word: 'Bottle', emoji: '🍾' },
    { word: 'Oven', emoji: '🔥' },
    { word: 'Stove', emoji: '🍳' },
    { word: 'Kettle', emoji: '🫖' },
    { word: 'Backpack', emoji: '🎒' },
    { word: 'Pen', emoji: '🖊️' },
    { word: 'Ruler', emoji: '📏' },
    { word: 'Eraser', emoji: '🧼' },
    { word: 'Classroom', emoji: '🏫' },
    { word: 'Lecture', emoji: '🎙️' },
    { word: 'Textbook', emoji: '📘' },
    { word: 'Assignment', emoji: '📝' },
    { word: 'Quiz', emoji: '❓' },
    { word: 'Certificate', emoji: '📜' },
    { word: 'Resume', emoji: '📄' },
    { word: 'Invoice', emoji: '🧾' },
    { word: 'Budget', emoji: '💵' },
    { word: 'Manager', emoji: '🧑‍💼' },
    { word: 'Colleague', emoji: '🧑‍🤝‍🧑' },
    { word: 'Intern', emoji: '🎓' },
    { word: 'Tablet', emoji: '📱' },
    { word: 'Printer', emoji: '🖨️' },
    { word: 'Router', emoji: '📶' },
    { word: 'Camera', emoji: '📷' },
    { word: 'Speaker', emoji: '🔊' },
    { word: 'Microphone', emoji: '🎤' },
    { word: 'Remote', emoji: '📺' },
    { word: 'Cable', emoji: '🔌' },
    { word: 'Screen', emoji: '🖥️' },
    { word: 'Keyboard', emoji: '⌨️' },
    { word: 'Software', emoji: '💿' },
    { word: 'File', emoji: '📁' },
    { word: 'Download', emoji: '⬇️' },
    { word: 'Upload', emoji: '⬆️' },
    { word: 'Football', emoji: '🏈' },
    { word: 'Basketball', emoji: '🏀' },
    { word: 'Soccer', emoji: '⚽' },
    { word: 'Swimming', emoji: '🏊' },
    { word: 'Cycling', emoji: '🚴' },
    { word: 'Hiking', emoji: '🥾' },
    { word: 'Painting', emoji: '🎨' },
    { word: 'Drawing', emoji: '✏️' },
    { word: 'Fishing', emoji: '🎣' },
    { word: 'Camping', emoji: '⛺' },
    { word: 'Yoga', emoji: '🧘' },
    { word: 'Puzzle', emoji: '🧩' },
    { word: 'Chess', emoji: '♟️' },
    { word: 'Funny', emoji: '😄' },
    { word: 'Strange', emoji: '🤨' },
    { word: 'Lucky', emoji: '🍀' },
    { word: 'Brave', emoji: '🦁' },
    { word: 'Clever', emoji: '🧠' },
    { word: 'Honest', emoji: '🤝' },
    { word: 'Polite', emoji: '🙇' },
    { word: 'Rude', emoji: '😤' },
    { word: 'Generous', emoji: '🎁' },
    { word: 'Stubborn', emoji: '🐴' },
    { word: 'Patient', emoji: '⏳' },
    { word: 'Careful', emoji: '⚠️' },
    { word: 'Lightning', emoji: '⚡' },
    { word: 'Rainbow', emoji: '🌈' },
    { word: 'Breeze', emoji: '🍃' },
    { word: 'Drought', emoji: '🏜️' },
    { word: 'Flood', emoji: '🌊' },
    { word: 'Earthquake', emoji: '🌍' },
    { word: 'Volcano', emoji: '🌋' },
    { word: 'Desert', emoji: '🐫' },
    { word: 'Valley', emoji: '⛰️' },
    { word: 'Cliff', emoji: '🧗' },
    { word: 'Cave', emoji: '🕳️' },
    { word: 'Waterfall', emoji: '💦' },
    { word: 'Stadium', emoji: '🏟️' },
    { word: 'Theater', emoji: '🎭' },
    { word: 'Cinema', emoji: '🎬' },
    { word: 'Bridge', emoji: '🌉' },
    { word: 'Harbor', emoji: '⚓' },
    { word: 'Village', emoji: '🏘️' },
    { word: 'City', emoji: '🏙️' },
    { word: 'Town', emoji: '🏡' },
    { word: 'Countryside', emoji: '🌾' },
    { word: 'Border', emoji: '🚧' },
    { word: 'Highway', emoji: '🛣️' },
    { word: 'Sidewalk', emoji: '🚶' },
    { word: 'Parking Lot', emoji: '🅿️' },
    { word: 'Playground', emoji: '🛝' },
    { word: 'Ticket', emoji: '🎟️' },
    { word: 'Receipt', emoji: '🧾' },
    { word: 'Coupon', emoji: '🎫' },
    { word: 'Discount', emoji: '🏷️' },
    { word: 'Refund', emoji: '💸' },
    { word: 'Warranty', emoji: '📋' },
    { word: 'Insurance', emoji: '🛡️' },
    { word: 'Passport', emoji: '🛂' },
    { word: 'License', emoji: '🪪' },
    { word: 'Signature', emoji: '✍️' },
    { word: 'Envelope', emoji: '✉️' },
    { word: 'Package', emoji: '📦' },
    { word: 'Delivery', emoji: '🚚' },
    { word: 'Address', emoji: '📍' },
    { word: 'Neighborhood', emoji: '🏘️' },
    { word: 'Community', emoji: '🤝' },
    { word: 'Crowd', emoji: '👥' },
    { word: 'Audience', emoji: '🎭' },
    { word: 'Guest', emoji: '🧑‍🤝‍🧑' },
    { word: 'Host', emoji: '🎙️' },
    { word: 'Volunteer', emoji: '🙋' },
    { word: 'Charity', emoji: '❤️' },
    { word: 'Donation', emoji: '🎁' },
  ],

  kangaroo: [
    { emoji: '🎧', charge: "wearing headphones with no music playing, just to avoid talking to people" },
    { emoji: '🧾', charge: "saving a receipt for a year, then throwing it away the week it's finally needed" },
    { emoji: '🚦', charge: "speeding up when a light turns yellow, then insisting they always drive safely" },
    { emoji: '🍿', charge: "bringing snacks into a movie, then rustling the loudest bag in the building" },
    { emoji: '📦', charge: "ordering something online, then acting shocked when it actually arrives" },
    { emoji: '🧴', charge: "using someone else's shampoo in the shower and never mentioning it" },
    { emoji: '🎮', charge: "rage-quitting a game, then telling everyone it was \"about to get boring anyway\"" },
    { emoji: '🧻', charge: "using the last of the toilet paper and leaving the empty roll right there" },
    { emoji: '🍳', charge: "cooking a huge meal, then leaving every dirty pan for \"just five more minutes\"" },
    { emoji: '📺', charge: "watching the next episode without the group, then pretending not to know what happens" },
    { emoji: '🧢', charge: "wearing sunglasses indoors and claiming it's a medical thing" },
    { emoji: '🚲', charge: "borrowing a bike \"just for the afternoon\" and returning it three weeks later" },
    { emoji: '🎂', charge: "eating the last piece of cake, then denying any cake ever existed" },
    { emoji: '📖', charge: "dog-earing every page of a borrowed book instead of using a bookmark" },
    { emoji: '🧑‍🍳', charge: "claiming a recipe is a secret family tradition that they found five minutes ago online" },
    { emoji: '🛒', charge: "taking the shopping cart with the wobbly wheel, every single time" },
    { emoji: '🎤', charge: "insisting on doing karaoke, then mumbling every single lyric" },
    { emoji: '🧊', charge: "putting an empty ice tray back in the freezer instead of refilling it" },
    { emoji: '📸', charge: "taking forty photos of the same sunset and posting none of them" },
    { emoji: '🛍️', charge: "returning something \"unused\" with the tags clearly reattached" },
    { emoji: '🚪', charge: "knocking on a door, then walking away before anyone answers" },
    { emoji: '🧦', charge: "owning eleven single socks and refusing to throw any of them away" },
    { emoji: '📺', charge: "falling asleep during a movie, then insisting they saw the whole thing" },
    { emoji: '🍫', charge: "hiding chocolate from themselves, then forgetting where they hid it" },
    { emoji: '🚿', charge: "singing in the shower loud enough for the whole street to hear" },
    { emoji: '🧑‍💻', charge: "leaving a video call on \"to be polite,\" then muting and walking away entirely" },
    { emoji: '🥤', charge: "ordering a large drink just to get free refills, then leaving after one" },
    { emoji: '🎬', charge: "spoiling the ending of a movie, then acting shocked that people are upset" },
    { emoji: '🧹', charge: "sweeping dust into a corner instead of into a dustpan" },
    { emoji: '🐦', charge: "yelling at a bird outside the window like it can understand English" },
  ],

  kangarooWitness: [
    { emoji: '🧑‍🏫', name: 'The Old Teacher', evidence: 'remembers this exact behavior from years ago' },
    { emoji: '🧑‍✈️', name: 'The Flight Attendant', evidence: 'brings up something that happened at 30,000 feet' },
    { emoji: '🧑‍🎤', name: 'The Karaoke Host', evidence: 'has strong opinions about the song choice that night' },
    { emoji: '🧑‍🌾', name: 'The Farmer', evidence: 'brings a very specific story involving livestock' },
    { emoji: '🧑‍⚕️', name: 'The Dentist', evidence: 'recalls something said mid-appointment, unprompted' },
    { emoji: '🐦', name: "The Neighbor's Parrot", evidence: 'apparently repeats exactly what it heard' },
    { emoji: '🧑‍🚒', name: 'The Firefighter', evidence: 'was at the scene for reasons still unclear' },
    { emoji: '🧑‍🎨', name: 'The Street Artist', evidence: 'sketched the whole thing from memory' },
    { emoji: '🧳', name: 'The Hotel Concierge', evidence: 'remembers an unusual request at check-in' },
    { emoji: '🧑‍🔬', name: 'The Lab Partner', evidence: 'brings a very detailed, very unnecessary chart' },
    { emoji: '🧑‍🍼', name: 'The Babysitter', evidence: 'was told to "never mention this to anyone"' },
    { emoji: '🚌', name: 'The Bus Driver', evidence: 'remembers exactly which stop they got off at' },
    { emoji: '🧑‍🚀', name: 'The Former Roommate', evidence: 'brings up an unpaid bill from years ago' },
    { emoji: '🧑‍💼', name: 'The Former Boss', evidence: 'has a performance review that is oddly relevant' },
    { emoji: '🦜', name: "The Pet Store Employee", evidence: 'sold them something they clearly regretted' },
    { emoji: '🧑‍🎓', name: 'The College Roommate', evidence: 'brings a photo nobody wanted resurfaced' },
    { emoji: '🧑‍⚖️', name: "The Wedding Officiant", evidence: 'remembers a very awkward toast' },
    { emoji: '🧑‍🍳', name: 'The Food Truck Owner', evidence: 'recalls a suspiciously large solo order' },
    { emoji: '🧑‍🏭', name: 'The Building Doorman', evidence: 'has seen every single late-night arrival' },
    { emoji: '🐕', name: "The Ex's Dog", evidence: 'is presented in the room, wearing a tiny witness badge' },
    { emoji: '🧑‍🎓', name: 'The Substitute Teacher', evidence: 'only worked there one day and remembers everything' },
    { emoji: '🧑‍🔧', name: 'The Locksmith', evidence: 'was called at a very suspicious hour' },
    { emoji: '🧑‍🎤', name: 'The Wedding Band Singer', evidence: 'took a very specific song request that night' },
    { emoji: '🧑‍💻', name: 'The IT Guy', evidence: 'saw the browser history before anyone could close it' },
  ],
};
